; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt  < %s -S -loop-swp -loop-software-pipelining=true | FileCheck %s

target triple = "tpc"

; Function Attrs: nounwind
define dso_local void @main(i32 %roundingMode) local_unnamed_addr #0 {
; CHECK-LABEL: @main(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.tpc.ld.l.i32(i32 3240, i32 1, i32 undef, i1 true, i1 false)
; CHECK-NEXT:    tail call void @llvm.tpc.st.l.i32(i32 3240, i32 [[ROUNDINGMODE:%.*]], i32 1, i1 true, i1 false)
; CHECK-NEXT:    [[TMP1:%.*]] = tail call <5 x i32> @llvm.tpc.get.index.space.offset()
; CHECK-NEXT:    [[TMP2:%.*]] = tail call <5 x i32> @llvm.tpc.get.index.space.size()
; CHECK-NEXT:    [[ADD:%.*]] = add <5 x i32> [[TMP2]], [[TMP1]]
; CHECK-NEXT:    [[VECEXT:%.*]] = extractelement <5 x i32> [[TMP1]], i32 1
; CHECK-NEXT:    [[MUL1:%.*]] = shl nsw i32 [[VECEXT]], 2
; CHECK-NEXT:    [[VECEXT2:%.*]] = extractelement <5 x i32> [[ADD]], i32 1
; CHECK-NEXT:    [[MUL4:%.*]] = shl i32 [[VECEXT2]], 2
; CHECK-NEXT:    [[VECEXT5:%.*]] = extractelement <5 x i32> [[TMP1]], i32 2
; CHECK-NEXT:    [[VECEXT7:%.*]] = extractelement <5 x i32> [[ADD]], i32 2
; CHECK-NEXT:    [[CMP60:%.*]] = icmp slt i32 [[VECEXT5]], [[VECEXT7]]
; CHECK-NEXT:    br i1 [[CMP60]], label [[FOR_BODY_LR_PH:%.*]], label [[FOR_COND_CLEANUP:%.*]]
; CHECK:       for.body.lr.ph:
; CHECK-NEXT:    [[CMP1056:%.*]] = icmp slt i32 [[MUL1]], [[MUL4]]
; CHECK-NEXT:    br label [[FOR_BODY:%.*]]
; CHECK:       for.cond.cleanup.loopexit:
; CHECK-NEXT:    br label [[FOR_COND_CLEANUP]]
; CHECK:       for.cond.cleanup:
; CHECK-NEXT:    tail call void @llvm.tpc.st.l.i32(i32 3240, i32 [[TMP0]], i32 1, i1 true, i1 false)
; CHECK-NEXT:    ret void
; CHECK:       for.body:
; CHECK-NEXT:    [[H_062:%.*]] = phi i32 [ [[VECEXT5]], [[FOR_BODY_LR_PH]] ], [ [[ADD15:%.*]], [[FOR_COND_CLEANUP11:%.*]] ]
; CHECK-NEXT:    [[IFMCOORDS_061:%.*]] = phi <5 x i32> [ undef, [[FOR_BODY_LR_PH]] ], [ [[IFMCOORDS_1_LCSSA:%.*]], [[FOR_COND_CLEANUP11]] ]
; CHECK-NEXT:    [[TMP3:%.*]] = tail call <5 x i32> @llvm.tpc.set.indx(<5 x i32> [[IFMCOORDS_061]], i32 4, i32 [[H_062]], i32 0, i1 true, i1 false)
; CHECK-NEXT:    [[TMP4:%.*]] = tail call <5 x i32> @llvm.tpc.set.indx(<5 x i32> [[TMP3]], i32 2, i32 [[MUL1]], i32 0, i1 true, i1 false)
; CHECK-NEXT:    [[TMP5:%.*]] = tail call <5 x i32> @llvm.tpc.add.mask.v5i32.v5i32(<5 x i32> <i32 64, i32 64, i32 64, i32 64, i32 64>, <5 x i32> [[TMP4]], i32 1, i8 2, i32 0, <5 x i32> [[TMP4]], i1 true, i1 false)
; CHECK-NEXT:    br i1 [[CMP1056]], label [[FOR_BODY12_PREHEADER:%.*]], label [[FOR_COND_CLEANUP11]]
; CHECK:       for.body12.preheader:
; CHECK-NEXT:    [[TMP6:%.*]] = phi i32 [ [[MUL1]], [[FOR_BODY]] ]
; CHECK-NEXT:    [[TMP7:%.*]] = phi <5 x i32> [ [[TMP4]], [[FOR_BODY]] ]
; CHECK-NEXT:    [[TMP8:%.*]] = tail call <128 x half> @llvm.tpc.ld.tnsr.v128f16.i1(<5 x i32> [[TMP7]], i8 0, i32 16, <128 x half> undef, i1 true, i1 false)
; CHECK-NEXT:    [[TMP9:%.*]] = tail call <5 x i32> @llvm.tpc.add.mask.v5i32.v5i32(<5 x i32> <i32 1, i32 1, i32 1, i32 1, i32 1>, <5 x i32> [[TMP7]], i32 2, i8 2, i32 0, <5 x i32> [[TMP7]], i1 true, i1 false)
; CHECK-NEXT:    [[TMP10:%.*]] = tail call <128 x half> @llvm.tpc.ld.tnsr.v128f16.i1(<5 x i32> [[TMP9]], i8 0, i32 16, <128 x half> undef, i1 true, i1 false)
; CHECK-NEXT:    [[TMP11:%.*]] = tail call <5 x i32> @llvm.tpc.add.mask.v5i32.v5i32(<5 x i32> <i32 1, i32 1, i32 1, i32 1, i32 1>, <5 x i32> [[TMP9]], i32 2, i8 2, i32 0, <5 x i32> [[TMP9]], i1 true, i1 false)
; CHECK-NEXT:    [[TMP12:%.*]] = tail call <128 x half> @llvm.tpc.ld.tnsr.v128f16.i1(<5 x i32> [[TMP11]], i8 0, i32 16, <128 x half> undef, i1 true, i1 false)
; CHECK-NEXT:    [[TMP13:%.*]] = tail call <5 x i32> @llvm.tpc.add.mask.v5i32.v5i32(<5 x i32> <i32 1, i32 1, i32 1, i32 1, i32 1>, <5 x i32> [[TMP11]], i32 2, i8 2, i32 0, <5 x i32> [[TMP11]], i1 true, i1 false)
; CHECK-NEXT:    [[TMP14:%.*]] = tail call <128 x half> @llvm.tpc.ld.tnsr.v128f16.i1(<5 x i32> [[TMP13]], i8 0, i32 16, <128 x half> undef, i1 true, i1 false)
; CHECK-NEXT:    [[TMP15:%.*]] = tail call <5 x i32> @llvm.tpc.add.mask.v5i32.v5i32(<5 x i32> <i32 1, i32 1, i32 1, i32 1, i32 1>, <5 x i32> [[TMP13]], i32 2, i8 2, i32 0, <5 x i32> [[TMP13]], i1 true, i1 false)
; CHECK-NEXT:    [[TMP16:%.*]] = add i32 [[TMP6]], 4
; CHECK-NEXT:    [[TMP17:%.*]] = icmp eq i32 [[TMP16]], [[MUL4]]
; CHECK-NEXT:    br i1 [[TMP17]], label [[FOR_COND_CLEANUP11_LOOPEXIT:%.*]], label [[FOR_BODY12:%.*]]
; CHECK:       for.cond.cleanup11.loopexit:
; CHECK-NEXT:    [[TMP18:%.*]] = phi <5 x i32> [ [[TMP76:%.*]], [[FOR_BODY12]] ], [ [[TMP5]], [[FOR_BODY12_PREHEADER]] ]
; CHECK-NEXT:    [[TMP19:%.*]] = phi <5 x i32> [ [[TMP4]], [[FOR_BODY12_PREHEADER]] ], [ [[TMP74:%.*]], [[FOR_BODY12]] ]
; CHECK-NEXT:    [[DOTLCSSA:%.*]] = phi <5 x i32> [ [[TMP75:%.*]], [[FOR_BODY12]] ], [ [[TMP15]], [[FOR_BODY12_PREHEADER]] ]
; CHECK-NEXT:    [[TMP20:%.*]] = phi <128 x half> [ [[TMP49:%.*]], [[FOR_BODY12]] ], [ [[TMP8]], [[FOR_BODY12_PREHEADER]] ]
; CHECK-NEXT:    [[TMP21:%.*]] = phi <128 x half> [ [[TMP56:%.*]], [[FOR_BODY12]] ], [ [[TMP10]], [[FOR_BODY12_PREHEADER]] ]
; CHECK-NEXT:    [[TMP22:%.*]] = phi <128 x half> [ [[TMP63:%.*]], [[FOR_BODY12]] ], [ [[TMP12]], [[FOR_BODY12_PREHEADER]] ]
; CHECK-NEXT:    [[TMP23:%.*]] = phi <128 x half> [ [[TMP70:%.*]], [[FOR_BODY12]] ], [ [[TMP14]], [[FOR_BODY12_PREHEADER]] ]
; CHECK-NEXT:    [[TMP24:%.*]] = tail call <128 x float> @llvm.tpc.convert.v128f32.v128f16.i1(<128 x half> [[TMP20]], i8 11, i32 0, <128 x float> undef, i1 true, i1 false)
; CHECK-NEXT:    [[TMP25:%.*]] = shufflevector <128 x float> [[TMP24]], <128 x float> undef, <64 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
; CHECK-NEXT:    [[TMP26:%.*]] = shufflevector <128 x float> [[TMP24]], <128 x float> undef, <64 x i32> <i32 64, i32 65, i32 66, i32 67, i32 68, i32 69, i32 70, i32 71, i32 72, i32 73, i32 74, i32 75, i32 76, i32 77, i32 78, i32 79, i32 80, i32 81, i32 82, i32 83, i32 84, i32 85, i32 86, i32 87, i32 88, i32 89, i32 90, i32 91, i32 92, i32 93, i32 94, i32 95, i32 96, i32 97, i32 98, i32 99, i32 100, i32 101, i32 102, i32 103, i32 104, i32 105, i32 106, i32 107, i32 108, i32 109, i32 110, i32 111, i32 112, i32 113, i32 114, i32 115, i32 116, i32 117, i32 118, i32 119, i32 120, i32 121, i32 122, i32 123, i32 124, i32 125, i32 126, i32 127>
; CHECK-NEXT:    tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> [[TMP19]], i8 1, <64 x float> [[TMP25]], i32 0, i1 true, i1 false)
; CHECK-NEXT:    tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> [[TMP18]], i8 1, <64 x float> [[TMP26]], i32 0, i1 true, i1 false)
; CHECK-NEXT:    [[TMP27:%.*]] = tail call <128 x float> @llvm.tpc.convert.v128f32.v128f16.i1(<128 x half> [[TMP21]], i8 11, i32 0, <128 x float> undef, i1 true, i1 false)
; CHECK-NEXT:    [[TMP28:%.*]] = shufflevector <128 x float> [[TMP27]], <128 x float> undef, <64 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
; CHECK-NEXT:    [[TMP29:%.*]] = shufflevector <128 x float> [[TMP27]], <128 x float> undef, <64 x i32> <i32 64, i32 65, i32 66, i32 67, i32 68, i32 69, i32 70, i32 71, i32 72, i32 73, i32 74, i32 75, i32 76, i32 77, i32 78, i32 79, i32 80, i32 81, i32 82, i32 83, i32 84, i32 85, i32 86, i32 87, i32 88, i32 89, i32 90, i32 91, i32 92, i32 93, i32 94, i32 95, i32 96, i32 97, i32 98, i32 99, i32 100, i32 101, i32 102, i32 103, i32 104, i32 105, i32 106, i32 107, i32 108, i32 109, i32 110, i32 111, i32 112, i32 113, i32 114, i32 115, i32 116, i32 117, i32 118, i32 119, i32 120, i32 121, i32 122, i32 123, i32 124, i32 125, i32 126, i32 127>
; CHECK-NEXT:    [[TMP30:%.*]] = tail call <5 x i32> @llvm.tpc.add.mask.v5i32.v5i32(<5 x i32> <i32 1, i32 1, i32 1, i32 1, i32 1>, <5 x i32> [[TMP19]], i32 2, i8 2, i32 0, <5 x i32> [[TMP19]], i1 true, i1 false)
; CHECK-NEXT:    tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> [[TMP30]], i8 1, <64 x float> [[TMP28]], i32 0, i1 true, i1 false)
; CHECK-NEXT:    [[TMP31:%.*]] = tail call <5 x i32> @llvm.tpc.add.mask.v5i32.v5i32(<5 x i32> <i32 1, i32 1, i32 1, i32 1, i32 1>, <5 x i32> [[TMP18]], i32 2, i8 2, i32 0, <5 x i32> [[TMP18]], i1 true, i1 false)
; CHECK-NEXT:    tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> [[TMP31]], i8 1, <64 x float> [[TMP29]], i32 0, i1 true, i1 false)
; CHECK-NEXT:    [[TMP32:%.*]] = tail call <128 x float> @llvm.tpc.convert.v128f32.v128f16.i1(<128 x half> [[TMP22]], i8 11, i32 0, <128 x float> undef, i1 true, i1 false)
; CHECK-NEXT:    [[TMP33:%.*]] = shufflevector <128 x float> [[TMP32]], <128 x float> undef, <64 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
; CHECK-NEXT:    [[TMP34:%.*]] = shufflevector <128 x float> [[TMP32]], <128 x float> undef, <64 x i32> <i32 64, i32 65, i32 66, i32 67, i32 68, i32 69, i32 70, i32 71, i32 72, i32 73, i32 74, i32 75, i32 76, i32 77, i32 78, i32 79, i32 80, i32 81, i32 82, i32 83, i32 84, i32 85, i32 86, i32 87, i32 88, i32 89, i32 90, i32 91, i32 92, i32 93, i32 94, i32 95, i32 96, i32 97, i32 98, i32 99, i32 100, i32 101, i32 102, i32 103, i32 104, i32 105, i32 106, i32 107, i32 108, i32 109, i32 110, i32 111, i32 112, i32 113, i32 114, i32 115, i32 116, i32 117, i32 118, i32 119, i32 120, i32 121, i32 122, i32 123, i32 124, i32 125, i32 126, i32 127>
; CHECK-NEXT:    [[TMP35:%.*]] = tail call <5 x i32> @llvm.tpc.add.mask.v5i32.v5i32(<5 x i32> <i32 1, i32 1, i32 1, i32 1, i32 1>, <5 x i32> [[TMP30]], i32 2, i8 2, i32 0, <5 x i32> [[TMP30]], i1 true, i1 false)
; CHECK-NEXT:    tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> [[TMP35]], i8 1, <64 x float> [[TMP33]], i32 0, i1 true, i1 false)
; CHECK-NEXT:    [[TMP36:%.*]] = tail call <5 x i32> @llvm.tpc.add.mask.v5i32.v5i32(<5 x i32> <i32 1, i32 1, i32 1, i32 1, i32 1>, <5 x i32> [[TMP31]], i32 2, i8 2, i32 0, <5 x i32> [[TMP31]], i1 true, i1 false)
; CHECK-NEXT:    tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> [[TMP36]], i8 1, <64 x float> [[TMP34]], i32 0, i1 true, i1 false)
; CHECK-NEXT:    [[TMP37:%.*]] = tail call <128 x float> @llvm.tpc.convert.v128f32.v128f16.i1(<128 x half> [[TMP23]], i8 11, i32 0, <128 x float> undef, i1 true, i1 false)
; CHECK-NEXT:    [[TMP38:%.*]] = shufflevector <128 x float> [[TMP37]], <128 x float> undef, <64 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
; CHECK-NEXT:    [[TMP39:%.*]] = shufflevector <128 x float> [[TMP37]], <128 x float> undef, <64 x i32> <i32 64, i32 65, i32 66, i32 67, i32 68, i32 69, i32 70, i32 71, i32 72, i32 73, i32 74, i32 75, i32 76, i32 77, i32 78, i32 79, i32 80, i32 81, i32 82, i32 83, i32 84, i32 85, i32 86, i32 87, i32 88, i32 89, i32 90, i32 91, i32 92, i32 93, i32 94, i32 95, i32 96, i32 97, i32 98, i32 99, i32 100, i32 101, i32 102, i32 103, i32 104, i32 105, i32 106, i32 107, i32 108, i32 109, i32 110, i32 111, i32 112, i32 113, i32 114, i32 115, i32 116, i32 117, i32 118, i32 119, i32 120, i32 121, i32 122, i32 123, i32 124, i32 125, i32 126, i32 127>
; CHECK-NEXT:    [[TMP40:%.*]] = tail call <5 x i32> @llvm.tpc.add.mask.v5i32.v5i32(<5 x i32> <i32 1, i32 1, i32 1, i32 1, i32 1>, <5 x i32> [[TMP35]], i32 2, i8 2, i32 0, <5 x i32> [[TMP35]], i1 true, i1 false)
; CHECK-NEXT:    tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> [[TMP40]], i8 1, <64 x float> [[TMP38]], i32 0, i1 true, i1 false)
; CHECK-NEXT:    [[TMP41:%.*]] = tail call <5 x i32> @llvm.tpc.add.mask.v5i32.v5i32(<5 x i32> <i32 1, i32 1, i32 1, i32 1, i32 1>, <5 x i32> [[TMP36]], i32 2, i8 2, i32 0, <5 x i32> [[TMP36]], i1 true, i1 false)
; CHECK-NEXT:    tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> [[TMP41]], i8 1, <64 x float> [[TMP39]], i32 0, i1 true, i1 false)
; CHECK-NEXT:    [[TMP42:%.*]] = tail call <5 x i32> @llvm.tpc.add.mask.v5i32.v5i32(<5 x i32> <i32 1, i32 1, i32 1, i32 1, i32 1>, <5 x i32> [[TMP40]], i32 2, i8 2, i32 0, <5 x i32> [[TMP40]], i1 true, i1 false)
; CHECK-NEXT:    [[TMP43:%.*]] = tail call <5 x i32> @llvm.tpc.add.mask.v5i32.v5i32(<5 x i32> <i32 1, i32 1, i32 1, i32 1, i32 1>, <5 x i32> [[TMP41]], i32 2, i8 2, i32 0, <5 x i32> [[TMP41]], i1 true, i1 false)
; CHECK-NEXT:    br label [[FOR_COND_CLEANUP11]]
; CHECK:       for.cond.cleanup11:
; CHECK-NEXT:    [[IFMCOORDS_1_LCSSA]] = phi <5 x i32> [ [[TMP4]], [[FOR_BODY]] ], [ [[DOTLCSSA]], [[FOR_COND_CLEANUP11_LOOPEXIT]] ]
; CHECK-NEXT:    [[ADD15]] = add i32 [[H_062]], 1
; CHECK-NEXT:    [[EXITCOND63:%.*]] = icmp eq i32 [[ADD15]], [[VECEXT7]]
; CHECK-NEXT:    br i1 [[EXITCOND63]], label [[FOR_COND_CLEANUP_LOOPEXIT:%.*]], label [[FOR_BODY]]
; CHECK:       for.body12:
; CHECK-NEXT:    [[TMP44:%.*]] = phi <128 x half> [ [[TMP49]], [[FOR_BODY12]] ], [ [[TMP8]], [[FOR_BODY12_PREHEADER]] ]
; CHECK-NEXT:    [[TMP45:%.*]] = phi <128 x half> [ [[TMP56]], [[FOR_BODY12]] ], [ [[TMP10]], [[FOR_BODY12_PREHEADER]] ]
; CHECK-NEXT:    [[TMP46:%.*]] = phi <128 x half> [ [[TMP63]], [[FOR_BODY12]] ], [ [[TMP12]], [[FOR_BODY12_PREHEADER]] ]
; CHECK-NEXT:    [[TMP47:%.*]] = phi <128 x half> [ [[TMP70]], [[FOR_BODY12]] ], [ [[TMP14]], [[FOR_BODY12_PREHEADER]] ]
; CHECK-NEXT:    [[TMP48:%.*]] = phi <5 x i32> [ [[TMP4]], [[FOR_BODY12_PREHEADER]] ], [ [[TMP74]], [[FOR_BODY12]] ]
; CHECK-NEXT:    [[W_059:%.*]] = phi i32 [ [[ADD13_3:%.*]], [[FOR_BODY12]] ], [ [[TMP16]], [[FOR_BODY12_PREHEADER]] ]
; CHECK-NEXT:    [[IFMCOORDS_158:%.*]] = phi <5 x i32> [ [[TMP75]], [[FOR_BODY12]] ], [ [[TMP15]], [[FOR_BODY12_PREHEADER]] ]
; CHECK-NEXT:    [[OFMCOORDS1_057:%.*]] = phi <5 x i32> [ [[TMP76]], [[FOR_BODY12]] ], [ [[TMP5]], [[FOR_BODY12_PREHEADER]] ]
; CHECK-NEXT:    [[TMP49]] = tail call <128 x half> @llvm.tpc.ld.tnsr.v128f16.i1(<5 x i32> [[IFMCOORDS_158]], i8 0, i32 16, <128 x half> undef, i1 true, i1 false)
; CHECK-NEXT:    [[TMP50:%.*]] = tail call <128 x float> @llvm.tpc.convert.v128f32.v128f16.i1(<128 x half> [[TMP44]], i8 11, i32 0, <128 x float> undef, i1 true, i1 false)
; CHECK-NEXT:    [[TMP51:%.*]] = shufflevector <128 x float> [[TMP50]], <128 x float> undef, <64 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
; CHECK-NEXT:    [[TMP52:%.*]] = shufflevector <128 x float> [[TMP50]], <128 x float> undef, <64 x i32> <i32 64, i32 65, i32 66, i32 67, i32 68, i32 69, i32 70, i32 71, i32 72, i32 73, i32 74, i32 75, i32 76, i32 77, i32 78, i32 79, i32 80, i32 81, i32 82, i32 83, i32 84, i32 85, i32 86, i32 87, i32 88, i32 89, i32 90, i32 91, i32 92, i32 93, i32 94, i32 95, i32 96, i32 97, i32 98, i32 99, i32 100, i32 101, i32 102, i32 103, i32 104, i32 105, i32 106, i32 107, i32 108, i32 109, i32 110, i32 111, i32 112, i32 113, i32 114, i32 115, i32 116, i32 117, i32 118, i32 119, i32 120, i32 121, i32 122, i32 123, i32 124, i32 125, i32 126, i32 127>
; CHECK-NEXT:    tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> [[TMP48]], i8 1, <64 x float> [[TMP51]], i32 0, i1 true, i1 false)
; CHECK-NEXT:    [[TMP53:%.*]] = tail call <5 x i32> @llvm.tpc.add.mask.v5i32.v5i32(<5 x i32> <i32 1, i32 1, i32 1, i32 1, i32 1>, <5 x i32> [[TMP48]], i32 2, i8 2, i32 0, <5 x i32> [[TMP48]], i1 true, i1 false)
; CHECK-NEXT:    [[TMP54:%.*]] = tail call <5 x i32> @llvm.tpc.add.mask.v5i32.v5i32(<5 x i32> <i32 1, i32 1, i32 1, i32 1, i32 1>, <5 x i32> [[IFMCOORDS_158]], i32 2, i8 2, i32 0, <5 x i32> [[IFMCOORDS_158]], i1 true, i1 false)
; CHECK-NEXT:    tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> [[OFMCOORDS1_057]], i8 1, <64 x float> [[TMP52]], i32 0, i1 true, i1 false)
; CHECK-NEXT:    [[TMP55:%.*]] = tail call <5 x i32> @llvm.tpc.add.mask.v5i32.v5i32(<5 x i32> <i32 1, i32 1, i32 1, i32 1, i32 1>, <5 x i32> [[OFMCOORDS1_057]], i32 2, i8 2, i32 0, <5 x i32> [[OFMCOORDS1_057]], i1 true, i1 false)
; CHECK-NEXT:    [[TMP56]] = tail call <128 x half> @llvm.tpc.ld.tnsr.v128f16.i1(<5 x i32> [[TMP54]], i8 0, i32 16, <128 x half> undef, i1 true, i1 false)
; CHECK-NEXT:    [[TMP57:%.*]] = tail call <128 x float> @llvm.tpc.convert.v128f32.v128f16.i1(<128 x half> [[TMP45]], i8 11, i32 0, <128 x float> undef, i1 true, i1 false)
; CHECK-NEXT:    [[TMP58:%.*]] = shufflevector <128 x float> [[TMP57]], <128 x float> undef, <64 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
; CHECK-NEXT:    [[TMP59:%.*]] = shufflevector <128 x float> [[TMP57]], <128 x float> undef, <64 x i32> <i32 64, i32 65, i32 66, i32 67, i32 68, i32 69, i32 70, i32 71, i32 72, i32 73, i32 74, i32 75, i32 76, i32 77, i32 78, i32 79, i32 80, i32 81, i32 82, i32 83, i32 84, i32 85, i32 86, i32 87, i32 88, i32 89, i32 90, i32 91, i32 92, i32 93, i32 94, i32 95, i32 96, i32 97, i32 98, i32 99, i32 100, i32 101, i32 102, i32 103, i32 104, i32 105, i32 106, i32 107, i32 108, i32 109, i32 110, i32 111, i32 112, i32 113, i32 114, i32 115, i32 116, i32 117, i32 118, i32 119, i32 120, i32 121, i32 122, i32 123, i32 124, i32 125, i32 126, i32 127>
; CHECK-NEXT:    tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> [[TMP53]], i8 1, <64 x float> [[TMP58]], i32 0, i1 true, i1 false)
; CHECK-NEXT:    [[TMP60:%.*]] = tail call <5 x i32> @llvm.tpc.add.mask.v5i32.v5i32(<5 x i32> <i32 1, i32 1, i32 1, i32 1, i32 1>, <5 x i32> [[TMP53]], i32 2, i8 2, i32 0, <5 x i32> [[TMP53]], i1 true, i1 false)
; CHECK-NEXT:    [[TMP61:%.*]] = tail call <5 x i32> @llvm.tpc.add.mask.v5i32.v5i32(<5 x i32> <i32 1, i32 1, i32 1, i32 1, i32 1>, <5 x i32> [[TMP54]], i32 2, i8 2, i32 0, <5 x i32> [[TMP54]], i1 true, i1 false)
; CHECK-NEXT:    tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> [[TMP55]], i8 1, <64 x float> [[TMP59]], i32 0, i1 true, i1 false)
; CHECK-NEXT:    [[TMP62:%.*]] = tail call <5 x i32> @llvm.tpc.add.mask.v5i32.v5i32(<5 x i32> <i32 1, i32 1, i32 1, i32 1, i32 1>, <5 x i32> [[TMP55]], i32 2, i8 2, i32 0, <5 x i32> [[TMP55]], i1 true, i1 false)
; CHECK-NEXT:    [[TMP63]] = tail call <128 x half> @llvm.tpc.ld.tnsr.v128f16.i1(<5 x i32> [[TMP61]], i8 0, i32 16, <128 x half> undef, i1 true, i1 false)
; CHECK-NEXT:    [[TMP64:%.*]] = tail call <128 x float> @llvm.tpc.convert.v128f32.v128f16.i1(<128 x half> [[TMP46]], i8 11, i32 0, <128 x float> undef, i1 true, i1 false)
; CHECK-NEXT:    [[TMP65:%.*]] = shufflevector <128 x float> [[TMP64]], <128 x float> undef, <64 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
; CHECK-NEXT:    [[TMP66:%.*]] = shufflevector <128 x float> [[TMP64]], <128 x float> undef, <64 x i32> <i32 64, i32 65, i32 66, i32 67, i32 68, i32 69, i32 70, i32 71, i32 72, i32 73, i32 74, i32 75, i32 76, i32 77, i32 78, i32 79, i32 80, i32 81, i32 82, i32 83, i32 84, i32 85, i32 86, i32 87, i32 88, i32 89, i32 90, i32 91, i32 92, i32 93, i32 94, i32 95, i32 96, i32 97, i32 98, i32 99, i32 100, i32 101, i32 102, i32 103, i32 104, i32 105, i32 106, i32 107, i32 108, i32 109, i32 110, i32 111, i32 112, i32 113, i32 114, i32 115, i32 116, i32 117, i32 118, i32 119, i32 120, i32 121, i32 122, i32 123, i32 124, i32 125, i32 126, i32 127>
; CHECK-NEXT:    tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> [[TMP60]], i8 1, <64 x float> [[TMP65]], i32 0, i1 true, i1 false)
; CHECK-NEXT:    [[TMP67:%.*]] = tail call <5 x i32> @llvm.tpc.add.mask.v5i32.v5i32(<5 x i32> <i32 1, i32 1, i32 1, i32 1, i32 1>, <5 x i32> [[TMP60]], i32 2, i8 2, i32 0, <5 x i32> [[TMP60]], i1 true, i1 false)
; CHECK-NEXT:    [[TMP68:%.*]] = tail call <5 x i32> @llvm.tpc.add.mask.v5i32.v5i32(<5 x i32> <i32 1, i32 1, i32 1, i32 1, i32 1>, <5 x i32> [[TMP61]], i32 2, i8 2, i32 0, <5 x i32> [[TMP61]], i1 true, i1 false)
; CHECK-NEXT:    tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> [[TMP62]], i8 1, <64 x float> [[TMP66]], i32 0, i1 true, i1 false)
; CHECK-NEXT:    [[TMP69:%.*]] = tail call <5 x i32> @llvm.tpc.add.mask.v5i32.v5i32(<5 x i32> <i32 1, i32 1, i32 1, i32 1, i32 1>, <5 x i32> [[TMP62]], i32 2, i8 2, i32 0, <5 x i32> [[TMP62]], i1 true, i1 false)
; CHECK-NEXT:    [[TMP70]] = tail call <128 x half> @llvm.tpc.ld.tnsr.v128f16.i1(<5 x i32> [[TMP68]], i8 0, i32 16, <128 x half> undef, i1 true, i1 false)
; CHECK-NEXT:    [[TMP71:%.*]] = tail call <128 x float> @llvm.tpc.convert.v128f32.v128f16.i1(<128 x half> [[TMP47]], i8 11, i32 0, <128 x float> undef, i1 true, i1 false)
; CHECK-NEXT:    [[TMP72:%.*]] = shufflevector <128 x float> [[TMP71]], <128 x float> undef, <64 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
; CHECK-NEXT:    [[TMP73:%.*]] = shufflevector <128 x float> [[TMP71]], <128 x float> undef, <64 x i32> <i32 64, i32 65, i32 66, i32 67, i32 68, i32 69, i32 70, i32 71, i32 72, i32 73, i32 74, i32 75, i32 76, i32 77, i32 78, i32 79, i32 80, i32 81, i32 82, i32 83, i32 84, i32 85, i32 86, i32 87, i32 88, i32 89, i32 90, i32 91, i32 92, i32 93, i32 94, i32 95, i32 96, i32 97, i32 98, i32 99, i32 100, i32 101, i32 102, i32 103, i32 104, i32 105, i32 106, i32 107, i32 108, i32 109, i32 110, i32 111, i32 112, i32 113, i32 114, i32 115, i32 116, i32 117, i32 118, i32 119, i32 120, i32 121, i32 122, i32 123, i32 124, i32 125, i32 126, i32 127>
; CHECK-NEXT:    tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> [[TMP67]], i8 1, <64 x float> [[TMP72]], i32 0, i1 true, i1 false)
; CHECK-NEXT:    [[TMP74]] = tail call <5 x i32> @llvm.tpc.add.mask.v5i32.v5i32(<5 x i32> <i32 1, i32 1, i32 1, i32 1, i32 1>, <5 x i32> [[TMP67]], i32 2, i8 2, i32 0, <5 x i32> [[TMP67]], i1 true, i1 false)
; CHECK-NEXT:    [[TMP75]] = tail call <5 x i32> @llvm.tpc.add.mask.v5i32.v5i32(<5 x i32> <i32 1, i32 1, i32 1, i32 1, i32 1>, <5 x i32> [[TMP68]], i32 2, i8 2, i32 0, <5 x i32> [[TMP68]], i1 true, i1 false)
; CHECK-NEXT:    tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> [[TMP69]], i8 1, <64 x float> [[TMP73]], i32 0, i1 true, i1 false)
; CHECK-NEXT:    [[TMP76]] = tail call <5 x i32> @llvm.tpc.add.mask.v5i32.v5i32(<5 x i32> <i32 1, i32 1, i32 1, i32 1, i32 1>, <5 x i32> [[TMP69]], i32 2, i8 2, i32 0, <5 x i32> [[TMP69]], i1 true, i1 false)
; CHECK-NEXT:    [[ADD13_3]] = add i32 [[W_059]], 4
; CHECK-NEXT:    [[EXITCOND_3:%.*]] = icmp eq i32 [[ADD13_3]], [[MUL4]]
; CHECK-NEXT:    br i1 [[EXITCOND_3]], label [[FOR_COND_CLEANUP11_LOOPEXIT]], label [[FOR_BODY12]], !llvm.loop !3
;
entry:
  %0 = tail call i32 @llvm.tpc.ld.l.i32(i32 3240, i32 1, i32 undef, i1 true, i1 false)
  tail call void @llvm.tpc.st.l.i32(i32 3240, i32 %roundingMode, i32 1, i1 true, i1 false)
  %1 = tail call <5 x i32> @llvm.tpc.get.index.space.offset()
  %2 = tail call <5 x i32> @llvm.tpc.get.index.space.size()
  %add = add <5 x i32> %2, %1
  %vecext = extractelement <5 x i32> %1, i32 1
  %mul1 = shl nsw i32 %vecext, 2
  %vecext2 = extractelement <5 x i32> %add, i32 1
  %mul4 = shl i32 %vecext2, 2
  %vecext5 = extractelement <5 x i32> %1, i32 2
  %vecext7 = extractelement <5 x i32> %add, i32 2
  %cmp60 = icmp slt i32 %vecext5, %vecext7
  br i1 %cmp60, label %for.body.lr.ph, label %for.cond.cleanup

for.body.lr.ph:                                   ; preds = %entry
  %cmp1056 = icmp slt i32 %mul1, %mul4
  br label %for.body

for.cond.cleanup.loopexit:                        ; preds = %for.cond.cleanup11
  br label %for.cond.cleanup

for.cond.cleanup:                                 ; preds = %for.cond.cleanup.loopexit, %entry
  tail call void @llvm.tpc.st.l.i32(i32 3240, i32 %0, i32 1, i1 true, i1 false)
  ret void

for.body:                                         ; preds = %for.cond.cleanup11, %for.body.lr.ph
  %h.062 = phi i32 [ %vecext5, %for.body.lr.ph ], [ %add15, %for.cond.cleanup11 ]
  %ifmCoords.061 = phi <5 x i32> [ undef, %for.body.lr.ph ], [ %ifmCoords.1.lcssa, %for.cond.cleanup11 ]
  %3 = tail call <5 x i32> @llvm.tpc.set.indx(<5 x i32> %ifmCoords.061, i32 4, i32 %h.062, i32 0, i1 true, i1 false)
  %4 = tail call <5 x i32> @llvm.tpc.set.indx(<5 x i32> %3, i32 2, i32 %mul1, i32 0, i1 true, i1 false)
  %5 = tail call <5 x i32> @llvm.tpc.add.mask.v5i32.v5i32(<5 x i32> <i32 64, i32 64, i32 64, i32 64, i32 64>, <5 x i32> %4, i32 1, i8 2, i32 0, <5 x i32> %4, i1 true, i1 false)
  br i1 %cmp1056, label %for.body12.preheader, label %for.cond.cleanup11

for.body12.preheader:                             ; preds = %for.body
  br label %for.body12

for.cond.cleanup11.loopexit:                      ; preds = %for.body12
  %.lcssa = phi <5 x i32> [ %28, %for.body12 ]
  br label %for.cond.cleanup11

for.cond.cleanup11:                               ; preds = %for.cond.cleanup11.loopexit, %for.body
  %ifmCoords.1.lcssa = phi <5 x i32> [ %4, %for.body ], [ %.lcssa, %for.cond.cleanup11.loopexit ]
  %add15 = add i32 %h.062, 1
  %exitcond63 = icmp eq i32 %add15, %vecext7
  br i1 %exitcond63, label %for.cond.cleanup.loopexit, label %for.body

for.body12:                                       ; preds = %for.body12.preheader, %for.body12
  %w.059 = phi i32 [ %add13.3, %for.body12 ], [ %mul1, %for.body12.preheader ]
  %ifmCoords.158 = phi <5 x i32> [ %28, %for.body12 ], [ %4, %for.body12.preheader ]
  %ofmCoords1.057 = phi <5 x i32> [ %29, %for.body12 ], [ %5, %for.body12.preheader ]
  %6 = tail call <128 x half> @llvm.tpc.ld.tnsr.v128f16.i1(<5 x i32> %ifmCoords.158, i8 0, i32 16, <128 x half> undef, i1 true, i1 false)
  %7 = tail call <128 x float> @llvm.tpc.convert.v128f32.v128f16.i1(<128 x half> %6, i8 11, i32 0, <128 x float> undef, i1 true, i1 false)
  %8 = shufflevector <128 x float> %7, <128 x float> undef, <64 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
  %9 = shufflevector <128 x float> %7, <128 x float> undef, <64 x i32> <i32 64, i32 65, i32 66, i32 67, i32 68, i32 69, i32 70, i32 71, i32 72, i32 73, i32 74, i32 75, i32 76, i32 77, i32 78, i32 79, i32 80, i32 81, i32 82, i32 83, i32 84, i32 85, i32 86, i32 87, i32 88, i32 89, i32 90, i32 91, i32 92, i32 93, i32 94, i32 95, i32 96, i32 97, i32 98, i32 99, i32 100, i32 101, i32 102, i32 103, i32 104, i32 105, i32 106, i32 107, i32 108, i32 109, i32 110, i32 111, i32 112, i32 113, i32 114, i32 115, i32 116, i32 117, i32 118, i32 119, i32 120, i32 121, i32 122, i32 123, i32 124, i32 125, i32 126, i32 127>
  tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> %ifmCoords.158, i8 1, <64 x float> %8, i32 0, i1 true, i1 false)
  %10 = tail call <5 x i32> @llvm.tpc.add.mask.v5i32.v5i32(<5 x i32> <i32 1, i32 1, i32 1, i32 1, i32 1>, <5 x i32> %ifmCoords.158, i32 2, i8 2, i32 0, <5 x i32> %ifmCoords.158, i1 true, i1 false)
  tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> %ofmCoords1.057, i8 1, <64 x float> %9, i32 0, i1 true, i1 false)
  %11 = tail call <5 x i32> @llvm.tpc.add.mask.v5i32.v5i32(<5 x i32> <i32 1, i32 1, i32 1, i32 1, i32 1>, <5 x i32> %ofmCoords1.057, i32 2, i8 2, i32 0, <5 x i32> %ofmCoords1.057, i1 true, i1 false)
  %12 = tail call <128 x half> @llvm.tpc.ld.tnsr.v128f16.i1(<5 x i32> %10, i8 0, i32 16, <128 x half> undef, i1 true, i1 false)
  %13 = tail call <128 x float> @llvm.tpc.convert.v128f32.v128f16.i1(<128 x half> %12, i8 11, i32 0, <128 x float> undef, i1 true, i1 false)
  %14 = shufflevector <128 x float> %13, <128 x float> undef, <64 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
  %15 = shufflevector <128 x float> %13, <128 x float> undef, <64 x i32> <i32 64, i32 65, i32 66, i32 67, i32 68, i32 69, i32 70, i32 71, i32 72, i32 73, i32 74, i32 75, i32 76, i32 77, i32 78, i32 79, i32 80, i32 81, i32 82, i32 83, i32 84, i32 85, i32 86, i32 87, i32 88, i32 89, i32 90, i32 91, i32 92, i32 93, i32 94, i32 95, i32 96, i32 97, i32 98, i32 99, i32 100, i32 101, i32 102, i32 103, i32 104, i32 105, i32 106, i32 107, i32 108, i32 109, i32 110, i32 111, i32 112, i32 113, i32 114, i32 115, i32 116, i32 117, i32 118, i32 119, i32 120, i32 121, i32 122, i32 123, i32 124, i32 125, i32 126, i32 127>
  tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> %10, i8 1, <64 x float> %14, i32 0, i1 true, i1 false)
  %16 = tail call <5 x i32> @llvm.tpc.add.mask.v5i32.v5i32(<5 x i32> <i32 1, i32 1, i32 1, i32 1, i32 1>, <5 x i32> %10, i32 2, i8 2, i32 0, <5 x i32> %10, i1 true, i1 false)
  tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> %11, i8 1, <64 x float> %15, i32 0, i1 true, i1 false)
  %17 = tail call <5 x i32> @llvm.tpc.add.mask.v5i32.v5i32(<5 x i32> <i32 1, i32 1, i32 1, i32 1, i32 1>, <5 x i32> %11, i32 2, i8 2, i32 0, <5 x i32> %11, i1 true, i1 false)
  %18 = tail call <128 x half> @llvm.tpc.ld.tnsr.v128f16.i1(<5 x i32> %16, i8 0, i32 16, <128 x half> undef, i1 true, i1 false)
  %19 = tail call <128 x float> @llvm.tpc.convert.v128f32.v128f16.i1(<128 x half> %18, i8 11, i32 0, <128 x float> undef, i1 true, i1 false)
  %20 = shufflevector <128 x float> %19, <128 x float> undef, <64 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
  %21 = shufflevector <128 x float> %19, <128 x float> undef, <64 x i32> <i32 64, i32 65, i32 66, i32 67, i32 68, i32 69, i32 70, i32 71, i32 72, i32 73, i32 74, i32 75, i32 76, i32 77, i32 78, i32 79, i32 80, i32 81, i32 82, i32 83, i32 84, i32 85, i32 86, i32 87, i32 88, i32 89, i32 90, i32 91, i32 92, i32 93, i32 94, i32 95, i32 96, i32 97, i32 98, i32 99, i32 100, i32 101, i32 102, i32 103, i32 104, i32 105, i32 106, i32 107, i32 108, i32 109, i32 110, i32 111, i32 112, i32 113, i32 114, i32 115, i32 116, i32 117, i32 118, i32 119, i32 120, i32 121, i32 122, i32 123, i32 124, i32 125, i32 126, i32 127>
  tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> %16, i8 1, <64 x float> %20, i32 0, i1 true, i1 false)
  %22 = tail call <5 x i32> @llvm.tpc.add.mask.v5i32.v5i32(<5 x i32> <i32 1, i32 1, i32 1, i32 1, i32 1>, <5 x i32> %16, i32 2, i8 2, i32 0, <5 x i32> %16, i1 true, i1 false)
  tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> %17, i8 1, <64 x float> %21, i32 0, i1 true, i1 false)
  %23 = tail call <5 x i32> @llvm.tpc.add.mask.v5i32.v5i32(<5 x i32> <i32 1, i32 1, i32 1, i32 1, i32 1>, <5 x i32> %17, i32 2, i8 2, i32 0, <5 x i32> %17, i1 true, i1 false)
  %24 = tail call <128 x half> @llvm.tpc.ld.tnsr.v128f16.i1(<5 x i32> %22, i8 0, i32 16, <128 x half> undef, i1 true, i1 false)
  %25 = tail call <128 x float> @llvm.tpc.convert.v128f32.v128f16.i1(<128 x half> %24, i8 11, i32 0, <128 x float> undef, i1 true, i1 false)
  %26 = shufflevector <128 x float> %25, <128 x float> undef, <64 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
  %27 = shufflevector <128 x float> %25, <128 x float> undef, <64 x i32> <i32 64, i32 65, i32 66, i32 67, i32 68, i32 69, i32 70, i32 71, i32 72, i32 73, i32 74, i32 75, i32 76, i32 77, i32 78, i32 79, i32 80, i32 81, i32 82, i32 83, i32 84, i32 85, i32 86, i32 87, i32 88, i32 89, i32 90, i32 91, i32 92, i32 93, i32 94, i32 95, i32 96, i32 97, i32 98, i32 99, i32 100, i32 101, i32 102, i32 103, i32 104, i32 105, i32 106, i32 107, i32 108, i32 109, i32 110, i32 111, i32 112, i32 113, i32 114, i32 115, i32 116, i32 117, i32 118, i32 119, i32 120, i32 121, i32 122, i32 123, i32 124, i32 125, i32 126, i32 127>
  tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> %22, i8 1, <64 x float> %26, i32 0, i1 true, i1 false)
  %28 = tail call <5 x i32> @llvm.tpc.add.mask.v5i32.v5i32(<5 x i32> <i32 1, i32 1, i32 1, i32 1, i32 1>, <5 x i32> %22, i32 2, i8 2, i32 0, <5 x i32> %22, i1 true, i1 false)
  tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> %23, i8 1, <64 x float> %27, i32 0, i1 true, i1 false)
  %29 = tail call <5 x i32> @llvm.tpc.add.mask.v5i32.v5i32(<5 x i32> <i32 1, i32 1, i32 1, i32 1, i32 1>, <5 x i32> %23, i32 2, i8 2, i32 0, <5 x i32> %23, i1 true, i1 false)
  %add13.3 = add i32 %w.059, 4
  %exitcond.3 = icmp eq i32 %add13.3, %mul4
  br i1 %exitcond.3, label %for.cond.cleanup11.loopexit, label %for.body12, !llvm.loop !3
}

; Function Attrs: nounwind readonly
declare i32 @llvm.tpc.ld.l.i32(i32, i32, i32, i1, i1) #1

; Function Attrs: nounwind writeonly
declare void @llvm.tpc.st.l.i32(i32, i32, i32, i1, i1) #2

; Function Attrs: nounwind readnone
declare <5 x i32> @llvm.tpc.get.index.space.offset() #3

; Function Attrs: nounwind readnone
declare <5 x i32> @llvm.tpc.get.index.space.size() #3

; Function Attrs: nounwind readnone
declare <5 x i32> @llvm.tpc.set.indx(<5 x i32>, i32, i32, i32, i1, i1) #3

; Function Attrs: nounwind readnone
declare <5 x i32> @llvm.tpc.add.mask.v5i32.v5i32(<5 x i32>, <5 x i32>, i32, i8, i32, <5 x i32>, i1, i1) #3

; Function Attrs: nounwind readnone
declare <128 x half> @llvm.tpc.ld.tnsr.v128f16.i1(<5 x i32>, i8, i32, <128 x half>, i1, i1) #3

; Function Attrs: nounwind readnone
declare <128 x float> @llvm.tpc.convert.v128f32.v128f16.i1(<128 x half>, i8, i32, <128 x float>, i1, i1) #3

; Function Attrs: nounwind writeonly
declare void @llvm.tpc.st.tnsr.v64f32(<5 x i32>, i8, <64 x float>, i32, i1, i1) #2

attributes #0 = { nounwind "correctly-rounded-divide-sqrt-fp-math"="false" "disable-tail-calls"="false" "frame-pointer"="all" "less-precise-fpmad"="false" "min-legal-vector-width"="0" "no-infs-fp-math"="false" "no-jump-tables"="false" "no-nans-fp-math"="false" "no-signed-zeros-fp-math"="false" "no-trapping-math"="false" "stack-protector-buffer-size"="8" "target-cpu"="goya2" "target-features"="+goya2" "unsafe-fp-math"="false" "use-soft-float"="false" }
attributes #1 = { nounwind readonly }
attributes #2 = { nounwind writeonly }
attributes #3 = { nounwind readnone }

!llvm.module.flags = !{!0}
!llvm.ident = !{!1}
!llvm.tpc.scalar_data = !{!2}
!llvm.tpc.vector_data = !{!2}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{!"clang version 10.0.1 (ssh://gerrit:29418/tpc_llvm10 4111c7f125204e995146f7741cc2c3989cfb74d0)"}
!2 = !{i32 0}
!3 = distinct !{!3, !4}
!4 = !{!"llvm.loop.unroll.disable"}
