; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -march=tpc -mcpu=goya2 -coord-simplify -coord-update-simplify=true -S | FileCheck %s

target datalayout = "e-p0:32:32:32-p1:32:32:32-p2:32:32:32-p3:64:64:64-i32:32:32-n8:16:32-f16:16:16-f32:32:32-v160:32:32-v256:2048:2048-v2048:2048:2048-v4096:2048:2048-v8192:2048:2048"
target triple = "tpc"

; Function Attrs: nounwind writeonly
define dso_local void @main() local_unnamed_addr #0 {
; CHECK-LABEL: @main(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = tail call <5 x i32> @llvm.tpc.get.index.space.offset()
; CHECK-NEXT:    [[TMP1:%.*]] = tail call <5 x i32> @llvm.tpc.get.index.space.size()
; CHECK-NEXT:    [[ADD:%.*]] = add <5 x i32> [[TMP1]], [[TMP0]]
; CHECK-NEXT:    [[VECEXT:%.*]] = extractelement <5 x i32> [[TMP0]], i32 3
; CHECK-NEXT:    [[MUL:%.*]] = shl nsw i32 [[VECEXT]], 2
; CHECK-NEXT:    [[VECEXT1:%.*]] = extractelement <5 x i32> [[ADD]], i32 3
; CHECK-NEXT:    [[MUL2:%.*]] = shl i32 [[VECEXT1]], 2
; CHECK-NEXT:    [[VECEXT3:%.*]] = extractelement <5 x i32> [[TMP0]], i32 0
; CHECK-NEXT:    [[VECEXT4:%.*]] = extractelement <5 x i32> [[ADD]], i32 0
; CHECK-NEXT:    [[CMP53:%.*]] = icmp slt i32 [[VECEXT3]], [[VECEXT4]]
; CHECK-NEXT:    br i1 [[CMP53]], label [[FOR_BODY_LR_PH:%.*]], label [[FOR_COND_CLEANUP:%.*]]
; CHECK:       for.body.lr.ph:
; CHECK-NEXT:    [[CMP747:%.*]] = icmp slt i32 [[MUL]], [[MUL2]]
; CHECK-NEXT:    br label [[FOR_BODY:%.*]]
; CHECK:       for.cond.cleanup.loopexit:
; CHECK-NEXT:    br label [[FOR_COND_CLEANUP]]
; CHECK:       for.cond.cleanup:
; CHECK-NEXT:    ret void
; CHECK:       for.body:
; CHECK-NEXT:    [[H_057:%.*]] = phi i32 [ [[VECEXT3]], [[FOR_BODY_LR_PH]] ], [ [[ADD14:%.*]], [[FOR_COND_CLEANUP8:%.*]] ]
; CHECK-NEXT:    [[OUT_056:%.*]] = phi <64 x float> [ undef, [[FOR_BODY_LR_PH]] ], [ [[OUT_1_LCSSA:%.*]], [[FOR_COND_CLEANUP8]] ]
; CHECK-NEXT:    [[IFMCOORDS_055:%.*]] = phi <5 x i32> [ zeroinitializer, [[FOR_BODY_LR_PH]] ], [ [[IFMCOORDS_1_LCSSA:%.*]], [[FOR_COND_CLEANUP8]] ]
; CHECK-NEXT:    [[OFMCOORDS_054:%.*]] = phi <5 x i32> [ zeroinitializer, [[FOR_BODY_LR_PH]] ], [ [[OFMCOORDS_1_LCSSA:%.*]], [[FOR_COND_CLEANUP8]] ]
; CHECK-NEXT:    [[VECINS:%.*]] = insertelement <5 x i32> [[IFMCOORDS_055]], i32 [[H_057]], i32 0
; CHECK-NEXT:    [[VECINS5:%.*]] = insertelement <5 x i32> [[OFMCOORDS_054]], i32 [[H_057]], i32 0
; CHECK-NEXT:    br i1 [[CMP747]], label [[FOR_BODY9_PREHEADER:%.*]], label [[FOR_COND_CLEANUP8]]
; CHECK:       for.body9.preheader:
; CHECK-NEXT:    [[TMP2:%.*]] = insertelement <5 x i32> [[VECINS5]], i32 [[MUL]], i32 3
; CHECK-NEXT:    [[TMP3:%.*]] = insertelement <5 x i32> [[VECINS]], i32 [[MUL]], i32 3
; CHECK-NEXT:    br label [[FOR_BODY9:%.*]]
; CHECK:       for.cond.cleanup8.loopexit:
; CHECK-NEXT:    [[VECINS10_LCSSA:%.*]] = phi <5 x i32> [ [[TMP9:%.*]], [[FOR_BODY9]] ]
; CHECK-NEXT:    [[VECINS11_LCSSA:%.*]] = phi <5 x i32> [ [[TMP6:%.*]], [[FOR_BODY9]] ]
; CHECK-NEXT:    [[DOTLCSSA:%.*]] = phi <64 x float> [ [[TMP8:%.*]], [[FOR_BODY9]] ]
; CHECK-NEXT:    [[TMP4:%.*]] = call <5 x i32> @llvm.tpc.add.mask.v5i32.i32(<5 x i32> [[VECINS11_LCSSA]], i32 -1, i32 8, i8 2, i32 0, <5 x i32> [[VECINS11_LCSSA]], i1 true, i1 false)
; CHECK-NEXT:    [[TMP5:%.*]] = call <5 x i32> @llvm.tpc.add.mask.v5i32.i32(<5 x i32> [[VECINS10_LCSSA]], i32 -1, i32 8, i8 2, i32 0, <5 x i32> [[VECINS10_LCSSA]], i1 true, i1 false)
; CHECK-NEXT:    br label [[FOR_COND_CLEANUP8]]
; CHECK:       for.cond.cleanup8:
; CHECK-NEXT:    [[OFMCOORDS_1_LCSSA]] = phi <5 x i32> [ [[VECINS5]], [[FOR_BODY]] ], [ [[TMP4]], [[FOR_COND_CLEANUP8_LOOPEXIT:%.*]] ]
; CHECK-NEXT:    [[IFMCOORDS_1_LCSSA]] = phi <5 x i32> [ [[VECINS]], [[FOR_BODY]] ], [ [[TMP5]], [[FOR_COND_CLEANUP8_LOOPEXIT]] ]
; CHECK-NEXT:    [[OUT_1_LCSSA]] = phi <64 x float> [ [[OUT_056]], [[FOR_BODY]] ], [ [[DOTLCSSA]], [[FOR_COND_CLEANUP8_LOOPEXIT]] ]
; CHECK-NEXT:    tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> [[OFMCOORDS_1_LCSSA]], i8 1, <64 x float> [[OUT_1_LCSSA]], i32 0, i1 true, i1 false)
; CHECK-NEXT:    [[ADD14]] = add i32 [[H_057]], 1
; CHECK-NEXT:    [[EXITCOND58:%.*]] = icmp eq i32 [[ADD14]], [[VECEXT4]]
; CHECK-NEXT:    br i1 [[EXITCOND58]], label [[FOR_COND_CLEANUP_LOOPEXIT:%.*]], label [[FOR_BODY]], !llvm.loop !3
; CHECK:       for.body9:
; CHECK-NEXT:    [[W_050:%.*]] = phi i32 [ [[ADD12:%.*]], [[FOR_BODY9]] ], [ [[MUL]], [[FOR_BODY9_PREHEADER]] ]
; CHECK-NEXT:    [[IFMCOORDS_149:%.*]] = phi <5 x i32> [ [[TMP3]], [[FOR_BODY9_PREHEADER]] ], [ [[TMP9]], [[FOR_BODY9]] ]
; CHECK-NEXT:    [[OFMCOORDS_148:%.*]] = phi <5 x i32> [ [[TMP2]], [[FOR_BODY9_PREHEADER]] ], [ [[TMP6]], [[FOR_BODY9]] ]
; CHECK-NEXT:    [[TMP6]] = call <5 x i32> @llvm.tpc.add.mask.v5i32.i32(<5 x i32> [[OFMCOORDS_148]], i32 1, i32 8, i8 2, i32 0, <5 x i32> [[OFMCOORDS_148]], i1 true, i1 false)
; CHECK-NEXT:    [[TMP7:%.*]] = tail call <64 x float> @llvm.tpc.ld.tnsr.v64f32.i1(<5 x i32> [[IFMCOORDS_149]], i8 0, i32 0, <64 x float> undef, i1 true, i1 false)
; CHECK-NEXT:    [[TMP8]] = tail call <64 x float> @llvm.fabs.v64f32(<64 x float> [[TMP7]])
; CHECK-NEXT:    tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> [[IFMCOORDS_149]], i8 1, <64 x float> [[TMP8]], i32 0, i1 true, i1 false)
; CHECK-NEXT:    [[TMP9]] = call <5 x i32> @llvm.tpc.add.mask.v5i32.i32(<5 x i32> [[IFMCOORDS_149]], i32 1, i32 8, i8 2, i32 0, <5 x i32> [[IFMCOORDS_149]], i1 true, i1 false)
; CHECK-NEXT:    [[ADD12]] = add i32 [[W_050]], 1
; CHECK-NEXT:    [[EXITCOND:%.*]] = icmp eq i32 [[ADD12]], [[MUL2]]
; CHECK-NEXT:    br i1 [[EXITCOND]], label [[FOR_COND_CLEANUP8_LOOPEXIT]], label [[FOR_BODY9]], !llvm.loop !5
;
entry:
  %0 = tail call <5 x i32> @llvm.tpc.get.index.space.offset()
  %1 = tail call <5 x i32> @llvm.tpc.get.index.space.size()
  %add = add <5 x i32> %1, %0
  %vecext = extractelement <5 x i32> %0, i32 3
  %mul = shl nsw i32 %vecext, 2
  %vecext1 = extractelement <5 x i32> %add, i32 3
  %mul2 = shl i32 %vecext1, 2
  %vecext3 = extractelement <5 x i32> %0, i32 0
  %vecext4 = extractelement <5 x i32> %add, i32 0
  %cmp53 = icmp slt i32 %vecext3, %vecext4
  br i1 %cmp53, label %for.body.lr.ph, label %for.cond.cleanup

for.body.lr.ph:                                   ; preds = %entry
  %cmp747 = icmp slt i32 %mul, %mul2
  br label %for.body

for.cond.cleanup.loopexit:                        ; preds = %for.cond.cleanup8
  br label %for.cond.cleanup

for.cond.cleanup:                                 ; preds = %for.cond.cleanup.loopexit, %entry
  ret void

for.body:                                         ; preds = %for.cond.cleanup8, %for.body.lr.ph
  %h.057 = phi i32 [ %vecext3, %for.body.lr.ph ], [ %add14, %for.cond.cleanup8 ]
  %out.056 = phi <64 x float> [ undef, %for.body.lr.ph ], [ %out.1.lcssa, %for.cond.cleanup8 ]
  %ifmCoords.055 = phi <5 x i32> [ zeroinitializer, %for.body.lr.ph ], [ %ifmCoords.1.lcssa, %for.cond.cleanup8 ]
  %ofmCoords.054 = phi <5 x i32> [ zeroinitializer, %for.body.lr.ph ], [ %ofmCoords.1.lcssa, %for.cond.cleanup8 ]
  %vecins = insertelement <5 x i32> %ifmCoords.055, i32 %h.057, i32 0
  %vecins5 = insertelement <5 x i32> %ofmCoords.054, i32 %h.057, i32 0
  br i1 %cmp747, label %for.body9.preheader, label %for.cond.cleanup8

for.body9.preheader:                              ; preds = %for.body
  br label %for.body9

for.cond.cleanup8.loopexit:                       ; preds = %for.body9
  %vecins10.lcssa = phi <5 x i32> [ %vecins10, %for.body9 ]
  %vecins11.lcssa = phi <5 x i32> [ %vecins11, %for.body9 ]
  %.lcssa = phi <64 x float> [ %3, %for.body9 ]
  br label %for.cond.cleanup8

for.cond.cleanup8:                                ; preds = %for.cond.cleanup8.loopexit, %for.body
  %ofmCoords.1.lcssa = phi <5 x i32> [ %vecins5, %for.body ], [ %vecins11.lcssa, %for.cond.cleanup8.loopexit ]
  %ifmCoords.1.lcssa = phi <5 x i32> [ %vecins, %for.body ], [ %vecins10.lcssa, %for.cond.cleanup8.loopexit ]
  %out.1.lcssa = phi <64 x float> [ %out.056, %for.body ], [ %.lcssa, %for.cond.cleanup8.loopexit ]
  tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> %ofmCoords.1.lcssa, i8 1, <64 x float> %out.1.lcssa, i32 0, i1 true, i1 false)
  %add14 = add i32 %h.057, 1
  %exitcond58 = icmp eq i32 %add14, %vecext4
  br i1 %exitcond58, label %for.cond.cleanup.loopexit, label %for.body, !llvm.loop !3

for.body9:                                        ; preds = %for.body9.preheader, %for.body9
  %w.050 = phi i32 [ %add12, %for.body9 ], [ %mul, %for.body9.preheader ]
  %ifmCoords.149 = phi <5 x i32> [ %vecins10, %for.body9 ], [ %vecins, %for.body9.preheader ]
  %ofmCoords.148 = phi <5 x i32> [ %vecins11, %for.body9 ], [ %vecins5, %for.body9.preheader ]
  %vecins10 = insertelement <5 x i32> %ifmCoords.149, i32 %w.050, i32 3
  %vecins11 = insertelement <5 x i32> %ofmCoords.148, i32 %w.050, i32 3
  %2 = tail call <64 x float> @llvm.tpc.ld.tnsr.v64f32.i1(<5 x i32> %vecins10, i8 0, i32 0, <64 x float> undef, i1 true, i1 false)
  %3 = tail call <64 x float> @llvm.fabs.v64f32(<64 x float> %2)
  tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> %vecins10, i8 1, <64 x float> %3, i32 0, i1 true, i1 false)
  %add12 = add i32 %w.050, 1
  %exitcond = icmp eq i32 %add12, %mul2
  br i1 %exitcond, label %for.cond.cleanup8.loopexit, label %for.body9, !llvm.loop !5
}

; Function Attrs: nounwind readnone
declare <5 x i32> @llvm.tpc.get.index.space.offset() #1

; Function Attrs: nounwind readnone
declare <5 x i32> @llvm.tpc.get.index.space.size() #1

; Function Attrs: nounwind readnone
declare <64 x float> @llvm.tpc.ld.tnsr.v64f32.i1(<5 x i32>, i8, i32, <64 x float>, i1, i1) #1

; Function Attrs: nounwind writeonly
declare void @llvm.tpc.st.tnsr.v64f32(<5 x i32>, i8, <64 x float>, i32, i1, i1) #2

; Function Attrs: nounwind readnone speculatable willreturn
declare <64 x float> @llvm.fabs.v64f32(<64 x float>) #3

attributes #0 = { nounwind writeonly "correctly-rounded-divide-sqrt-fp-math"="false" "disable-tail-calls"="false" "frame-pointer"="all" "less-precise-fpmad"="false" "min-legal-vector-width"="0" "no-infs-fp-math"="false" "no-jump-tables"="false" "no-nans-fp-math"="false" "no-signed-zeros-fp-math"="false" "no-trapping-math"="false" "stack-protector-buffer-size"="8" "target-cpu"="goya2" "target-features"="+goya2" "unsafe-fp-math"="false" "use-soft-float"="false" }
attributes #1 = { nounwind readnone }
attributes #2 = { nounwind writeonly }
attributes #3 = { nounwind readnone speculatable willreturn }

!llvm.module.flags = !{!0}
!llvm.ident = !{!1}
!llvm.tpc.scalar_data = !{!2}
!llvm.tpc.vector_data = !{!2}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{!"clang version 10.0.1 (ssh://gerrit:29418/tpc_llvm10 37f6b84c5ee8bcfb48af5c8de6a680ad5a709a1d)"}
!2 = !{i32 0}
!3 = distinct !{!3, !4}
!4 = !{!"llvm.loop.taken", i1 true}
!5 = distinct !{!5, !4}
