; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -cast-swizzle-opt -S | FileCheck %s


declare i8* @malloc(i64)

declare void @free(i8*)

declare i16 @llvm.tpc.ld.g.i16(i8 addrspace(3)*, i32, i16, i1, i1)

declare i32 @llvm.tpc.ld.g.i32(i8 addrspace(3)*, i32, i32, i1, i1)

declare bfloat16 @llvm.tpc.ld.g.bf16(i8 addrspace(3)*, i32, bfloat16, i1, i1)

declare float @llvm.tpc.ld.g.f32(i8 addrspace(3)*, i32, float, i1, i1)

declare <128 x bfloat16> @llvm.tpc.ld.g.v128bf16(i8 addrspace(3)*, i32, <128 x bfloat16>, i1, i1)

declare <128 x bfloat16> @llvm.tpc.ld.tnsr.v128bf16.i1(<5 x i32>, i8, i32, <128 x bfloat16>, i1, i1)

declare void @llvm.tpc.st.tnsr.v128bf16(<5 x i32>, i8, <128 x bfloat16>, i32, i1, i1)

declare <128 x bfloat16> @llvm.tpc.tanh.v128bf16(<128 x bfloat16>)

declare <64 x float> @llvm.tpc.ld.g.v64f32(i8 addrspace(3)*, i32, <64 x float>, i1, i1)

declare <64 x float> @llvm.tpc.ld.tnsr.v64f32.i1(<5 x i32>, i8, i32, <64 x float>, i1, i1)

declare void @llvm.tpc.st.tnsr.v64f32(<5 x i32>, i8, <64 x float>, i32, i1, i1)

declare <64 x float> @llvm.tpc.tanh.v64f32(<64 x float>)

declare <128 x float> @llvm.tpc.ld.g.v128f32(i8 addrspace(3)*, i32, <128 x float>, i1, i1)

declare <128 x float> @llvm.tpc.ld.tnsr.v128f32.i1(<5 x i32>, i8, i32, <128 x float>, i1, i1)

declare void @llvm.tpc.st.tnsr.v128f32(<5 x i32>, i8, <128 x float>, i32, i1, i1)

declare <128 x float> @llvm.tpc.tanh.v128f32(<128 x float>)

declare <256 x i8> @llvm.tpc.ld.g.v256i8(i8 addrspace(3)*, i32, <256 x i8>, i1, i1)

declare <256 x i8> @llvm.tpc.ld.tnsr.v256i8.i1(<5 x i32>, i8, i32, <256 x i8>, i1, i1)

declare void @llvm.tpc.st.tnsr.v256i8(<5 x i32>, i8, <256 x i8>, i32, i1, i1)

declare <256 x i8> @llvm.tpc.tanh.v256i8(<256 x i8>)

declare <128 x i16> @llvm.tpc.ld.g.v128i16(i8 addrspace(3)*, i32, <128 x i16>, i1, i1)

declare <128 x i16> @llvm.tpc.ld.tnsr.v128i16.i1(<5 x i32>, i8, i32, <128 x i16>, i1, i1)

declare void @llvm.tpc.st.tnsr.v128i16(<5 x i32>, i8, <128 x i16>, i32, i1, i1)

declare <128 x i16> @llvm.tpc.tanh.v128i16(<128 x i16>)

declare <64 x i32> @llvm.tpc.ld.g.v64i32(i8 addrspace(3)*, i32, <64 x i32>, i1, i1)

declare <64 x i32> @llvm.tpc.ld.tnsr.v64i32.i1(<5 x i32>, i8, i32, <64 x i32>, i1, i1)

declare void @llvm.tpc.st.tnsr.v64i32(<5 x i32>, i8, <64 x i32>, i32, i1, i1)

declare <64 x i32> @llvm.tpc.tanh.v64i32(<64 x i32>)

declare <256 x i8> @llvm.tpc.read.lfsr()

declare void @llvm.tpc.write.lfsr(<256 x i8>)

declare i8 addrspace(3)* @llvm.tpc.gen.addr(<5 x i32>, i8, i32, i8 addrspace(3)*, i1, i1)

define void @main() !dbg !3 {
; CHECK-LABEL: @main(
; CHECK-NEXT:  bb:
; CHECK-NEXT:    [[I:%.*]] = alloca i32, i32 mul (i32 ptrtoint (i32* getelementptr (i32, i32* null, i32 1) to i32), i32 5), align 4
; CHECK-NEXT:    [[I1:%.*]] = insertvalue { i32*, i32*, i32, [1 x i32], [1 x i32] } undef, i32* [[I]], 0
; CHECK-NEXT:    [[I2:%.*]] = insertvalue { i32*, i32*, i32, [1 x i32], [1 x i32] } [[I1]], i32* [[I]], 1
; CHECK-NEXT:    [[I3:%.*]] = insertvalue { i32*, i32*, i32, [1 x i32], [1 x i32] } [[I2]], i32 0, 2
; CHECK-NEXT:    [[I4:%.*]] = insertvalue { i32*, i32*, i32, [1 x i32], [1 x i32] } [[I3]], i32 5, 3, 0
; CHECK-NEXT:    [[I5:%.*]] = insertvalue { i32*, i32*, i32, [1 x i32], [1 x i32] } [[I4]], i32 1, 4, 0
; CHECK-NEXT:    [[I6:%.*]] = extractvalue { i32*, i32*, i32, [1 x i32], [1 x i32] } [[I5]], 1
; CHECK-NEXT:    [[I7:%.*]] = getelementptr i32, i32* [[I6]], i32 0
; CHECK-NEXT:    [[I8:%.*]] = bitcast i32* [[I7]] to <5 x i32>*
; CHECK-NEXT:    store <5 x i32> zeroinitializer, <5 x i32>* [[I8]], align 4
; CHECK-NEXT:    [[I9:%.*]] = alloca i32, i32 mul (i32 ptrtoint (i32* getelementptr (i32, i32* null, i32 1) to i32), i32 5), align 4
; CHECK-NEXT:    [[I10:%.*]] = insertvalue { i32*, i32*, i32, [1 x i32], [1 x i32] } undef, i32* [[I9]], 0
; CHECK-NEXT:    [[I11:%.*]] = insertvalue { i32*, i32*, i32, [1 x i32], [1 x i32] } [[I10]], i32* [[I9]], 1
; CHECK-NEXT:    [[I12:%.*]] = insertvalue { i32*, i32*, i32, [1 x i32], [1 x i32] } [[I11]], i32 0, 2
; CHECK-NEXT:    [[I13:%.*]] = insertvalue { i32*, i32*, i32, [1 x i32], [1 x i32] } [[I12]], i32 5, 3, 0
; CHECK-NEXT:    [[I14:%.*]] = insertvalue { i32*, i32*, i32, [1 x i32], [1 x i32] } [[I13]], i32 1, 4, 0
; CHECK-NEXT:    [[I15:%.*]] = extractvalue { i32*, i32*, i32, [1 x i32], [1 x i32] } [[I14]], 1
; CHECK-NEXT:    [[I16:%.*]] = getelementptr i32, i32* [[I15]], i32 0
; CHECK-NEXT:    [[I17:%.*]] = bitcast i32* [[I16]] to <5 x i32>*
; CHECK-NEXT:    store <5 x i32> zeroinitializer, <5 x i32>* [[I17]], align 4
; CHECK-NEXT:    br label [[BB18:%.*]]
; CHECK:       bb18:
; CHECK-NEXT:    [[I19:%.*]] = phi i32 [ [[I57:%.*]], [[BB56:%.*]] ], [ 0, [[BB:%.*]] ]
; CHECK-NEXT:    [[I20:%.*]] = icmp slt i32 [[I19]], 2
; CHECK-NEXT:    br i1 [[I20]], label [[BB21:%.*]], label [[BB58:%.*]]
; CHECK:       bb21:
; CHECK-NEXT:    [[I22:%.*]] = extractvalue { i32*, i32*, i32, [1 x i32], [1 x i32] } [[I5]], 1
; CHECK-NEXT:    [[I23:%.*]] = getelementptr i32, i32* [[I22]], i32 2
; CHECK-NEXT:    store i32 [[I19]], i32* [[I23]], align 4
; CHECK-NEXT:    [[I24:%.*]] = extractvalue { i32*, i32*, i32, [1 x i32], [1 x i32] } [[I14]], 1
; CHECK-NEXT:    [[I25:%.*]] = getelementptr i32, i32* [[I24]], i32 2
; CHECK-NEXT:    store i32 [[I19]], i32* [[I25]], align 4
; CHECK-NEXT:    br label [[BB26:%.*]]
; CHECK:       bb26:
; CHECK-NEXT:    [[I27:%.*]] = phi i32 [ [[I55:%.*]], [[BB54:%.*]] ], [ 0, [[BB21]] ]
; CHECK-NEXT:    [[I28:%.*]] = icmp slt i32 [[I27]], 8
; CHECK-NEXT:    br i1 [[I28]], label [[BB29:%.*]], label [[BB56]]
; CHECK:       bb29:
; CHECK-NEXT:    [[I30:%.*]] = extractvalue { i32*, i32*, i32, [1 x i32], [1 x i32] } [[I5]], 1
; CHECK-NEXT:    [[I31:%.*]] = getelementptr i32, i32* [[I30]], i32 1
; CHECK-NEXT:    store i32 [[I27]], i32* [[I31]], align 4
; CHECK-NEXT:    [[I32:%.*]] = extractvalue { i32*, i32*, i32, [1 x i32], [1 x i32] } [[I14]], 1
; CHECK-NEXT:    [[I33:%.*]] = getelementptr i32, i32* [[I32]], i32 1
; CHECK-NEXT:    store i32 [[I27]], i32* [[I33]], align 4
; CHECK-NEXT:    br label [[BB34:%.*]]
; CHECK:       bb34:
; CHECK-NEXT:    [[I35:%.*]] = phi i32 [ [[I53:%.*]], [[BB37:%.*]] ], [ 0, [[BB29]] ]
; CHECK-NEXT:    [[I36:%.*]] = icmp slt i32 [[I35]], 256
; CHECK-NEXT:    br i1 [[I36]], label [[BB37]], label [[BB54]]
; CHECK:       bb37:
; CHECK-NEXT:    [[I38:%.*]] = extractvalue { i32*, i32*, i32, [1 x i32], [1 x i32] } [[I5]], 1
; CHECK-NEXT:    [[I39:%.*]] = getelementptr i32, i32* [[I38]], i32 0
; CHECK-NEXT:    store i32 [[I35]], i32* [[I39]], align 4
; CHECK-NEXT:    [[I40:%.*]] = extractvalue { i32*, i32*, i32, [1 x i32], [1 x i32] } [[I14]], 1
; CHECK-NEXT:    [[I41:%.*]] = getelementptr i32, i32* [[I40]], i32 0
; CHECK-NEXT:    store i32 [[I35]], i32* [[I41]], align 4
; CHECK-NEXT:    [[I42:%.*]] = extractvalue { i32*, i32*, i32, [1 x i32], [1 x i32] } [[I14]], 1
; CHECK-NEXT:    [[I43:%.*]] = getelementptr i32, i32* [[I42]], i32 0
; CHECK-NEXT:    [[I44:%.*]] = bitcast i32* [[I43]] to <5 x i32>*
; CHECK-NEXT:    [[I45:%.*]] = load <5 x i32>, <5 x i32>* [[I44]], align 4
; CHECK-NEXT:    [[I46:%.*]] = call <128 x bfloat> @llvm.tpc.ld.tnsr.v128bf16.i1(<5 x i32> [[I45]], i8 0, i32 0, <128 x bfloat> undef, i1 true, i1 false)
; CHECK-NEXT:    [[TMP0:%.*]] = call <128 x float> @llvm.tpc.convert.v128f32.v128bf16.i1(<128 x bfloat> [[I46]], i8 1, i32 327680, <128 x float> undef, i1 true, i1 false)
; CHECK-NEXT:    [[TMP1:%.*]] = call <128 x bfloat> @llvm.tpc.convert.v128bf16.v128f32.i1(<128 x float> [[TMP0]], i8 0, i32 327940, <128 x bfloat> undef, i1 true, i1 false)
; CHECK-NEXT:    [[I49:%.*]] = extractvalue { i32*, i32*, i32, [1 x i32], [1 x i32] } [[I5]], 1
; CHECK-NEXT:    [[I50:%.*]] = getelementptr i32, i32* [[I49]], i32 0
; CHECK-NEXT:    [[I51:%.*]] = bitcast i32* [[I50]] to <5 x i32>*
; CHECK-NEXT:    [[I52:%.*]] = load <5 x i32>, <5 x i32>* [[I51]], align 4
; CHECK-NEXT:    call void @llvm.tpc.st.tnsr.v128bf16(<5 x i32> [[I52]], i8 1, <128 x bfloat> [[TMP1]], i32 0, i1 true, i1 false)
; CHECK-NEXT:    [[I53]] = add i32 [[I35]], 128
; CHECK-NEXT:    br label [[BB34]]
; CHECK:       bb54:
; CHECK-NEXT:    [[I55]] = add i32 [[I27]], 1
; CHECK-NEXT:    br label [[BB26]]
; CHECK:       bb56:
; CHECK-NEXT:    [[I57]] = add i32 [[I19]], 1
; CHECK-NEXT:    br label [[BB18]]
; CHECK:       bb58:
; CHECK-NEXT:    ret void
;
bb:
  %i = alloca i32, i32 mul (i32 ptrtoint (i32* getelementptr (i32, i32* null, i32 1) to i32), i32 5), align 4, !dbg !7
  %i1 = insertvalue { i32*, i32*, i32, [1 x i32], [1 x i32] } undef, i32* %i, 0, !dbg !9
  %i2 = insertvalue { i32*, i32*, i32, [1 x i32], [1 x i32] } %i1, i32* %i, 1, !dbg !10
  %i3 = insertvalue { i32*, i32*, i32, [1 x i32], [1 x i32] } %i2, i32 0, 2, !dbg !11
  %i4 = insertvalue { i32*, i32*, i32, [1 x i32], [1 x i32] } %i3, i32 5, 3, 0, !dbg !12
  %i5 = insertvalue { i32*, i32*, i32, [1 x i32], [1 x i32] } %i4, i32 1, 4, 0, !dbg !13
  %i6 = extractvalue { i32*, i32*, i32, [1 x i32], [1 x i32] } %i5, 1, !dbg !14
  %i7 = getelementptr i32, i32* %i6, i32 0, !dbg !15
  %i8 = bitcast i32* %i7 to <5 x i32>*, !dbg !16
  store <5 x i32> zeroinitializer, <5 x i32>* %i8, align 4, !dbg !17
  %i9 = alloca i32, i32 mul (i32 ptrtoint (i32* getelementptr (i32, i32* null, i32 1) to i32), i32 5), align 4, !dbg !18
  %i10 = insertvalue { i32*, i32*, i32, [1 x i32], [1 x i32] } undef, i32* %i9, 0, !dbg !19
  %i11 = insertvalue { i32*, i32*, i32, [1 x i32], [1 x i32] } %i10, i32* %i9, 1, !dbg !20
  %i12 = insertvalue { i32*, i32*, i32, [1 x i32], [1 x i32] } %i11, i32 0, 2, !dbg !21
  %i13 = insertvalue { i32*, i32*, i32, [1 x i32], [1 x i32] } %i12, i32 5, 3, 0, !dbg !22
  %i14 = insertvalue { i32*, i32*, i32, [1 x i32], [1 x i32] } %i13, i32 1, 4, 0, !dbg !23
  %i15 = extractvalue { i32*, i32*, i32, [1 x i32], [1 x i32] } %i14, 1, !dbg !24
  %i16 = getelementptr i32, i32* %i15, i32 0, !dbg !25
  %i17 = bitcast i32* %i16 to <5 x i32>*, !dbg !26
  store <5 x i32> zeroinitializer, <5 x i32>* %i17, align 4, !dbg !27
  br label %bb18, !dbg !28

  bb18:                                             ; preds = %bb56, %bb
  %i19 = phi i32 [ %i57, %bb56 ], [ 0, %bb ]
  %i20 = icmp slt i32 %i19, 2, !dbg !29
  br i1 %i20, label %bb21, label %bb58, !dbg !30

  bb21:                                             ; preds = %bb18
  %i22 = extractvalue { i32*, i32*, i32, [1 x i32], [1 x i32] } %i5, 1, !dbg !31
  %i23 = getelementptr i32, i32* %i22, i32 2, !dbg !32
  store i32 %i19, i32* %i23, align 4, !dbg !33
  %i24 = extractvalue { i32*, i32*, i32, [1 x i32], [1 x i32] } %i14, 1, !dbg !34
  %i25 = getelementptr i32, i32* %i24, i32 2, !dbg !35
  store i32 %i19, i32* %i25, align 4, !dbg !36
  br label %bb26, !dbg !37

  bb26:                                             ; preds = %bb54, %bb21
  %i27 = phi i32 [ %i55, %bb54 ], [ 0, %bb21 ]
  %i28 = icmp slt i32 %i27, 8, !dbg !38
  br i1 %i28, label %bb29, label %bb56, !dbg !39

  bb29:                                             ; preds = %bb26
  %i30 = extractvalue { i32*, i32*, i32, [1 x i32], [1 x i32] } %i5, 1, !dbg !40
  %i31 = getelementptr i32, i32* %i30, i32 1, !dbg !41
  store i32 %i27, i32* %i31, align 4, !dbg !42
  %i32 = extractvalue { i32*, i32*, i32, [1 x i32], [1 x i32] } %i14, 1, !dbg !43
  %i33 = getelementptr i32, i32* %i32, i32 1, !dbg !44
  store i32 %i27, i32* %i33, align 4, !dbg !45
  br label %bb34, !dbg !46

  bb34:                                             ; preds = %bb37, %bb29
  %i35 = phi i32 [ %i53, %bb37 ], [ 0, %bb29 ]
  %i36 = icmp slt i32 %i35, 256, !dbg !47
  br i1 %i36, label %bb37, label %bb54, !dbg !48

  bb37:                                             ; preds = %bb34
  %i38 = extractvalue { i32*, i32*, i32, [1 x i32], [1 x i32] } %i5, 1, !dbg !49
  %i39 = getelementptr i32, i32* %i38, i32 0, !dbg !50
  store i32 %i35, i32* %i39, align 4, !dbg !51
  %i40 = extractvalue { i32*, i32*, i32, [1 x i32], [1 x i32] } %i14, 1, !dbg !52
  %i41 = getelementptr i32, i32* %i40, i32 0, !dbg !53
  store i32 %i35, i32* %i41, align 4, !dbg !54
  %i42 = extractvalue { i32*, i32*, i32, [1 x i32], [1 x i32] } %i14, 1, !dbg !55
  %i43 = getelementptr i32, i32* %i42, i32 0, !dbg !56
  %i44 = bitcast i32* %i43 to <5 x i32>*, !dbg !57
  %i45 = load <5 x i32>, <5 x i32>* %i44, align 4, !dbg !58
  %i46 = call <128 x bfloat16> @llvm.tpc.ld.tnsr.v128bf16.i1(<5 x i32> %i45, i8 0, i32 0, <128 x bfloat16> undef, i1 true, i1 false), !dbg !59
  %i47 = fpext <128 x bfloat16> %i46 to <128 x float>, !dbg !60
  %i48 = fptrunc <128 x float> %i47 to <128 x bfloat16>, !dbg !61
  %i49 = extractvalue { i32*, i32*, i32, [1 x i32], [1 x i32] } %i5, 1, !dbg !62
  %i50 = getelementptr i32, i32* %i49, i32 0, !dbg !63
  %i51 = bitcast i32* %i50 to <5 x i32>*, !dbg !64
  %i52 = load <5 x i32>, <5 x i32>* %i51, align 4, !dbg !65
  call void @llvm.tpc.st.tnsr.v128bf16(<5 x i32> %i52, i8 1, <128 x bfloat16> %i48, i32 0, i1 true, i1 false), !dbg !66
  %i53 = add i32 %i35, 128, !dbg !67
  br label %bb34, !dbg !68

  bb54:                                             ; preds = %bb34
  %i55 = add i32 %i27, 1, !dbg !69
  br label %bb26, !dbg !70

  bb56:                                             ; preds = %bb26
  %i57 = add i32 %i19, 1, !dbg !71
  br label %bb18, !dbg !72

  bb58:                                             ; preds = %bb18
  ret void, !dbg !73
}

!llvm.dbg.cu = !{!0}
!llvm.module.flags = !{!2}

!0 = distinct !DICompileUnit(language: DW_LANG_C, file: !1, producer: "mlir", isOptimized: true, runtimeVersion: 0, emissionKind: FullDebug)
!1 = !DIFile(filename: "LLVMDialectModule", directory: "/")
!2 = !{i32 2, !"Debug Info Version", i32 3}
!3 = distinct !DISubprogram(name: "main", linkageName: "main", scope: null, file: !4, line: 35, type: !5, scopeLine: 35,  retainedNodes: !6)
!4 = !DIFile(filename: "<stdin>", directory: "/tmp/JSONS")
!5 = !DISubroutineType(types: !6)
!6 = !{}
!7 = !DILocation(line: 53, column: 11, scope: !8)
!8 = !DILexicalBlockFile(scope: !3, file: !4, discriminator: 0)
!9 = !DILocation(line: 55, column: 11, scope: !8)
!10 = !DILocation(line: 56, column: 11, scope: !8)
!11 = !DILocation(line: 58, column: 11, scope: !8)
!12 = !DILocation(line: 60, column: 11, scope: !8)
!13 = !DILocation(line: 61, column: 11, scope: !8)
!14 = !DILocation(line: 62, column: 11, scope: !8)
!15 = !DILocation(line: 67, column: 11, scope: !8)
!16 = !DILocation(line: 68, column: 11, scope: !8)
!17 = !DILocation(line: 69, column: 5, scope: !8)
!18 = !DILocation(line: 77, column: 11, scope: !8)
!19 = !DILocation(line: 79, column: 11, scope: !8)
!20 = !DILocation(line: 80, column: 11, scope: !8)
!21 = !DILocation(line: 82, column: 11, scope: !8)
!22 = !DILocation(line: 84, column: 11, scope: !8)
!23 = !DILocation(line: 85, column: 11, scope: !8)
!24 = !DILocation(line: 86, column: 11, scope: !8)
!25 = !DILocation(line: 91, column: 11, scope: !8)
!26 = !DILocation(line: 92, column: 11, scope: !8)
!27 = !DILocation(line: 93, column: 5, scope: !8)
!28 = !DILocation(line: 94, column: 5, scope: !8)
!29 = !DILocation(line: 96, column: 11, scope: !8)
!30 = !DILocation(line: 97, column: 5, scope: !8)
!31 = !DILocation(line: 99, column: 11, scope: !8)
!32 = !DILocation(line: 104, column: 11, scope: !8)
!33 = !DILocation(line: 105, column: 5, scope: !8)
!34 = !DILocation(line: 106, column: 11, scope: !8)
!35 = !DILocation(line: 111, column: 11, scope: !8)
!36 = !DILocation(line: 112, column: 5, scope: !8)
!37 = !DILocation(line: 113, column: 5, scope: !8)
!38 = !DILocation(line: 115, column: 11, scope: !8)
!39 = !DILocation(line: 116, column: 5, scope: !8)
!40 = !DILocation(line: 118, column: 11, scope: !8)
!41 = !DILocation(line: 123, column: 11, scope: !8)
!42 = !DILocation(line: 124, column: 5, scope: !8)
!43 = !DILocation(line: 125, column: 11, scope: !8)
!44 = !DILocation(line: 130, column: 11, scope: !8)
!45 = !DILocation(line: 131, column: 5, scope: !8)
!46 = !DILocation(line: 132, column: 5, scope: !8)
!47 = !DILocation(line: 134, column: 11, scope: !8)
!48 = !DILocation(line: 135, column: 5, scope: !8)
!49 = !DILocation(line: 137, column: 11, scope: !8)
!50 = !DILocation(line: 142, column: 11, scope: !8)
!51 = !DILocation(line: 143, column: 5, scope: !8)
!52 = !DILocation(line: 144, column: 11, scope: !8)
!53 = !DILocation(line: 149, column: 11, scope: !8)
!54 = !DILocation(line: 150, column: 5, scope: !8)
!55 = !DILocation(line: 151, column: 11, scope: !8)
!56 = !DILocation(line: 156, column: 12, scope: !8)
!57 = !DILocation(line: 157, column: 12, scope: !8)
!58 = !DILocation(line: 158, column: 12, scope: !8)
!59 = !DILocation(line: 163, column: 12, scope: !8)
!60 = !DILocation(line: 164, column: 12, scope: !8)
!61 = !DILocation(line: 165, column: 12, scope: !8)
!62 = !DILocation(line: 166, column: 12, scope: !8)
!63 = !DILocation(line: 171, column: 12, scope: !8)
!64 = !DILocation(line: 172, column: 12, scope: !8)
!65 = !DILocation(line: 173, column: 12, scope: !8)
!66 = !DILocation(line: 177, column: 12, scope: !8)
!67 = !DILocation(line: 178, column: 12, scope: !8)
!68 = !DILocation(line: 179, column: 5, scope: !8)
!69 = !DILocation(line: 181, column: 12, scope: !8)
!70 = !DILocation(line: 182, column: 5, scope: !8)
!71 = !DILocation(line: 184, column: 12, scope: !8)
!72 = !DILocation(line: 185, column: 5, scope: !8)
!73 = !DILocation(line: 187, column: 5, scope: !8)
