; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -cast-swizzle-opt -aggressive-cast-swizzle -S | FileCheck %s
;XFAIL:*

@llvm.embedded.module = private constant [15728 x i8] c"BC\C0\DE5\14\00\00\05\00\00\00b\0C0$JY\BEfM\FB\B4_\0BQ\80L\01\00\00\00!\0C\00\00q\0D\00\00\0B\02!\00\02\00\00\00\16\00\00\00\07\81#\91A\C8\04I\06\1029\92\01\84\0C%\05\08\19\1E\04\8Bb\80\1CE\02B\92\0BB\E4\102\148\08\18K\0A2r\88Hp\C4!#D\12\87\8C\10A\92\02d\C8\08\B1\14 CF\88 \C9\012r\84\18*(*\901|\B0\\\91 \C7\C8\00\00\00\89 \00\00I\00\00\002\22\C8\09 d\85\04\93#\A4\84\04\93#\E3\84\A1\90\14\12L\8E\8C\0B\84\E4L\10\94\C2\1C\01\18\0C#\14\C0 B\10\CC\11@\83\08C0\030\88P\04#\00%8\10b\8E\00\14\E6\08\10Z\94\E1\A0`P\A3\04\01z\94\01\00\00P\A4\10\07\00\00@\939\82\A0 \00\00`\01\00T*d\19F\00\85\A2\1C\98\C0\02\80\A9T(3\170\8C\00\12[98\98\05\80S\A9Pg\18\01$\862|>\1F\02\15\84\C3\E1,\00\9CJ\85DgISD\09\93\FF\17\8B\03L:\FE?\00\12\FD\13\120\18\22\95\E1P\E2\90\A9\1C\87\C0\02\03\A8T\08U\8EC`\C1\01T*\A4*\06\00\00\00T*\C4*\C6\01\00\00T*\E4*\C7\E7\B3\00|*\15\82\95\E3\F3\01\00>\95\0A\C9\EE\92\A6\88\12&\FF\97\0E'\9Aj\9B\FF\1F\00\89\FE\09\09\9F\0F\D1\CAp\A8}\C8V\8A\03\83\01\A8\10n\18\01$\8Ar\E88\0B\80\AER\A1\DD@\00\05\08@\9C)\00\C2\D0g\18\01\14\00\00\00Q\18\00\00\BC\01\00\00\1BJ&\F8\FF\FF\FF\FF\01\90\88qx\07y\90\87r\18\07z`\87|h\03yx\87zp\07r(\07rh\03rH\07{H\07r(\876\98\87x\90\07zh\03s\80\876h\87p\A0\07t\00\CC!\1C\D8a\1E\CA\01 \C8!\1D\E6!\1C\C4\81\1D\CA\A1\0D\E8!\1C\D2\81\1D\DA`\1C\C2\81\1D\D8a\1E\00s\08\07v\98\87r\00\08s\90\87ph\87rh\03xx\87tp\07z(\07y\00\C2\81\1D\D8\01 \D8\A1\1C\E6a\1E\DA\00\1E\E4\A1\1C\C6!\1D\E6\A1\1C\DA\C0\1C\E0\A1\1D\C2\81\1C\00s\08\07v\98\87r\00\88vH\07wh\03v(\87s\08\07vh\03{(\87q\A0\87w\90\876\B8\87t \07z@\07@\0E\E0\80\0E\F0\00 \DC\E1\1D\DA \1D\DC\C1\1C\E6\A1\0D\CC\01\1E\DA\A0\1D\C2\81\1E\D0\010\87p`\87y(\07\80p\87wh\03u\A8\87v\80\876\A0\87p\10\07v(\87y\00\CC!\1C\D8a\1E\CA\01 \DC\E1\1D\DA\C0\1D\C2\C1\1D\E6\A1\0D\CC\01\1E\DA\A0\1D\C2\81\1E\D0\010\87p`\87y(\07\80p\87wh\83yH\87sp\87r \876\D0\87r\90\87w\98\8760\07xh\83v\08\07z@\07\C0\1C\C2\81\1D\E6\A1\1C\00\C2\1D\DE\A1\0D\E8A\1E\C2\01\1E\E0!\1D\DC\E1\1C\DA\A0\1D\C2\81\1E\D0\010\87p`\87y(\07\80\98\07z\08\87qX\876\80\07yx\07z(\87q\A0\87w\90\876\10\87z0\07s(\07yh\83yH\07}(\07\00\0F\00\82\1E\C2A\1E\CE\A1\1C\E8\A1\0D\C6\01\1E\EA\018\87p\A8\07rH\07\80\A0\87p\90\87s(\07zh\03s(\87p\A0\87z\90\87r\98\07`\0D\CE!\1C\EA\81\1C\D2\01 \EA\C1\1D\E6!\1C\CC\A1\1C\DA\C0\1C\E0\A1\0D\DA!\1C\E8\01\1D\00s\08\07v\98\87r\00\88z\98\87rh\83yx\07s\A0\8760\07vx\87p\A0\07\C0\1C\C2\81\1D\E6\A1\1C\80\0D\88\F0\FF\FF\FF\FF\03\D0\06\80\04\F4\C1\06b\08\00>\D8@\10\02\B0l0\8A\FF\FF\FF\FF\1F\00\09\A06\90\8C\F1\FF\FF\FF\FF\03 \00\121\0E\EF \0F\F2P\0E\E3@\0F\EC\90\0Fm \0F\EFP\0F\EE@\0E\E5@\0Em@\0E\E9`\0F\E9@\0E\E5\D0\06\F3\10\0F\F2@\0Fm`\0E\F0\D0\06\ED\10\0E\F4\80\0E\809\84\03;\CCC9\00\049\A4\C3<\84\838\B0C9\B4\01=\84C:\B0C\1B\8CC8\B0\03;\CC\03`\0E\E1\C0\0E\F3P\0E\00a\0E\F2\10\0E\EDP\0Em\00\0F\EF\90\0E\EE@\0F\E5 \0F@8\B0\03;\00\04;\94\C3<\CCC\1B\C0\83<\94\C38\A4\C3<\94C\1B\98\03<\B4C8\90\03`\0E\E1\C0\0E\F3P\0E\00\D1\0E\E9\E0\0Em\C0\0E\E5p\0E\E1\C0\0Em`\0F\E50\0E\F4\F0\0E\F2\D0\06\F7\90\0E\E4@\0F\E8\00\C0\01@\B8\C3;\B4A:\B8\839\CCC\1B\98\03<\B4A;\84\03=\A0\03`\0E\E1\C0\0E\F3P\0E\00\E1\0E\EF\D0\06\EAP\0F\ED\00\0Fm@\0F\E1 \0E\ECP\0E\F3\00\98C8\B0\C3<\94\03@\B8\C3;\B4\81;\84\83;\CCC\1B\98\03<\B4A;\84\03=\A0\03`\0E\E1\C0\0E\F3P\0E\00\E1\0E\EF\D0\06\F3\90\0E\E7\E0\0E\E5@\0Em\A0\0F\E5 \0F\EF0\0Fm`\0E\F0\D0\06\ED\10\0E\F4\80\0E\809\84\03;\CCC9\00\84;\BCC\1B\D0\83<\84\03<\C0C:\B8\C39\B4A;\84\03=\A0\03`\0E\E1\C0\0E\F3P\0E\001\0F\F4\10\0E\E3\B0\0Em\00\0F\F2\F0\0E\F4P\0E\E3@\0F\EF \0Fm \0E\F5`\0E\E6P\0E\F2\D0\06\F3\90\0E\FAP\0E\00\1E\00\04=\84\83<\9CC9\D0C\1B\8C\03<\D4\03p\0E\E1P\0F\E4\90\0E\00A\0F\E1 \0F\E7P\0E\F4\D0\06\E6P\0E\E1@\0F\F5 \0F\E50\0F\C0\1A\9CC8\D4\039\A4\03@\D4\83;\CCC8\98C9\B4\819\C0C\1B\B4C8\D0\03:\00\E6\10\0E\EC0\0F\E5\00\10\F50\0F\E5\D0\06\F3\F0\0E\E6@\0Fm`\0E\EC\F0\0E\E1@\0F\809\84\03;\CCC9\00\1BN\E6\F8\FF\FF\FF\FF\01\10\00\89\18\87w\90\07y(\87q\A0\07v\C8\876\90\87w\A8\07w \87r \876 \87t\B0\87t \87rh\83y\88\07y\A0\8760\07xh\83v\08\07z@\07\C0\1C\C2\81\1D\E6\A1\1C\00\82\1C\D2a\1E\C2A\1C\D8\A1\1C\DA\80\1E\C2!\1D\D8\A1\0D\C6!\1C\D8\81\1D\E6\010\87p`\87y(\07\800\07y\08\87v(\876\80\87wH\07w\A0\87r\90\07 \1C\D8\81\1D\00\82\1D\CAa\1E\E6\A1\0D\E0A\1E\CAa\1C\D2a\1E\CA\A1\0D\CC\01\1E\DA!\1C\C8\010\87p`\87y(\07\80h\87tp\876`\87r8\87p`\876\B0\87r\18\07zx\07yh\83{H\07r\A0\07t\00\E4\00\0E\E8\00\0F\00\C2\1D\DE\A1\0D\D2\C1\1D\CCa\1E\DA\C0\1C\E0\A1\0D\DA!\1C\E8\01\1D\00s\08\07v\98\87r\00\08wx\876P\87zh\07xh\03z\08\07q`\87r\98\07\C0\1C\C2\81\1D\E6\A1\1C\00\C2\1D\DE\A1\0D\DC!\1C\DCa\1E\DA\C0\1C\E0\A1\0D\DA!\1C\E8\01\1D\00s\08\07v\98\87r\00\08wx\876\98\87t8\07w(\07rh\03}(\07yx\87yh\03s\80\876h\87p\A0\07t\00\CC!\1C\D8a\1E\CA\01 \DC\E1\1D\DA\80\1E\E4!\1C\E0\01\1E\D2\C1\1D\CE\A1\0D\DA!\1C\E8\01\1D\00s\08\07v\98\87r\00\88y\A0\87p\18\87uh\03x\90\87w\A0\87r\18\07zx\07yh\03q\A8\07s0\87r\90\876\98\87t\D0\87r\00\F0\00 \E8!\1C\E4\E1\1C\CA\81\1E\DA`\1C\E0\A1\1E\80s\08\87z \87t\00\08z\08\07y8\87r\A0\8760\87r\08\07z\A8\07y(\87y\00\D6\E0\1C\C2\A1\1E\C8!\1D\00\A2\1E\DCa\1E\C2\C1\1C\CA\A1\0D\CC\01\1E\DA\A0\1D\C2\81\1E\D0\010\87p`\87y(\07\80\A8\87y(\876\98\87w0\07zh\03s`\87w\08\07z\00\CC!\1C\D8a\1E\CA\01\D8` \01\90\00\DD\06#\F9\FF\FF\FF\FF\01\90\00:\D8`(\FF\FF\FF\FF?\00\12Pm@\96\00H\80\05\A0\83\0D\08#\00\09\B0\00\D5\06\A2!\00>\D8@8\FF\FF\FF\FF?\00\D2\06\E2\09\80nC\01\05A\00\22\1B\8AH\08\02\10\01\00\00I\18\00\00\0A\00\00\00\13\82`\C2 \0C\C4\84\A0\98\10\18\13\82c\82p \13\82dB\A0L \84\85i&\04\CE\84\E0\99 @\11\00\00\00\13\06z\80\87q\D8 \16\E5\D0\06\F0\00\07z0\07r\A0\07s \07z0\07r\D0\06\F0\10\07z0\07r\A0\07s \07z0\07r\D0\06\F0 \07z0\07r\A0\07s \07z0\07r\D0\06\F00\07z`\07t\A0\07v@\07z`\07t\D0\06\E90\07r\A0\07s \07z0\07r\D0\06\EE\80\07z\10\07v\A0\07s \07m`\0Eq`\07z\10\07v\A0\07q`\07m`\0Es \07z0\07r\A0\07s \07m`\0Fq`\07p\A0\07s \07z0\07r\D0\06\F6 \07u`\07z \07p@\07x\A0\07r\00\07t\80\07m`\0Fr\00\07t\80\07z \07p@\07x\A0\07r\00\07t\80\07m`\0Ft\00\07y`\07z \07p@\07x\A0\07r\00\07t\80\07m`\0Fx\10\07y \07z \07p@\07x\A0\07r\00\07t\80\07J\0F\08\11\92A\86\8C\14\11\014B\98\9C>ty\DD=n\95\F1\F4\16q\06u\8DwH\C0\14\18g\00\0C\00\00\00\00\00\00\C1\04\EC\90\A6f8\D0\00\10\00\00\00\00\00\00\82\09\D8!\81\813\1Ci\00\08\00\00\00\00\00\00\C1\04\EC\90\DC\A0\19\0E5\00\04\00\00\00\00\00\80`\02vH{\D0\0C\C7\1A\00\02\00\00\00\00\00@0\01;$Tp\86\83\0D\00\01\00\00\00\00\00 \98\80\1D\92-H\C3\D1\06\80\00\00\00\00\00\00\10L\C0\0E\09\1D\8E\E2p\03`\00\00\00\00\00\00\08&`\87\F4\0EEq\BC\010\00\00\00\00\00\00\04\13\B0C\A2\87\A28\E0\00\18\00\00\00\00\00\00\82\09\D8!\E5CQ\1Cq\00\0C\00\00\00\00\00\00\C1\04\0C\A9\FC\81@\00\00\08\00\00\00\00\00\00\00 \00&`H%\12X\03\04\80\00\00\00\00\00\00\00\00\000\01C*\9D\F8\1E \00\06\00\00\00\00\00\00\00\00\80\09\18R\E5E\F7\00\010\00\00\00\00\00\00\00\00\00L\C0\90\CA6\98\08\00\18\02\00\00\00\00\00\00\00\02`\02\86T\E2\C1L\00\C0\10\00\00\00\00\00\00\00\10\00\130\A4r\8F\CD\02\02`\00\00\00\00\00\00\00\00\00\98\80!U\8A8\13\000\04\00\00\00\00\00\00\00\04\C0\04\0C\A9nD\CB\80\00\18\00\00\00\00\00\00\00\00\00&`H\15'c\D0\01\010\00\00\00\00\00\00\00\00\00L\C0\90\8AV80\00\00\A6\00\00\00\00\00\00\00\80\00\98\80!\15\BCX\0D\10\00\02\00\00\00\00\00\00\00\00\C0\04\0C\A9LF\0D\C4\00\08\80\01\00\00\00\00\00\00\00\00`\02\86Tp\A3\99\01\000\06\00\00\00\00\00\00\00\04\C0\04\0C\A9T\E7B\03 \00\0E\00\00\00\00\00\00\00\00\80\09\18R\85O\A6\06@\00\1C\00\00\00\00\00\00\00\00\00\130\A4\D2\1F.\02\00\86\00\00\00\00\00\00\00\80\00\98\80!\95\0DEl\00\04\00\02\00\00\00\00\00\00\00\000\01C\AA3\8A\DC\00\08\80\03\00\00\00\00\00\00\00\00`\02\86Tx\84\C1\01\10\00\03\00\00\00\00\00\00\00\00\C0\04\0C\A9`\C9\0C\E4\00\08\80\01\00\00\00\00\00\00\00\00`\02\86T\F6$\06r\00\04\C0\00\00\00\00\00\00\00\00\000\01C*\9C\E2\EC\00\00\18\03\00\00\00\00\00\00\00\02`\02\86Tt\95\E1\01\10\00\09\00\00\00\00\00\00\00\00\C0\04\0C\A9Z\8B\0C\F6\00\08\80\01\00\00\00\00\00\00\00\00`\02\86T\F1U\06r\00\04\C0\00\00\00\00\00\00\00\00\000\01C*\1B\D3\E0\00\08\80\01\00\00\00\00\00\00\00\00`\02$6\08\14~k\00\00\C8\02\01\14\00\00\002\1E\98\18\19\11L\90\8C\09&G\C6\04C\0A\8C\00\D0\A0\00\FD\03*PP\A0\FC\FF\07\0A\D0\7F\A0\02\05\0A\10S\80\0Ac\04#\EB\97\FA7F\00\82\A0L\FF\C2\18\01\08\A2\FB\CD\0Bc\04\E9\8A\92r.\10\A0\04\0A\81\14#\00\05H\00\B1\18\00\00\93\00\00\003\08\80\1C\C4\E1\1Cf\14\01=\88C8\84\C3\8CB\80\07yx\07s\98q\0C\E6\00\0F\ED\10\0E\F4\80\0E3\0CB\1E\C2\C1\1D\CE\A1\1Cf0\05=\88C8\84\83\1B\CC\03=\C8C=\8C\03=\CCx\8Ctp\07{\08\07yH\87pp\07zp\03vx\87p \87\19\CC\11\0E\EC\90\0E\E10\0Fn0\0F\E3\F0\0E\F0P\0E3\10\C4\1D\DE!\1C\D8!\1D\C2a\1Ef0\89;\BC\83;\D0C9\B4\03<\BC\83<\84\03;\CC\F0\14v`\07{h\077h\87rh\077\80\87p\90\87p`\07v(\07v\F8\05vx\87w\80\87_\08\87q\18\87r\98\87y\98\81,\EE\F0\0E\EE\E0\0E\F5\C0\0E\EC0\03b\C8\A1\1C\E4\A1\1C\CC\A1\1C\E4\A1\1C\DCa\1C\CA!\1C\C4\81\1D\CAa\06\D6\90C9\C8C9\98C9\C8C9\B8\C38\94C8\88\03;\94\C3/\BC\83<\FC\82;\D4\03;\B0\C3\0C\C7i\87pX\87rp\83th\07x`\87t\18\87t\A0\87\19\CES\0F\EE\00\0F\F2P\0E\E4\90\0E\E3@\0F\E1 \0E\ECP\0E3 (\1D\DC\C1\1E\C2A\1E\D2!\1C\DC\81\1E\DC\E0\1C\E4\E1\1D\EA\01\1Ef\18Q8\B0C:\9C\83;\CCP$v`\07{h\077`\87wx\07x\98QL\F4\90\0F\F0P\0E3\1Ej\1E\CAa\1C\E8!\1D\DE\C1\1D~\01\1E\E4\A1\1C\CC!\1D\F0a\06T\85\838\CC\C3;\B0C=\D0C9\FC\C2<\E4C;\88\C3;\B0\C3\8C\C5\0A\87y\98\87w\18\87t\08\07z(\07r\98\81\\\E3\10\0E\EC\C0\0E\E5P\0E\F30#\C1\D2A\1E\E4\E1\17\D8\E1\1D\DE\01\1EfH\19;\B0\83=\B4\83\1B\84\C38\8CC9\CC\C3<\B8\C19\C8\C3;\D4\03<\CCH\B4q\08\07v`\07q\08\87qX\87\19\DB\C6\0E\EC`\0F\ED\E0\06\F0 \0F\E50\0F\E5 \0F\F6P\0En\10\0E\E30\0E\E50\0F\F3\E0\06\E9\E0\0E\E4P\0E\F80C\E1\DA!\1D\E6\A1\1C\F0\01\1E\CAa\1C\E8aF\D4\D9\C38\84\03;\B0\C3/\D8C:\CCC:\88C:\B0C:\D0C>\00y \00\00B\00\00\00r\1EH C\88\0C\19\09r2H #\81\8C\91\91\D1D\A0\10(d<12B\8E\90!\A3X 2\01J/<\D1\00\00\00\00wchar_sizeclang version 10.0.1 (ssh://gerrit:29418/tpc_llvm10 dc18ecd58013a5cbeeb9da4f73dac2351d74c5b3)omnipotent charSimple C/C++ TBAAint\00\00#\08@\1C\8C \00r0\82\A0\CC\C1\0C\83\11\1C3\04\C2\0C\011\C30,\C8\0C\03\C3 3\0C\05\83\CC08\0E\22#\81\09\CA\88\8D\CD\AE\CD\A5\ED\8D\AC\8E\AD\CC\C5\8C-\ECln\94\00I\85\8D\CD\AE\CD%\8D\AC\CC\8Dn\94 \01\00\A9\18\00\00\11\00\00\00\0B\0Ar(\87w\80\07zXp\98C=\B8\C38\B0C9\D0\C3\82\E6\1C\C6\A1\0D\E8A\1E\C2\C1\1D\E6!\1D\E8!\1D\DE\C1\1D\164\E3`\0E\E7P\0F\E1 \0F\E4@\0F\E1 \0F\E7P\0E\F4\00\00\00\00\D1\10\00\00\06\00\00\00\07\CC<\A4\83;\9C\03;\94\03=\A0\83<\94C8\90\C3\01\00\00\00a \00\00\06\06\00\00\13\04P,\10\00\00\00\11\00\00\00\A4(\94B \C0\08@\F1\07\D0\A2\08\080\03@\95\1A\18\01 @\11\94A)\90\A2\00\11(0\03@\8B\11\00\C2\CC\00\10\A0\00\03hQ\02\04(\88\02, \CE\08\C0\0C\00-\CA\A0\10J\01\00\00\00\F10\00\00\07\00\00\00\22G\C8\90Q\06\04\02\04\00\00\00long\1B\06\88A6\0CQ\84\00\00\00\003\11\01\10\07\A30\13\11\00q0\0A3\11\00\10\07\A30\13\01\00q0\0A3\11\00\10\07\A30\13\01\00q0\0A3\11\00\10\07\A30\13\01\00q0\0A3\11\00\10\07\A30\13\01\00q0\0A3\11\00\10\07\A30\13\01\00q0\0A3\11\00\10\07\A30\13\01\00q0\0A3\11\00\10\07\A30\13\01\00q0\0A3\11d\00\C4A*\CCD\04@\1C\8C\C2L\04\00\C4\C1(\CCD\90\01\10\07\A90\13\11\00q0\0A3\11d\00\C4A*\CCD\04@\1C\8C\C2L\04\00\C4\C1(\CCDp@\1C\A4\C2L\04\07\C4A*\CCDp@\1C\A4\C2L\04\07\C4A*\CCDp@\1C\A4\C2L\04\07\C4A*\CCDp@\1C\A4\C2L\04\07\C4A*\CCDp@\1C\A4\C2L\04\07\C4A*\CCDp@\1C\A4\C2L\04\19\00q\90\0A3\11\01\10\07\A30\13\11\00q0\0Ai\06\8C\1D10\14\10\04\83\06\1D\FE \181 \00\10\04\83\E7\1C\86\0D\084\08\06 \CF\80\B1#\06\86\02\82`\D0\A8C(\04\94\06\811b@\00 \08\06O:\9C\10\C0\B0\01\B1\06\C1\00\A4\1A0v\C4\C0P@\10\0C\1Aw \85`\C4\C0\00@\10\0C\A2u\18\85Q\186 \D8 \18\80\\\03\C6\8E\18\18\0A\08\82A\03\0F\A6\10\8C\18\18\00\08\82A\D4\0E\A5\B0\0A\C3\06D\1B\04\03@n\00\18\E4\06\80qB $\07\811\86\10\C0\02\AAB \02#\06\0B\00\82``\C9\03\11\A8\02+\A4\02*\9C\C2\88\C1\01\80 \18L\F4\D0\0A\AD\10\8C\18\1C\00\08\82\C1D\0F\AD0\0B\B3@u\00\18T\07\80qB #\06\07\00\82`0\D5\03,\D8B\90v\C0\D8\11\03C\01A0h\F8A\16\82\11\03\03\00A0\88\F2\E1\16ba\D8\80\C0\83`\00\F2\0E\18;b`( \08\06\8D?\D0B0b`\00 \08\06\D1>\E4B.\0C\1B\10y\10\0C\00\E9\01`\90\1E\00\C6\09\81\10(\04\C6\18B\E0\0B\88\0B\81\08\8C\18,\00\08\82\81\05\12D\80\0B\BAp\0B\B6P\0B#\06\07\00\82`0\89D8\ECB0bp\00 \08\06\93H\84C8\84\03\85\02`P(\00\C6\09\81\8C\18\1C\00\08\82\C14\12\E4@\0EA\8A\02cG\0C\0C\05\04\C1\A0Q\09p\08F\0C\0C\00\04\C1 :\89\\\F8\85a\03\82\14\82\01\C8Q`\EC\88\81\A1\80 \184,!\0E\C1\88\81\01\80 \18D)\B1\0B\E70l@\94B0\00d\0A\80A\A6\00\18'\04B\AE\10\18c\08\01;\A09\04\220b\B0\00 \08\06\96K\10\819\A0C9\90\C38\8C\18\1C\00\08\82\C1\04\13\E3\90\0E\C1\88\C1\01\80 \18L01\0E\EF\F0\0E\D4\0A\80A\AD\00\18'\042bp\00 \08\06SL\98\83<\04\E9\0A\8C\1D10\14\10\04\83\06'\DC!\1810\00\10\04\83\A8&\CC\A1\1D\86\0D\08X\08\06 _\81\B1#\06\86\02\82`\D0\E8\04<\04#\06\06\00\82`\10\DD\04:\D4\C3\B0\01\11\0B\C1\00\90,\00\06\C9\02`\9C\10\08\F1B`\8C!\04\FA\80\F4\10\88\C0\88\C1\02\80 \18X<A\04\F4`\0F\F3 \0F\F10bp\00 \08\06\93O\C0\C3=\04#\06\07\00\82`0\F9\04<\F4C?P.\00\06\E5\02`\9C\10\C8\88\C1\01\80 \18L?1\0F \11\A4.0v\C4\C0P@\10\0C\1A\B3\E0\87`\C4\C0\00@\10\0C\A2\B1\00\89}\186 x!\18\80\DC\05\C6\8E\18\18\0A\08\82A\83\16\FE\10\8C\18\18\00\08\82AT\16\221\12\C3\06D/\04\03@\BE\00\18\E4\0B\80qB \A4\0E\811\86\10\A0\04\8AD \02#\06\0B\00\82``\A9\05\11\88\04I\84\04H\FC\C3\88\C1\01\80 \18Ll\A1\12%\11\8C\18\1C\00\08\82\C1\C4\16*\B1\12+A\E5\00\18T\0E\80qB #\06\07\00\82`0\B5EK\B8D\90\E6\C0\D8\11\03C\01A0h\E8B%\82\11\03\03\00A0\88\E2\22$Rb\D8\80@\87`\00\F2\1C\18;b`( \08\06\8D]\B0D0b`\00 \08\06\D1\\\8CDL\0C\1B\10\E9\10\0C\00\A9\03`\90:\00\C6\09\81\10>\04\C6\18B`\13\08\13\81\08\8C\18,\00\08\82\81\85\17D\00\132\F1\12.\D1\12#\06\07\00\82`0\E9\C5J\CCD0bp\00 \08\06\93^\ACDN\E4\04\C5\03`P<\00\C6\09\81\8C\18\1C\00\08\82\C1\B4\17.\C1\13\01\81D`\8C!\04=A\22\11\18s\0C\81\90\13\C3\06\04I\04\03@#\11\18c\08AXPI\04\C6\1CC \F4\C4\B0\01q\12\C1\00\10J\04\C6\1CC\F0\13e1l@\A8D0\00\94\12\811\C7\10\9C\C5Y\0C\1B\10+\11\0C@\FA\03cG\0C\0C\05\04\C1\A0q\0D\B2\08\A8%\02c\0C! \0B\0C\C8B\04\86\0D\08\91\08\06`\96  \91\00\0C\82\89\C0\18C\08\D0\02\03\B4\10\81\E1\06\22@\83Y\86A\08\86\0D\08\93(\8B\01\C8\93`\EC\88\81\A1\80 \184\AD\D1\16\C1,\C1\93&\C1\D8\11\03C\01A0hp\83,\824\09\C6\8E\18\18\0A\08\82A\93\1Bp\11\90J\00\C6\1CCY\04o1\C7\10\C0\85]\CC1\04q\B1\16s\0C\81\\\AC\C5\1CC0\17x1l@\B4D0\00\D4\12\811b\A0\00 \08\06Yn\04jQ\17i\11\17p\D1I\03L\D8\85]\0C\1B\10\81\90\00\04\13\811\86\10\E0\05\06l\01\024\13\811\C7\10\08{1l@\D4D0\00T\13\811b\A0\00 \08\06Yx\04r\D1\17q\91\17x\D1I\03N\F8\05i\0C\1B\10\81\90\00y\13\8C\1D10\14\10\04\83f=B# \B5\08\8C1\84`/0@\0D\11\186 v\22\18\80Y\02\82v\020\A8-\02c\0C!\F8\0B\0CXC\04\86\1B\88\00\0Df\19\8C\22\186 \C6\024\06 \C1\82\B1#\06\86\02\82`\D0\A8\87j\04\B3\04M\82\05cG\0C\0C\05\04\C1\A0\A9\8F\D0\08\12,\18;b`( \08\06\8D}\B4F@g\01\18s\0C\A2\11\B0\C6\1CC\D0\1A\B3Af\01\18s\0CB\90\1As\0C\01l\A4\C6\1CC\10\1B\B61l@\A0E0\00\84\16\811b\A0\00 \08\06\D9}\04\A51\1B\A7\F1\1A\AE\D1I\C3Z\D0\06m\0C\1B\10\81\90\00\B4\16\811\86\10\D8\06\06\AA\01\02\E4\16\811\C7\10\08\B91l@\C0E0\00\04\17\811b\A0\00 \08\06\D9\7F\04\AD\B1\1B\AFq\1B\B6\D1I\C3\\\F0\86x\0C\1B\10\81\90\00)\17\8C\1D10\14\10\04\83&Ej#H\B9`\EC\88\81\A1\80 \184*\12\1E\01\ED\05`\CC1\D8F\00\1Es\0CAx\9C\07\E9\05`\CC1\08Ao\CC1\04\E4\D1\1Bs\0CAy\A8\C7\B0\01\A1\17\C1\00\90^\04\C6\88\81\02\80 \18d+\12\94\C7y\EC\C6x\88G'\0D}\81\1E\E81l@\04B\02P_\04\C6\18B\A0\1E\18\F8\06\08\10h\04\C6\1CC \B4\C7\B0\01!\1A\C1\00\90h\04\C6\88\81\02\80 \18d3\12\B4\C7{\8C\C7z\A8G'\0D\A5\01\1F\F61l@\04B\02$i0v\C4\C0P@\10\0C\9A\1E\99\8F\80x#0\C6\10\82\FC\C0@?D`\D8\80@\8D`\00f\09\0EB\0D\C0\A0\DF\08\8C1\84\A0?0\F0\0F\11\18n \024\98eH\90`\D8\80\A8\8D\F5\18\80l\0D\C6\8E\18\18\0A\08\82A\C3#\FC\11\CC\12,\D9\1A\8C\1D10\14\10\04\83\E6L\FE#\C8\D6`\EC\88\81\A1\80 \184h\02\22A'\0D\B7\D1\1F\FDA\01&\C3\88\81\02\80 \18tb\12\D0\C7{\B8\C7~\E8\C7\B0\01\11\1BA\02$l0v\C4\C0P@\10\0C\1A6!\91\A0\93\86\DD\08\91\13\A1\00\93a\C4@\01@\10\0C:3\09\F0c>\E4\E3?\FCc\D8\80\A0\8D \01\A868\192\F8,\D9\06'C\06\9F\1D10\00\10\04\030P\93!\C8\80\B3\C3\06\04o\04\09\90\BA\C1\D8\11\03C\01A0h\D8\C4E\82\E4\0D\C6\8E\18\18\0A\08\82A\D3&/\12\E4n0v\C4\C0P@\10\0C\1A<\81\91 w\83\B1#\06\86\02\82`\D0\E4I\8C\04\9D4\94\87\8B\B8\08\05\98\0C#\06\0A\00\82`\D0\CDIP\22 \F2\1F,\B2\22\C3\06\C4o\04\09\90\BE\C1\D8\11\03C\01A0h\FA\A4F\82N\1A\D2CFp\84\02L\86\11\03\05\00A0\E8\EE$H\11\12\19\11\18y\91a\03B<\82\04\A0\F1\E0d\C8\E0\B3D\1E\9C\0C\19|v\C4\C0\00@\10\0C\C0`O\86 \03\CE\0E\1B\10\EA\11$@\A2\07cG\0C\0C\05\04\C1\A0\E9\93\1F\09R=\18;b`( \08\06\8D\9F\80I\90\E9\C1\D8\11\03C\01A0hR%L\82L\0F\C6\8E\18\18\0A\08\82A\A3*b\12t\D2@\1F?\F2#\14`2\8C\18(\00\08\82AG*\81\8D\C4\08\8C\F4\08\8F\0C\1B\10\ED\11$@\B2\07cG\0C\0C\05\04\C1\A0q\153\09:i\C0\8F1I\13\0A0\19F\0C\14\00\04\C1\A0C\95@Gj\84F\C2\04L\86\0D\08\F8\08\12\80\E2\83\93!\83\CF\92|p2d\F0\D9\11\03\03\00A0\00\03V\19\82\0C8;l@\E0G\90\00i\1F\8C\1D10\14\10\04\83\C6U\E0$H\FC`\EC\88\81\A1\80 \184\AF\12'A\DE\07cG\0C\0C\05\04\C1\A0\D1\159\09\C8?8\19\88?8\19F\0C\16\00\04\C1@\0CbE\08\C6$N~\A4M\D8d\D8\80\D8\8F \01R?\18;b`( \08\06\8D\AF\D8I@%\C2\C9@\FD\C1\C90b\B0\00 \08\06bP+Bp&u2&q\02'\C3\06\84\7F\04\09\90\FD\C1\D8\11\03C\01A0h\C4\C5M\02\FA\0FN\86\11\03c\01A00\83[\F9\8F \FD\83\B1#\06\86\02\82`\D0\90\CB\9E\04T#\801\C7\00'\81\9E\CC1\04{\12*D#\801\C7 \04w2\C7\10\F8\C9\9D\CC1\04\7FB*\C3\06\84\89\04\03@&\12\18\9D4\A0H\A8\84\0A\05\98\0C#\06\0A\00\82`\80\06\E12\C0I0*\7F\E2'\94\22\811\86\10\90\0A\06x\02\02\C4\22\811\C7\10\08\A72l@\B8H0\00\E4\22\81\D1I\03\8C\A4\CA\ABP\80\C90b\A0\00 \08\06h\90.\03\9E\04\ABr*\A6\920\C2\D8\11\03C\01A0h\EE\C5U\02B\13\C0\98c\18\95\A0U\E6\18\02W\A1\15:\13\C0\98c\10\02U\99c\08bEU\E6\18\02Y\B9\95a\03\02G\82\01 \1C\09\0C\E2\11N\86\11\03\05\00A0P\03y\11B%\A8\95X\81\15\D2\91\C0 1\E1d\181P\00\10\04\035\A0\17AT\82[\99\15YI\1Ea\EC\88\81\A1\80 \184\F9\A2+A\FA\08cG\0C\0C\05\04\C1\A0\D1\97]\09\12L\18;b`( \08\06\CD\BE\C4J\90b\C2\D8\11\03C\01A0h\F8\C5W\82$\13\C6\8E\18\18\0A\08\82A\D3/\BF\12$\9A0v\C4\C0P@\10\0C\1A\7F\01\97 \D9\84\B1#\06\86\02\82`\D0\FCK\B8\04\09'\8C\1D10\14\10\04\83\06d\C4%\98%PHN\00\03\03s\01\81a\03\82N\82\01\98%8\B2N\18;b`( \08\06\CD\C8\90K\90w\C2\D8\11\03C\01A0hHFW\82\CC\13\C6\8E\18\18\0A\08\82AS2\E6\12\E4\9E0v\C4\C0P@\10\0C\1A\93\E1\95`\96\80\A1>\01\0C\0C\D8\05\04\86\0D\88?\09\06`\96\80HPa\EC\88\81\A1\80 \184)\A3.A\8A\0AcG\0C\0C\05\04\C1\A0Q\19p\09f\09\1C*\15\C0\C0 ]@`\D8\808\95`\00f\09\02\9A\15\C0\1818\00\10\04\83if\D8\85]\02\9A\15\C0\1818\00\10\04\83\89f\DAe^\02\A2\15\C0\1818\00\10\04\83if\DC\85^\02\A2\15\C0\1818\00\10\04\83\C9f\EA\E5]\02\A2\15\C0\1818\00\10\04\83\E9f\EC\C5^\02\AA\15\C0\1818\00\10\04\83\C9f\EE\E5^\02\AA\15\C0\1818\00\10\04\83)g\D8E^\02\AA\15\C0\1818\00\10\04\83Ig\DA%_\02\B2\15\C0\1818\00\10\04\83)g\DCE_\02\B2\15\C0\1818\00\10\04\83\89g\DC\A5^\02\B2\15\C0\1818\00\10\04\83\A9g\DE\85_\02\BA\15\C0\1818\00\10\04\83\89g\E0\A5_\02\BA\15\C0\1818\00\10\04\83\E9g\FA\05_\02\BA\15\C0\1818\00\10\04\83\09l\FC\E5_\02\C2\15\C0\1818\00\10\04\83\E9g\FE\05d\02\C2\15\C0\1818\00\10\04\83Il\E6e_\02\C2\15\C0\1818\00\10\04\83il\E8Ed\02\CA\15\C0\1818\00\10\04\83Il\EAed\82\D4\15\C6\8E\18\18\0A\08\82A\F33\FF\12$\AF0v\C4\C0P@\10\0C\1A\B0\01\99 }\85\B1#\06\86\02\82`\D0\84M\C8\04\09.\8C\1D10\14\10\04\83FlD&Hqa\EC\88\81\A1\80 \184c32A\92\0BcG\0C\0C\05\04\C1\A0!\1B\92\09\D2\\\18;b`( \08\06M\D9\94L\90\E8\C2\D8\11\03C\01A0h\CC\C6d\82T\17\C6\8E\18\18\0A\08\82As6'\13$\BB0v\C4\C0P@\10\0C\1A\B4A\99 \DD\85\B1#\06\86\02\82`\D0\A4M\CA\04\09/\8C\1D10\14\10\04\83FmT&Hya\EC\88\81\A1\80 \184k\C32A\D2\0BcG\0C\0C\05\04\C1\A0a\9B\96\094\1C\08\00\00\8A\01\00\00F\1A`\08\C0\B2\D4\BA\99\06\18\02\B0,\F5n\D0\02\86\00,K\7F\1B\AC@!0\0F\7F[\B8\80!\00\CB\D2\F3\D6\14!\CD@\\\BF\F4\00\02\F1K\13\10M\97\A0\14N\E4\07\CE\80\F1\B9\99\07\1C\15! \0D2\19\A4\00R\11\02\D2H\BAn\F0\01\050\0C8o\AF\02\05C-\BCmN\0F\D2\0C\C4\F5K\0F \10?\D1\0C\D6(\80T\84@\\\93\8E\9B`\00\C1P\8Bm\86\01\04C-\B7\D1\06\18\02\B0,\F6m\B2\01\86\00,\8Bm[c\00\C1P\8Bnf\C2D\1Bd\00\C1P\0Bo\94\01\04C-\BD\09\07\18\02\B0,vo\C0\01\86\00,\8B\CD[\BC@R\11\02\D2 S\DF\DF\81R8\91/8\CD\C0\D3\16\16\B5D#9\11\FD\0B\8E\13\0D\D2\1F\D4\C6W\08\C0\B2\D4\F670\D4b\81\01FE\08\C45\19b@!\00\CB\82\9Bb@!\00\CB\92\1F@A4S\84\99g@\C1PK\8D\9Bh@\C1PK\9D\1B\A9\00R\11\02\D2H\BBn\9B\01\05C-\B5m\A9\01\05C-5o\A1\02HE\08\C45\ED\B8\F1\0B\18\C00\D4\B4nqQK4\92\13\F1\BF\E08\D1 \FDAm\AA\02HE\08\C45\ED\BC\C9%\82\E3D\83\F4\07\B5]\0E\18\C00\D45ng\C2T\1B\E0@Q\D95\CD[\E7\80\01\0CC]\EB\D7\A0\14N\E4\13\CDP\D7\BB=\06\1C\15!\10\D7\B4[\E8\80\01\0CC]\F7&\15\0D\08S\FF\12\92\11\7FK4\92\13\D1\C6\1AP0\D4b\D3F\15\0D\08S\FF\12\92\11\7FK4\92\13\D9\06\1BP0\D4b\D7\A6\15\0D\08S\FF\12\92\11\7FK4\92\13\DD\06\15\0D\08S\FF\12\92\11\7FK4\92\13\E5v\1BP0\D4b\E3\86\15\0D\08S\FF\12\92\11\7FK4\92\13\EDf\15\0D\08S\FF\12\92\11\7FK4\92\13\F1\E6\1BP0\D4b\EF\A6\1BP0\D4b\EBW \15N\E4\0BN3\F8\C2B\00\0D\F5\E4\BA\B9\0A \15!\10\D7\C4\D7\C6\15\09\0B\014\D4\E3\0F\844\F9\D2\E2L\E6(P\00\C3\A0\E7\B6(@T\B5~\DF\83R8\91O4Cm\D3\C7\A0\14N\E4#\8DP\D7\B9\B5\07\08Um\F5\01Be\9B\9B\05\0C\C3_X\C3\1F\14\B5\FE\8B\DD\AF\DF|\BF\E7\E7\A0\14N\E4#\8DP\D7\BC\BDY\C00\FC\855\FCAQ\EB\BF\D8\FD\FA\CD\F7{o\C5\01\05C-7m\9F\02DU\EF\B7u\06 \15!\10\D7T\DF\86\1CP0\D4r\DB\C6\1CP0\D4r\DF&*P\00\C3\B0\E7\86\A6\09\804\FD\C5m\FF\93\F3\07E\AD\FFb\F7\EB7\DF\EB\BB\9D\07$\15! \0D2\E1\B7\AD\06 \15!\10\D7T\F7\96\1E\90T\84\804\C8\84\E7\A6\1E\90T\84\804\C8\84\EB\86\1E\90T\84\804\C8\84\E3\E6E\B5D#9Q\FE\0B\8E\13\0D\D2\1F\D4\7F`_\00R8\91/8\CD`z\84\00,\CB\09@\85\13\F9\82\D3\0C\BE\B0\10@C=\C6\1DP0\D4\82\D3\06\1EP0\D4\82\DB6)@T\B6\BE[n\00R\11\02qMvn\B4\02DU\F3\BA\95i\02 M\7Fq\DB\FF\E4\FCAQ\EB\BF\D8\FD\FA\CD\F7;oi\C4D\F3\BD\0D\0A$\15! \0D2\E5\BC\85\07\0C\02\F3\18\A1@R\11\02\D2 S\DE\9B\BC\80R\11\02\D2 SM\D3\B6\A6\09\804\FD\C5m\FF\93\F3\07E\AD\FFb\F7\EB7\DF\EF\B8\D1\0B(\15! \0D2\D5tm\F5\02JE\08H\83L5m\9B\BD\80R\11\02\D2 SM\DF6\16\B5D#9\91\FD\0B\8E\13\0D\D2\1F\D4\E6\1FP\08\CC\93\E7\B6/\90T\84@\\SM\E7F8\A0T\84\804\C8T\D3\BDEE\03\C2\D0\BF\84d\C4\DF\12\8D\E4D\F4\19(\85\13\F9\813`\F9nS\D1\800\F4/!\19\F1\B7D#9\91mY\D1\800\F4/!\19\F1\B7D#9\D1m\D4\01HE\08H#\DD\BA=E\03\C2\D0\BF\84d\C4\DF\12\8D\E4D\B9\1D\07 \15!\10\D7t\D7v\15\0D\08C\FF\12\92\11\7FK4\92\13\EDV\15\0D\08C\FF\12\92\11\7FK4\92\13\F1\E6\1C\80T\84@\\\D3\8D\9Bt\00R\11\02qMwn\D8\01HE\08H#\DD\BC\E5\07\14\0C\B5\E4\B5m\07 \15!\10\D7t\F7f\1D\80T\84\804\D2\BD\1B\A2@R\11\02\D2 \93n\9B\A1@R\11\02\D2 \93N\DB\A1@R\11\02\D2 \93^\1F\81R8\91/8\CD\90\DB\D6\1FP0\D4\92\E3\86)\90T\84\804\C8\A4\F7v)\90T\84\804\C8\A4\F3f-@Tu\9F\DB\A9\00Q\D9\FBnl\C4D\F7\B8\C1i\02 M\7FP\D4\FA?9\7Fq\DB\BF\D8\FD\FA\CD\F7<m\87\03JE\08H\83Lu]\1B\E2\80R\11\02\D2 S]\DB\B6E\0C\08C\1B\191 Lm_\C4\800\B6%\0E(\15! \0D2\D5\F5m\85\03JE\08H\83LuM\9B\BF@R\11\02\D2H5\BD\1F\82T8\91/8\CD\E0\0B\0B\014\D4\C3\E3\A7p\14N\E4#\8D`\DF\01HE\08\C45\E1\B5\C9\07 \15! \8D\84\F7\B7p\14N\E4\13\CD`\B8\02De\F3\BBi\0A$\15! \0D2\ED\B4\BD\07 \15!\10\D7\84\EF\B6)\90T\84\804\C8\B4\D7\C6)\90T\84\804\C8\B4\DBV,@TuO\1B\BE@Q\D55\8D\DF\00R8\91\1F8\03f\D0\01FE\08H#\19\DE\00\0C\83\81\1D-\D1HND\DB\AF\80!\00\CB\C2\F3&v\B4D#9\91mj\C4T\F7\B5u\1D-\D1HN\94[\B2\00Q\D9\BDm\F8\01HE\08\C45\E5\B4\B5\11S\DD\EB\C6\1F\80T\84@\\S~\9B\B6\00Q\D9\FDn\96\01\86\00,KM\1Bf\80!\00\CBR\D7\B6*P0\D4\B2\F7\00\011\00\00\B6\00\00\00[\864\08\98-\03\1B\04\CC\96\E1\0D\02f\CB0\07A\B4e\B8\83 \DA2\E0A\10m\19\F2 \88\B6\0C{\100[\86P\08\A2-\83(\04\D1\96\01\15\82h\CB\C0\0AA\B4eh\85 \DA2\B8B\10m\19`!`\B6\0C\B6\10D[\86[\08\A2-C/\04\D1\96!\1C\82h\CB \0EA\B4e\18\87 \DA2\94C\C0l\19\D6!\88\B6\0C\EC\10D[\06y\08\A2-\83=\04\D1\96\E1\1E\82h\CB\80\0FA\B4e\D0\87\80\D92\80D\10m\19B\22\88\B6\0C'\11D[\86\95\08\A2-\03K\04\D1\96\A1%\82h\CB\F0\12\01\B3e\A8\89 \DA2\D8D\10m\19x\22\88\B6\0C`\11D[\86\B0\08\A2-\83X\04\D1\96\81,\02f\CB\A0\16A\B4eX\8B \DA2\B8E\C0l\19\E6\22`\B6\0C\A0\110[\86\D1\08\9C-Ci\04\CE\96\C14\02f\CB0\1B\81\B3e\C8\8D\80\D92\E8F\C0l\19z#`\B6\0C\BE\110[\06\F2\08\98-\C3y\04\CC\96A=\02f\CB\D0\1E\81\B3ex\8F\C0\D92\C0G\C0l\19\FA#p\B6\0C \128[\06\12\09\98-C\89\04\CC\96\01E\02f\CB\90\22\01\B3ex\91\80\D92\C8H\C0l\19n$p\B6\0C:\128[\06\1F\09\98-\C3\8F\04\CC\96AL\02f\CB0&\01\B3eH\93\80\D92\B0I\C0l\19\DE$`\B6\0Cr\128[\06:\09\9C-C\9D\04\CC\96aT\02f\CBP*\01\B3eH\95\80\D92\ACJ\C0l\19X%`\B6\0C\AE\120[\06Y\09\98-\03\AF\04\CC\96\C1W\02f\CB .\01\B3e \97\80\D92\94K\C0l\19\CE%`\B6\0C\EB\120[\86z\09\98-\C3\BD\04\CC\96a_\02f\CB\D0/\01\B3e\F0\97\80\D92\80L\C0l\19H&`\B6\0C+\130[\06\96\09\98-\83\CB\04\CC\96!f\02f\CB 3\01\B3e\A0\99\80\D92\DCL\C0l\19v&p\B6\0C>\138[\06\B1\09\98-\C3\D8\04\CC\96\A1l\02f\CBp6\01\B3eh\9B\80\D92\BCM\C0l\19\E6&p\B6\0Cv\138[\06\BD\09\98-\C3\DE\04\CC\96\81o\02f\CB\E07\01\B3e\F8\9B\80\D92\C8N\E0l\19h'p\B6\0C\BF\138[\86\F0\09\9C-\03\FA\04\CE\96A}\02g\CB\C0>A\B4ep\9F \DA2\C0O\10m\19\E4'\88\B6\0C\F4\13D[\06\FB\09\A2-\03\FE\04\D1\96A\7F\82h\CB\C0?A\B4e\F0\9F \DA2\80P\10m\19D(\88\B6\0C$\14D[\06\13\0A\A2-\03\0A\05\D1\96A\85\82h\CB\C0BA\B4ep\A1 \02\00!1\00\00\08\00\00\00\0B\8E@\00\06\A2 \87\05K \0CDa\00\07\92\FC\C2\02&\10\06\A20\0E\00I\94]\00\00\00\00\00\00a \00\00F\00\00\00\13\04A,\10\00\00\00\04\00\00\00\A4(\04\02\8C\00\CC\00P\A5\06F\00\00\00\003\11\00\10\07\A30\13\01\00q0\0A3\11\00\10\07\A30\13\01\00q0\0A\C3\06\04\B1\0C\C0\B0\011(\03\90\02cG\0C\0C\05\04\C1\A0\A9\03%\A0\020\A8\00\8C\11\03\03\00A0\88\D0@\08\86\0D\08#\18\80,\18;b`( \08\06M\1E8\C1\B0\01a4\03@\07`\8C\18$\00\08\82\01\1B\A8AP5\CC2l@ \C1\00\10\02\18\990v\C4\C0P@\10\0C\9A9\90\82\\\18;b`( \08\06\0D\1DL\C1\0E\E1@\0D\00\00\00V\13\00\07P\10\CD\14a\D6\83\0C\08\E3\03\C3\10\99\CF\01\0CCDH\92\F1\18\80\0F\0CCd6\C3\8006D\08\C0\B2\D8\8F\11\11\12\B5L\00\00\00\00\011\00\00\0A\00\00\00[\06\22p\B6\0CE\E0l\19\90\C0\D92$\81\B3eX\02g\CB\E0\04\CE\96\E1\09\9C-C\148[\06)p\00\00\00\00\00\00\00a \00\00=\00\00\00\13\04A,\10\00\00\00\03\00\00\00\A4(\04\AA\D4\C0\08\00\00\00\00\003\11\00\10\07\A30\13\01\00q0\0A3\11\00\10\07\A30\13\01\00q0\0A\C3\06\04\A1\0C\C0\B0\011$\030l@\08\C8\00d\C0\D8\11\03C\01A0h\E8\00\09\A8\00\0C*\00c\C4\C0\00@\10\0C\A23\10\82a\03\A2\08\06\80\0A\C0\A0\030F\0C\12\00\04\C1\C0\0D\D0@\08(f\C9\83\B1#\06\86\02\82`\D0\C0\81\13h8\10\0E\00\00\00V\13\00\07P\10\CD\14a\C6\83\0C\08\E3\03\C3\10\D9\CDP\01\8B\F9\1C\C00D\84$\D9\8E\01\F8\C00Df3\0C\08c=H\05,>0\0C\91\09\11\02\B0,\00\00\011\00\00\09\00\00\00[\06\22p\B6\0CE\E0l\19\8C\C0\D92$\81\B3eP\02g\CB\C0\04\CE\96\A1\09\9C-\83\138\00\00\00\00\00\00\00a \00\00?\00\00\00\13\04A,\10\00\00\00\03\00\00\00\A4(\04\AA\D4\C0\08\00\00\00\00\003\11\00\10\07\A30\13\01\00q0\0A3\11\00\10\07\A30\13\01\00q0\0A\C3\06\04\A1\0C\C0\B0\011$\030l@\08\C8\00d\C0\D8\11\03C\01A0h\E8\00\09\A8\00\0C*\00c\C4\C0\00@\10\0C\A23\10\82\0B\22\186 \8C`\00\C8\00\0CB\00c\C4 \01@\10\0C\DC \0D\84\A0j\98D\18;b`( \08\06M\1C<\81\86\03\01\00\0F\00\00\00V\13\00\07P\10\CD\14a\C6\83\0C\08\E3\03\C3\10\D9\CDP\01\8B\F9\1C\C00D\84$\D9\D0\00\0C\83\ED\18\80\0F\0CCd6\C3\800\D6\83T\C0\E2\03\C3\10\99\10!\00\CB\02\00\011\00\00\09\00\00\00[\06\22p\B6\0CE\E0l\19\8C\C0\D92$\81\B3eP\02g\CB\D0\04\CE\96\C1\09\9C-\C3\138\00\00\00\00\00\00\00a \00\00\8B\00\00\00\13\04A,\10\00\00\00\0A\00\00\00\F4\19\01\A0E9\10`\04\80*50\02@\80\02$\A8\81\02$\8F)@\CE\80\02\A4%,(@pC\05\00\00\00\003\11\1F\10\07\A90\13\F1\01q\90\0A3\11\1F\10\07\A90\13\F1\01q\90\0A\C3\06\04\11%\C0\B0\011@\09\90\02cG\0C\0C\05\04\C1\A0\D9\83)\186 \06(\01R`\EC\88\81\A1\80 \184|@\05\C3\06\C4\10%\00\19\9F\0CD|2\8C\18(\00\08\82\01\1C\B0\81 E\01\F4\0C\1B\10F\90\00\94|2\D0\F1\C90b\A0\00 \08\06p\F0\06B\15\05\934l@$A\02P\F2\C9@\CA'\C3\88\81\02\80 \18\C8A\1C\08\93\14X\D5\B0\01\C1\04\09@\CC'\035\9F\0C#\06\0A\00\82` \07s XT\90a\C3\06\C4\13$\00E\9F\0C\14}2\8C\18(\00\08\82\01\1C\E0\81\E0u\01\B7\0D\1B\10S\90\00D}2\10\F5\C90b\A0\00 \08\06p\B0\07B\18t\C1\E7\0D\1B\10V\90\00d}2\90\F5\C90b\A0\00 \08\06r\D0\07\C2\C7\05b\10\06\C3\06\04\16$\00e\9F\0C\94}2\8C\18(\00\08\82\81\1C\80\82 \06^P\06d0l@lA\02\D0\F6\C9\90\1CcG\0C\0C\05\04\C1\A0a\057\08\D2c\EC\88\81\A1\80 \184\AD\F0\06\C1\0E\E1@\00\09\00\00\00&t\\\B4\0F\0CCt\00\05\D1L\11fC\C7U\FB\C00DF\14LV#\\\B4\D9\08WmE\01\06\00\011\00\00 \00\00\00[\06\22`\B6\0CE\C0l\19\90\80\D92,\01\B3e`\02f\CB\D0\04\CC\96\E1\09\98-\03\140[\86(`\B6\0CS\C0l\19\A8\80\D92T\01\B3e\B8\02f\CB\80\05\CC\96!\0B\98-\C3\160[\06.`\B6\0C]\C0l\19\BE\80\D92\80A\C0l\19\C2 `\B6\0Cc\100[\062\08\98-C\19\04\CC\96\E1\0C\02f\CB\80\06\01\B3eH\83\80\D92\ACA\C0l\19\D8 `\00\00\00\00\00a \00\00\CF\00\00\00\13\04A,\10\00\00\003\00\00\00\A4(@\04\02\14 \02UF\00\080\02@\8B\12 \DD\0C\00Uj\80\88c\81\02\10\08\03Q\18\07\92(\0B\D38\0F\14I\13UY\17\96i\1B\D7y\1F\18\84\81\18\8C\01\19\94\81\19\9C\01\1A\A4\81\1A\AC\01\1B\B4\81\1B\BC\01\1C\C4\81\1C\CC\01\1D\D4\81\1D\DC\01\1E\E4\81\1E\EC\01\1F\F4\81\1F\FC\C1X\A0\00\0A\A1 \0A\A3@\0A\A5`\0A\A7\80\0A\A9\A0\0A\AB\C0\0A\AD\E0\0A\AF\00\0B\B1 \0B\B3@\0B\B5`\0B\B7\80\0B\B9\A0\0B\BB\C0\0B\BD\E0\0B\BF\00\0E\E1 \0E\E3@\0E\E5`\0E\E7\80\0E\E9\A0\0E\EB\C0\0E\ED\E0\0E\EF\00\0F\F1 \0F\F3@\0F\F5`\0F\F7\80\0F\F9\A0\0F\FB\C0\0F\FD\E0\0F\FF@\A4\19\00\00\00\F10\00\00\03\00\00\00\13\04\85\0E6\18\08\D4@P\03\003\11\1C\10\07\A90\13A\07@\1C\A4\C2L\04\19\00q\90\0A3\11d\00\C4A*\CCD\D0\01\10\07\A90\13A\06@\1C\A4\C2L\04\19\00q\90\0A\C3\06\C4!%@\1A\8C\1D10\14\10\04\83\A6\0F\A4 \0D\C6\8E\18\18\0A\08\82A\E3\07S\90\06cG\0C\0C\05\04\C1\A0\F9\03*H\83\B1#\06\86\02\82`\D0\80B\15\D0\C2\C9\90\C1gG\0C\8C\05\04\C1\C0\0E\DA \09\92al*\8C\1D1@\18\10\04\03<p\03!\C0\AE\\\18;b`( \08\06\CD\1EhA.\8C\1D10\14\10\04\83\C6\14\B6\A0\D3\06\08\C3(\F8d\C8\80\B3#\06\0A\00\82`\B0\07r\10h[\86q\83\0C\81\86\0D2\08\1B6\DB\80\09\C0lC \04\C3\06\04\15$@^\8C\CD\8A\B1#\06\08\03\82`\80\07z \04d0\06i1v\C4\C0P@\10\0C\9AS0\83 -\C6\8E\18\18\0A\08\82A#\0Bg\10t\DA\C0\91A\1BP\F0\C9\90\01gG\0C\14\00\04\C1`\0F\FC 0\833(\032@\83A\86\C0\0C\C8`\90A8\032\98m \03\01\98m\08\84`\D8\80\F8\82\04H1`l\82\01cG\0C\10\06\04\C1\00\0FLA\08\E0\E0\0D2\0C\18;b`( \08\06\CD,\C8A\D0I\83\19\BC\C1\1BP\80\C9\D0I\83\1D\C4A\1C\0C\1B\10\81\90\00\9D4\A0\81\1C\C8\01\05\98\0C\9D4\E4\01\1D\F4\C1\B0\01\11\08\09\90k\C0\D8\11\03C\01A0ht!\0F\82l\03\C6\8E\18\18\0A\08\82A\B3\0Bz\10\E4\1B0v\C4\C0P@\10\0C\1A^\D8\83@\C3\81\00\14\00\00\00\16d\\>0\0C\91\19\11\13\F3\D4vDL\CCs\DB\90P\D1F$T\B5y\09\95mE\C3\C4<\07P\10\CD\14a&\14Lf\13\\&5T\B5miCU\E3V\A3\00\86\E1G\84D-\93\AD\0DU\9D\1B\DBP\D5\BA\B9\0D\95\BD\03\00\00\011\00\00\0D\00\00\00[\86#`\B6\0CP\C0l\19\AA\02\DA2l\01\B3e(\83\02\DA2\ACA\C0l\19\EA\A0\80\B6\0Cy\100[\86=\08\98-C\1F\04\CC\96\E1\0F\02\06\00\00\00\00\00a \00\00D\00\00\00\13\04A,\10\00\00\00\03\00\00\00\A4(\04\02\14\\\01B\14HA\003\11\00\10\07\A30\13\01\00q0\0A3\11\00\10\07\A30l@\0C\CA\00\0C\1B\10B2\00\190v\C4\C0P@\10\0C\1A:H\02\22\00\E3\82D.\09\E0\82\04\E8\00\8C\0B\14\B9!\80a\03\22\09\06\80\12\C0H\85\B1#\06\86\02\82`\D0\CC\81\14\AC\10\0E\04\00\10\00\00\00VD0\D4b[M\00X\0F2 \8C\0F\0CCd>\070\0C\11!I&4\00\C3`<\06\E0\03\C3\10Y\D0\C0P\CB\01\14D3E\98\D9\0C\03\C2\D8\10\01\0CCmF\040\0C7\00\00\00\011\00\00\07\00\00\00[\86!p\B6\0CD\E0l\19\8E\C0\D92,\81\B3ep\02g\CB\F0\04\0E\00\00\00!1\00\00\0B\00\00\00\0B\D2\80(\80@\18\8C\03I\94\85i\9C\07\8A\A4\89\AA\B0\EC\D2\AC\8D\EB\BC\0F\0C\C2@\0C\C6\80\0C\CA\C0\0C\CE\E0\0E\00\00\00\00\00\00\00\00a \00\00\C1\00\00\00\13\04A,\10\00\00\00\0A\00\00\00\A4(@\04\02\8C\00\D4@\F9Q\A5\06F\00\08P\80\E0\DE\0D\05\88<k@\8Br\A0\CF\08\00\01\0A\90\00\00\00\00\003\11\1F\10\07\A90\13A\07@\1C\A4\C2\B0\01!8\09\90\01cG\0C\0C\05\04\C1\A0\C9\03'\A0\E1\93\A1\D3\86\C1q(\F8d\181P\00\10\04\039 \83\E1q\82\86\E9\B4\C1\88\A2a\03\22\10\12\80\90O\86N\1B\90I\A3\E0\93a\C4@\01@\10\0C\E4\C0\0D\06\0A\0A\A4\A8\D3\86\C5\EA\86\0D\88@H\80N\1B\98\EB\A2\E0\93\A1\D3\06'\03\03\0A>\19F\0C\14\00\04\C1@\0E\E8`\D0\AA\00\BB:m\88\B81\186 \02!\01:m\90:2\A0\E0\93a\C4@\01@\10\0C\E0@\0E\02\EC\BB\B8\AD\D3\861\00\030\186 \02!\01:m\B0\C2\00\0D(\F8d\181P\00\10\04\038\B0\83\80\D360\F8:m8\032X\83a\03\22\10\12 5\C6\8E\18\18\0A\08\82A\83\0Ag\10h8\10\14\00\00\00\965T6oB\C6\E5\03\C3\10\19\D7P\D9\BDa\0DU\BD\9B\91P\D5\B6$T\F6\01\14D3E\98\0D\05\93\D9\04\97%\0DU]\9B\D3P\D9\B6=\0DU}[\8D\02\18\86\1F\11\12\B5LF5TvnUCe\EB\165T6\0E\00\00\00\011\00\00\0F\00\00\00[\06!`\B6\0CE\C0l\19\8E\80\D92(\01\B3eX\02f\CB\D0\04\CC\96\01\0A\98-\83\140[\06*`\B6\0CW\C0l\19\B2\80\D92p\01\B3e\F0\02f\CB\10\06\01\03\00!1\00\00Q\00\00\00\0B\E8\00X\02a \0A\E3@\12\85i\9C\07\8A\A4\89\AA\AC\0B\CB\B4\AD\F3\C0 \0C\C4`\0C\CA\C0\0C\CE\00\0D\D2@\0D\D6\80\0D\DA\C0\0D\DE\00\0E\E2@\0E\C8\E0\E3\AC\05t\00,\810\10\85q \89\C24\CE\03E\D2DU\D6\85e\DA\C6u\DE\07\06a \06c@\06e`\06g\80\06i\A0\06k\C0\06m\E0\06o\00\07q \07\CC\02\9D\00\02a \0A\E3@\C0 \0C\C4 Q\16\A6q\1E(\92&\AA\B2.,\D36\AE\F3\BE1 \8320\833@\834P\835`\836p\837\80\838\90\839\A0\83:\B0\83;\C0\83<\D8\03>\08\85RH\85Vp\85W\80\05Y\98\05[\B8\05]\D8\85^\F0\85q \87r0\87s@\87tP\87u`\87w\80\87x\90\87y\B0\87{\C0\87|\D0\87~\F0\87\7F\00\89\90 \89\920\89\93@\89\94P\89\95`\09\97\80\89\98\90\89\99\A0\09=\E8\03?\F8\03P\10\85Q \05S8\05TP\85U`\85X\A0\85Z\C0\85\\\E0\85_\00\87p\10\87vp\07z\A8\87}\E0\07\91\18\89\96x\89\9A\B0\89\9B\C0\898\00\00\00\00\00\00\00q \00\00\09\00\00\002\0E\10\22\84\0B\B8\08\F8\00L\81\10\88\15(q\\\81\15\88\16\88Qy\81\1B\E6\18\18\C2\9A\01\00\00\00\00\00\00\00e\0C\00\00\FD\00\00\00\12\03\94\E8\07\00\00\00\02\00\00\000\03\00\00/\00\00\00L\00\00\00\01\00\00\00X\00\00\00\00\00\00\00X\00\00\00&\00\00\00\E8\03\00\00\00\00\00\00_\03\00\00\03\00\00\00b\03\00\00\0F\00\00\00\13\00\00\00\00\00\00\00\E8\03\00\00\00\00\00\00\00\00\00\00&\00\00\00\00\00\00\00~\00\00\00\04\00\00\00~\00\00\00\04\00\00\00\FF\FF\FF\FF\00$\00\00\82\00\00\00\18\00\00\00\82\00\00\00\18\00\00\00\FF\FF\FF\FF\08,\00\00\9A\00\00\00\1F\00\00\00\9A\00\00\00\1F\00\00\00\FF\FF\FF\FF\08,\00\00\B9\00\00\00\1D\00\00\00\B9\00\00\00\1D\00\00\00\FF\FF\FF\FF\08,\00\00\D6\00\00\00\0C\00\00\00\D6\00\00\00\0C\00\00\00\FF\FF\FF\FF\08$\00\00\E2\00\00\00\0C\00\00\00\E2\00\00\00\0C\00\00\00\FF\FF\FF\FF\08$\00\00\EE\00\00\00\1B\00\00\00\EE\00\00\00\1B\00\00\00\FF\FF\FF\FF\08,\00\00\09\01\00\00\0E\00\00\00\09\01\00\00\0E\00\00\00\FF\FF\FF\FF\08$\00\00\17\01\00\00\1A\00\00\00\17\01\00\00\1A\00\00\00\FF\FF\FF\FF\08,\00\001\01\00\00#\00\00\001\01\00\00#\00\00\00\FF\FF\FF\FF\08,\00\00T\01\00\00\1C\00\00\00T\01\00\00\1C\00\00\00\FF\FF\FF\FF\08$\00\00p\01\00\00\16\00\00\00p\01\00\00\16\00\00\00\FF\FF\FF\FF\08,\00\00\86\01\00\00*\00\00\00\86\01\00\00*\00\00\00\FF\FF\FF\FF\08,\00\00\B0\01\00\00\1A\00\00\00\B0\01\00\00\1A\00\00\00\FF\FF\FF\FF\08$\00\00\CA\01\00\00\17\00\00\00\CA\01\00\00\17\00\00\00\FF\FF\FF\FF\08,\00\00\E1\01\00\00\19\00\00\00\E1\01\00\00\19\00\00\00\FF\FF\FF\FF\08,\00\00\FA\01\00\00\1C\00\00\00\FA\01\00\00\1C\00\00\00\FF\FF\FF\FF\08$\00\00\16\02\00\00\11\00\00\00\16\02\00\00\11\00\00\00\FF\FF\FF\FF\08,\00\00'\02\00\00\11\00\00\00'\02\00\00\11\00\00\00\FF\FF\FF\FF\08,\00\008\02\00\00\18\00\00\008\02\00\00\18\00\00\00\FF\FF\FF\FF\08,\00\00P\02\00\00&\00\00\00P\02\00\00&\00\00\00\FF\FF\FF\FF\08,\00\00v\02\00\00\22\00\00\00v\02\00\00\22\00\00\00\FF\FF\FF\FF\08,\00\00\98\02\00\00\1C\00\00\00\98\02\00\00\1C\00\00\00\FF\FF\FF\FF\08$\00\00\B4\02\00\00\19\00\00\00\B4\02\00\00\19\00\00\00\FF\FF\FF\FF\08,\00\00\CD\02\00\00$\00\00\00\CD\02\00\00$\00\00\00\FF\FF\FF\FF\08,\00\00\F1\02\00\00%\00\00\00\F1\02\00\00%\00\00\00\FF\FF\FF\FF\08,\00\00\16\03\00\00\1A\00\00\00\16\03\00\00\1A\00\00\00\FF\FF\FF\FF\08,\00\00\00\00\00\00\13\00\00\00\00\00\00\00\13\00\00\00\FF\FF\FF\FF\00\04\00\00\13\00\00\00\0D\00\00\00\13\00\00\00\0D\00\00\00\FF\FF\FF\FF\00\04\00\00 \00\00\00\0E\00\00\00 \00\00\00\0E\00\00\00\FF\FF\FF\FF\00\04\00\00.\00\00\00\0D\00\00\00.\00\00\00\0D\00\00\00\FF\FF\FF\FF\00\04\00\00;\00\00\00\0D\00\00\00;\00\00\00\0D\00\00\00\FF\FF\FF\FF\00\04\00\00H\00\00\00\0E\00\00\00H\00\00\00\0E\00\00\00\FF\FF\FF\FF\00\04\00\00V\00\00\00\12\00\00\00V\00\00\00\12\00\00\00\FF\FF\FF\FF\00\04\00\00h\00\00\00\07\00\00\00h\00\00\00\07\00\00\00\FF\FF\FF\FF\00\04\00\00o\00\00\00\05\00\00\00o\00\00\00\05\00\00\00\FF\FF\FF\FF\00\04\00\00t\00\00\00\05\00\00\00t\00\00\00\05\00\00\00\FF\FF\FF\FF\00\04\00\00y\00\00\00\05\00\00\00y\00\00\00\05\00\00\00\FF\FF\FF\FF\00\04\00\00\00\00\00\00]\0C\00\00\E0\00\00\00\12\03\94\F1\06\00\00\00__PrintfTensorIndexPLUS_ONE_BF16MINUS_ONE_BF16PLUS_NAN_BF16PLUS_INF_BF16MINUS_INF_BF16sin_accuracy_limitfour_pipi4_1pi4_2pi4_3mainllvm.lifetime.start.p0i8llvm.tpc.get.index.space.offsetllvm.tpc.get.index.space.sizeget_dim_sizeset_dim_sizellvm.tpc.min.i32.i32.i32.i1set_dim_stridellvm.tpc.ld.tnsr.v64f32.i1llvm.tpc.convert.v128bf16.v64f32.i1cast_32bits_to_i16_lin_orderllvm.lifetime.end.p0i8llvm.tpc.add.v128bf16.v128bf16.v128bf16.i1cast_bf16_to_f32_lin_orderllvm.tpc.st.tnsr.v64f32llvm.tpc.st.tnsr.v128bf16get_dim_size_offset_internalllvm.tpc.ld.l.i32llvm.tpc.st.l.i32llvm.tpc.pack.v128i16.i1llvm.tpc.mov.dual.group.all.v128i16.i1llvm.tpc.mov.dual.group.v128i16.i1cast_i16_to_32bits_lin_orderllvm.memcpy.p0i8.p0i8.i32llvm.tpc.convert.v128f32.v128bf16.i1llvm.tpc.mov.group.v128i16.v128i16.i1llvm.tpc.unpack.v128i16.i110.0.1 dc18ecd58013a5cbeeb9da4f73dac2351d74c5b3tpctrunc-ext-D3P.c\00\00\00\00\00\00\00", section ".llvmbc"
@llvm.compiler.used = appending global [1 x i8*] [i8* getelementptr inbounds ([15728 x i8], [15728 x i8]* @llvm.embedded.module, i32 0, i32 0)], section "llvm.metadata"

; Function Attrs: nounwind
define dso_local void @main() local_unnamed_addr #0 {
; CHECK-LABEL: @main(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = tail call <5 x i32> @llvm.tpc.get.index.space.offset()
; CHECK-NEXT:    [[TMP1:%.*]] = tail call <5 x i32> @llvm.tpc.get.index.space.size()
; CHECK-NEXT:    [[ADD:%.*]] = add <5 x i32> [[TMP1]], [[TMP0]]
; CHECK-NEXT:    [[TMP2:%.*]] = tail call i32 @llvm.tpc.ld.l.i32(i32 1040, i32 1, i32 undef, i1 true, i1 false) #4
; CHECK-NEXT:    [[TMP3:%.*]] = tail call i32 @llvm.tpc.ld.l.i32(i32 1048, i32 1, i32 undef, i1 true, i1 false) #4
; CHECK-NEXT:    [[MUL:%.*]] = mul i32 [[TMP3]], [[TMP2]]
; CHECK-NEXT:    [[VECEXT:%.*]] = extractelement <5 x i32> [[ADD]], i32 1
; CHECK-NEXT:    [[MUL2:%.*]] = mul nsw i32 [[VECEXT]], 126
; CHECK-NEXT:    [[TMP4:%.*]] = icmp slt i32 [[MUL]], [[MUL2]]
; CHECK-NEXT:    [[TMP5:%.*]] = select i1 [[TMP4]], i32 [[MUL]], i32 [[MUL2]]
; CHECK-NEXT:    tail call void @llvm.tpc.st.l.i32(i32 1040, i32 [[TMP5]], i32 1, i1 true, i1 false) #4
; CHECK-NEXT:    tail call void @llvm.tpc.st.l.i32(i32 1048, i32 1, i32 1, i1 true, i1 false) #4
; CHECK-NEXT:    tail call void @llvm.tpc.st.l.i32(i32 1052, i32 [[MUL]], i32 1, i1 true, i1 false) #4
; CHECK-NEXT:    [[TMP6:%.*]] = tail call i32 @llvm.tpc.ld.l.i32(i32 1096, i32 1, i32 undef, i1 true, i1 false) #4
; CHECK-NEXT:    [[TMP7:%.*]] = tail call i32 @llvm.tpc.ld.l.i32(i32 1104, i32 1, i32 undef, i1 true, i1 false) #4
; CHECK-NEXT:    [[MUL6:%.*]] = mul i32 [[TMP7]], [[TMP6]]
; CHECK-NEXT:    [[TMP8:%.*]] = icmp slt i32 [[MUL6]], [[MUL2]]
; CHECK-NEXT:    [[TMP9:%.*]] = select i1 [[TMP8]], i32 [[MUL6]], i32 [[MUL2]]
; CHECK-NEXT:    tail call void @llvm.tpc.st.l.i32(i32 1096, i32 [[TMP9]], i32 1, i1 true, i1 false) #4
; CHECK-NEXT:    tail call void @llvm.tpc.st.l.i32(i32 1104, i32 1, i32 1, i1 true, i1 false) #4
; CHECK-NEXT:    tail call void @llvm.tpc.st.l.i32(i32 1108, i32 [[MUL6]], i32 1, i1 true, i1 false) #4
; CHECK-NEXT:    [[TMP10:%.*]] = tail call i32 @llvm.tpc.ld.l.i32(i32 1152, i32 1, i32 undef, i1 true, i1 false) #4
; CHECK-NEXT:    [[TMP11:%.*]] = tail call i32 @llvm.tpc.ld.l.i32(i32 1160, i32 1, i32 undef, i1 true, i1 false) #4
; CHECK-NEXT:    [[MUL12:%.*]] = mul i32 [[TMP11]], [[TMP10]]
; CHECK-NEXT:    [[TMP12:%.*]] = icmp slt i32 [[MUL12]], [[MUL2]]
; CHECK-NEXT:    [[TMP13:%.*]] = select i1 [[TMP12]], i32 [[MUL12]], i32 [[MUL2]]
; CHECK-NEXT:    tail call void @llvm.tpc.st.l.i32(i32 1152, i32 [[TMP13]], i32 1, i1 true, i1 false) #4
; CHECK-NEXT:    tail call void @llvm.tpc.st.l.i32(i32 1160, i32 1, i32 1, i1 true, i1 false) #4
; CHECK-NEXT:    tail call void @llvm.tpc.st.l.i32(i32 1164, i32 [[MUL12]], i32 1, i1 true, i1 false) #4
; CHECK-NEXT:    [[TMP14:%.*]] = tail call i32 @llvm.tpc.ld.l.i32(i32 1208, i32 1, i32 undef, i1 true, i1 false) #4
; CHECK-NEXT:    [[TMP15:%.*]] = tail call i32 @llvm.tpc.ld.l.i32(i32 1216, i32 1, i32 undef, i1 true, i1 false) #4
; CHECK-NEXT:    [[MUL18:%.*]] = mul i32 [[TMP15]], [[TMP14]]
; CHECK-NEXT:    [[TMP16:%.*]] = icmp slt i32 [[MUL18]], [[MUL2]]
; CHECK-NEXT:    [[TMP17:%.*]] = select i1 [[TMP16]], i32 [[MUL18]], i32 [[MUL2]]
; CHECK-NEXT:    tail call void @llvm.tpc.st.l.i32(i32 1208, i32 [[TMP17]], i32 1, i1 true, i1 false) #4
; CHECK-NEXT:    tail call void @llvm.tpc.st.l.i32(i32 1216, i32 1, i32 1, i1 true, i1 false) #4
; CHECK-NEXT:    tail call void @llvm.tpc.st.l.i32(i32 1220, i32 [[MUL18]], i32 1, i1 true, i1 false) #4
; CHECK-NEXT:    [[TMP18:%.*]] = tail call i32 @llvm.tpc.ld.l.i32(i32 1264, i32 1, i32 undef, i1 true, i1 false) #4
; CHECK-NEXT:    [[TMP19:%.*]] = tail call i32 @llvm.tpc.ld.l.i32(i32 1272, i32 1, i32 undef, i1 true, i1 false) #4
; CHECK-NEXT:    [[MUL24:%.*]] = mul i32 [[TMP19]], [[TMP18]]
; CHECK-NEXT:    [[TMP20:%.*]] = icmp slt i32 [[MUL24]], [[MUL2]]
; CHECK-NEXT:    [[TMP21:%.*]] = select i1 [[TMP20]], i32 [[MUL24]], i32 [[MUL2]]
; CHECK-NEXT:    tail call void @llvm.tpc.st.l.i32(i32 1264, i32 [[TMP21]], i32 1, i1 true, i1 false) #4
; CHECK-NEXT:    tail call void @llvm.tpc.st.l.i32(i32 1272, i32 1, i32 1, i1 true, i1 false) #4
; CHECK-NEXT:    tail call void @llvm.tpc.st.l.i32(i32 1276, i32 [[MUL24]], i32 1, i1 true, i1 false) #4
; CHECK-NEXT:    [[TMP22:%.*]] = tail call i32 @llvm.tpc.ld.l.i32(i32 1320, i32 1, i32 undef, i1 true, i1 false) #4
; CHECK-NEXT:    [[TMP23:%.*]] = tail call i32 @llvm.tpc.ld.l.i32(i32 1328, i32 1, i32 undef, i1 true, i1 false) #4
; CHECK-NEXT:    [[MUL30:%.*]] = mul i32 [[TMP23]], [[TMP22]]
; CHECK-NEXT:    [[TMP24:%.*]] = icmp slt i32 [[MUL30]], [[MUL2]]
; CHECK-NEXT:    [[TMP25:%.*]] = select i1 [[TMP24]], i32 [[MUL30]], i32 [[MUL2]]
; CHECK-NEXT:    tail call void @llvm.tpc.st.l.i32(i32 1320, i32 [[TMP25]], i32 1, i1 true, i1 false) #4
; CHECK-NEXT:    tail call void @llvm.tpc.st.l.i32(i32 1328, i32 1, i32 1, i1 true, i1 false) #4
; CHECK-NEXT:    tail call void @llvm.tpc.st.l.i32(i32 1332, i32 [[MUL30]], i32 1, i1 true, i1 false) #4
; CHECK-NEXT:    [[VECEXT34:%.*]] = extractelement <5 x i32> [[TMP0]], i32 1
; CHECK-NEXT:    [[MUL40:%.*]] = mul nsw i32 [[VECEXT34]], 126
; CHECK-NEXT:    [[CMP240:%.*]] = icmp slt i32 [[MUL40]], [[MUL2]]
; CHECK-NEXT:    br i1 [[CMP240]], label [[FOR_BODY_LR_PH:%.*]], label [[FOR_COND_CLEANUP:%.*]]
; CHECK:       for.body.lr.ph:
; CHECK-NEXT:    [[VECEXT50:%.*]] = extractelement <5 x i32> [[TMP0]], i32 2
; CHECK-NEXT:    [[VECEXT53:%.*]] = extractelement <5 x i32> [[ADD]], i32 2
; CHECK-NEXT:    [[CMP55238:%.*]] = icmp slt i32 [[VECEXT50]], [[VECEXT53]]
; CHECK-NEXT:    br label [[FOR_BODY:%.*]]
; CHECK:       for.cond.cleanup.loopexit:
; CHECK-NEXT:    br label [[FOR_COND_CLEANUP]]
; CHECK:       for.cond.cleanup:
; CHECK-NEXT:    tail call void @llvm.tpc.st.l.i32(i32 1040, i32 [[TMP2]], i32 1, i1 true, i1 false) #4
; CHECK-NEXT:    tail call void @llvm.tpc.st.l.i32(i32 1048, i32 [[TMP3]], i32 1, i1 true, i1 false) #4
; CHECK-NEXT:    tail call void @llvm.tpc.st.l.i32(i32 1052, i32 [[TMP3]], i32 1, i1 true, i1 false) #4
; CHECK-NEXT:    tail call void @llvm.tpc.st.l.i32(i32 1096, i32 [[TMP6]], i32 1, i1 true, i1 false) #4
; CHECK-NEXT:    tail call void @llvm.tpc.st.l.i32(i32 1104, i32 [[TMP7]], i32 1, i1 true, i1 false) #4
; CHECK-NEXT:    tail call void @llvm.tpc.st.l.i32(i32 1108, i32 [[TMP7]], i32 1, i1 true, i1 false) #4
; CHECK-NEXT:    tail call void @llvm.tpc.st.l.i32(i32 1152, i32 [[TMP10]], i32 1, i1 true, i1 false) #4
; CHECK-NEXT:    tail call void @llvm.tpc.st.l.i32(i32 1160, i32 [[TMP11]], i32 1, i1 true, i1 false) #4
; CHECK-NEXT:    tail call void @llvm.tpc.st.l.i32(i32 1164, i32 [[TMP11]], i32 1, i1 true, i1 false) #4
; CHECK-NEXT:    tail call void @llvm.tpc.st.l.i32(i32 1208, i32 [[TMP14]], i32 1, i1 true, i1 false) #4
; CHECK-NEXT:    tail call void @llvm.tpc.st.l.i32(i32 1216, i32 [[TMP15]], i32 1, i1 true, i1 false) #4
; CHECK-NEXT:    tail call void @llvm.tpc.st.l.i32(i32 1220, i32 [[TMP15]], i32 1, i1 true, i1 false) #4
; CHECK-NEXT:    tail call void @llvm.tpc.st.l.i32(i32 1264, i32 [[TMP18]], i32 1, i1 true, i1 false) #4
; CHECK-NEXT:    tail call void @llvm.tpc.st.l.i32(i32 1272, i32 [[TMP19]], i32 1, i1 true, i1 false) #4
; CHECK-NEXT:    tail call void @llvm.tpc.st.l.i32(i32 1276, i32 [[TMP19]], i32 1, i1 true, i1 false) #4
; CHECK-NEXT:    tail call void @llvm.tpc.st.l.i32(i32 1320, i32 [[TMP22]], i32 1, i1 true, i1 false) #4
; CHECK-NEXT:    tail call void @llvm.tpc.st.l.i32(i32 1328, i32 [[TMP23]], i32 1, i1 true, i1 false) #4
; CHECK-NEXT:    tail call void @llvm.tpc.st.l.i32(i32 1332, i32 [[TMP23]], i32 1, i1 true, i1 false) #4
; CHECK-NEXT:    ret void
; CHECK:       for.body:
; CHECK-NEXT:    [[DIM0_0241:%.*]] = phi i32 [ [[MUL40]], [[FOR_BODY_LR_PH]] ], [ [[ADD119:%.*]], [[FOR_COND_CLEANUP56:%.*]] ]
; CHECK-NEXT:    [[VECINIT43:%.*]] = insertelement <5 x i32> <i32 undef, i32 0, i32 undef, i32 undef, i32 undef>, i32 [[DIM0_0241]], i32 0
; CHECK-NEXT:    [[VECINIT46:%.*]] = shufflevector <5 x i32> [[VECINIT43]], <5 x i32> <i32 undef, i32 undef, i32 0, i32 0, i32 0>, <5 x i32> <i32 0, i32 1, i32 7, i32 8, i32 9>
; CHECK-NEXT:    [[TMP26:%.*]] = tail call <64 x float> @llvm.tpc.ld.tnsr.v64f32.i1(<5 x i32> [[VECINIT46]], i8 0, i32 0, <64 x float> undef, i1 true, i1 false)
; CHECK-NEXT:    [[TMP27:%.*]] = tail call <5 x i32> @llvm.tpc.add.mask.v5i32.i32(<5 x i32> [[VECINIT46]], i32 64, i32 1, i8 2, i32 0, <5 x i32> [[VECINIT46]], i1 true, i1 false)
; CHECK-NEXT:    [[TMP28:%.*]] = tail call <64 x float> @llvm.tpc.ld.tnsr.v64f32.i1(<5 x i32> [[TMP27]], i8 0, i32 0, <64 x float> undef, i1 true, i1 false)
; CHECK-NEXT:    br i1 [[CMP55238]], label [[FOR_BODY57_LR_PH:%.*]], label [[FOR_COND_CLEANUP56]]
; CHECK:       for.body57.lr.ph:
; CHECK-NEXT:    [[TMP29:%.*]] = shufflevector <5 x i32> [[VECINIT43]], <5 x i32> <i32 undef, i32 undef, i32 undef, i32 0, i32 0>, <5 x i32> <i32 0, i32 1, i32 undef, i32 8, i32 9>
; CHECK-NEXT:    [[IN_SROA_0_0_VEC_EXPAND:%.*]] = shufflevector <64 x float> [[TMP26]], <64 x float> undef, <128 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>
; CHECK-NEXT:    [[IN_SROA_0_256_VEC_EXPAND:%.*]] = shufflevector <64 x float> [[TMP28]], <64 x float> undef, <128 x i32> <i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
; CHECK-NEXT:    [[IN_SROA_0_256_VECBLEND:%.*]] = shufflevector <128 x float> [[IN_SROA_0_256_VEC_EXPAND]], <128 x float> [[IN_SROA_0_0_VEC_EXPAND]], <128 x i32> <i32 128, i32 129, i32 130, i32 131, i32 132, i32 133, i32 134, i32 135, i32 136, i32 137, i32 138, i32 139, i32 140, i32 141, i32 142, i32 143, i32 144, i32 145, i32 146, i32 147, i32 148, i32 149, i32 150, i32 151, i32 152, i32 153, i32 154, i32 155, i32 156, i32 157, i32 158, i32 159, i32 160, i32 161, i32 162, i32 163, i32 164, i32 165, i32 166, i32 167, i32 168, i32 169, i32 170, i32 171, i32 172, i32 173, i32 174, i32 175, i32 176, i32 177, i32 178, i32 179, i32 180, i32 181, i32 182, i32 183, i32 184, i32 185, i32 186, i32 187, i32 188, i32 189, i32 190, i32 191, i32 64, i32 65, i32 66, i32 67, i32 68, i32 69, i32 70, i32 71, i32 72, i32 73, i32 74, i32 75, i32 76, i32 77, i32 78, i32 79, i32 80, i32 81, i32 82, i32 83, i32 84, i32 85, i32 86, i32 87, i32 88, i32 89, i32 90, i32 91, i32 92, i32 93, i32 94, i32 95, i32 96, i32 97, i32 98, i32 99, i32 100, i32 101, i32 102, i32 103, i32 104, i32 105, i32 106, i32 107, i32 108, i32 109, i32 110, i32 111, i32 112, i32 113, i32 114, i32 115, i32 116, i32 117, i32 118, i32 119, i32 120, i32 121, i32 122, i32 123, i32 124, i32 125, i32 126, i32 127>
; CHECK-NEXT:    [[TMP30:%.*]] = call <128 x bfloat> @llvm.tpc.convert.v128bf16.v128f32.i1(<128 x float> [[IN_SROA_0_256_VECBLEND]], i8 0, i32 327940, <128 x bfloat> undef, i1 true, i1 false)
; CHECK-NEXT:    br label [[FOR_BODY57:%.*]]
; CHECK:       for.cond.cleanup56.loopexit:
; CHECK-NEXT:    br label [[FOR_COND_CLEANUP56]]
; CHECK:       for.cond.cleanup56:
; CHECK-NEXT:    [[ADD119]] = add nsw i32 [[DIM0_0241]], 126
; CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[ADD119]], [[MUL2]]
; CHECK-NEXT:    br i1 [[CMP]], label [[FOR_BODY]], label [[FOR_COND_CLEANUP_LOOPEXIT:%.*]]
; CHECK:       for.body57:
; CHECK-NEXT:    [[DIM2_0239:%.*]] = phi i32 [ [[VECEXT50]], [[FOR_BODY57_LR_PH]] ], [ [[ADD116:%.*]], [[FOR_BODY57]] ]
; CHECK-NEXT:    [[VECINIT62:%.*]] = insertelement <5 x i32> [[TMP29]], i32 [[DIM2_0239]], i32 2
; CHECK-NEXT:    [[TMP31:%.*]] = tail call <64 x float> @llvm.tpc.ld.tnsr.v64f32.i1(<5 x i32> [[VECINIT62]], i8 1, i32 0, <64 x float> undef, i1 true, i1 false)
; CHECK-NEXT:    [[TMP32:%.*]] = tail call <5 x i32> @llvm.tpc.add.mask.v5i32.i32(<5 x i32> [[VECINIT62]], i32 64, i32 1, i8 2, i32 0, <5 x i32> [[VECINIT62]], i1 true, i1 false)
; CHECK-NEXT:    [[TMP33:%.*]] = tail call <64 x float> @llvm.tpc.ld.tnsr.v64f32.i1(<5 x i32> [[TMP32]], i8 1, i32 0, <64 x float> undef, i1 true, i1 false)
; CHECK-NEXT:    [[TMP34:%.*]] = tail call <64 x float> @llvm.tpc.ld.tnsr.v64f32.i1(<5 x i32> [[VECINIT62]], i8 2, i32 0, <64 x float> undef, i1 true, i1 false)
; CHECK-NEXT:    [[TMP35:%.*]] = tail call <64 x float> @llvm.tpc.ld.tnsr.v64f32.i1(<5 x i32> [[TMP32]], i8 2, i32 0, <64 x float> undef, i1 true, i1 false)
; CHECK-NEXT:    [[IN_SROA_0_0_VEC_EXPAND1:%.*]] = shufflevector <64 x float> [[TMP31]], <64 x float> undef, <128 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>
; CHECK-NEXT:    [[IN_SROA_0_256_VEC_EXPAND1:%.*]] = shufflevector <64 x float> [[TMP33]], <64 x float> undef, <128 x i32> <i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
; CHECK-NEXT:    [[IN_SROA_0_256_VECBLEND1:%.*]] = shufflevector <128 x float> [[IN_SROA_0_256_VEC_EXPAND1]], <128 x float> [[IN_SROA_0_0_VEC_EXPAND1]], <128 x i32> <i32 128, i32 129, i32 130, i32 131, i32 132, i32 133, i32 134, i32 135, i32 136, i32 137, i32 138, i32 139, i32 140, i32 141, i32 142, i32 143, i32 144, i32 145, i32 146, i32 147, i32 148, i32 149, i32 150, i32 151, i32 152, i32 153, i32 154, i32 155, i32 156, i32 157, i32 158, i32 159, i32 160, i32 161, i32 162, i32 163, i32 164, i32 165, i32 166, i32 167, i32 168, i32 169, i32 170, i32 171, i32 172, i32 173, i32 174, i32 175, i32 176, i32 177, i32 178, i32 179, i32 180, i32 181, i32 182, i32 183, i32 184, i32 185, i32 186, i32 187, i32 188, i32 189, i32 190, i32 191, i32 64, i32 65, i32 66, i32 67, i32 68, i32 69, i32 70, i32 71, i32 72, i32 73, i32 74, i32 75, i32 76, i32 77, i32 78, i32 79, i32 80, i32 81, i32 82, i32 83, i32 84, i32 85, i32 86, i32 87, i32 88, i32 89, i32 90, i32 91, i32 92, i32 93, i32 94, i32 95, i32 96, i32 97, i32 98, i32 99, i32 100, i32 101, i32 102, i32 103, i32 104, i32 105, i32 106, i32 107, i32 108, i32 109, i32 110, i32 111, i32 112, i32 113, i32 114, i32 115, i32 116, i32 117, i32 118, i32 119, i32 120, i32 121, i32 122, i32 123, i32 124, i32 125, i32 126, i32 127>
; CHECK-NEXT:    [[TMP36:%.*]] = call <128 x bfloat> @llvm.tpc.convert.v128bf16.v128f32.i1(<128 x float> [[IN_SROA_0_256_VECBLEND1]], i8 0, i32 327940, <128 x bfloat> undef, i1 true, i1 false)
; CHECK-NEXT:    [[IN_SROA_0_0_VEC_EXPAND2:%.*]] = shufflevector <64 x float> [[TMP34]], <64 x float> undef, <128 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>
; CHECK-NEXT:    [[IN_SROA_0_256_VEC_EXPAND2:%.*]] = shufflevector <64 x float> [[TMP35]], <64 x float> undef, <128 x i32> <i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
; CHECK-NEXT:    [[IN_SROA_0_256_VECBLEND2:%.*]] = shufflevector <128 x float> [[IN_SROA_0_256_VEC_EXPAND2]], <128 x float> [[IN_SROA_0_0_VEC_EXPAND2]], <128 x i32> <i32 128, i32 129, i32 130, i32 131, i32 132, i32 133, i32 134, i32 135, i32 136, i32 137, i32 138, i32 139, i32 140, i32 141, i32 142, i32 143, i32 144, i32 145, i32 146, i32 147, i32 148, i32 149, i32 150, i32 151, i32 152, i32 153, i32 154, i32 155, i32 156, i32 157, i32 158, i32 159, i32 160, i32 161, i32 162, i32 163, i32 164, i32 165, i32 166, i32 167, i32 168, i32 169, i32 170, i32 171, i32 172, i32 173, i32 174, i32 175, i32 176, i32 177, i32 178, i32 179, i32 180, i32 181, i32 182, i32 183, i32 184, i32 185, i32 186, i32 187, i32 188, i32 189, i32 190, i32 191, i32 64, i32 65, i32 66, i32 67, i32 68, i32 69, i32 70, i32 71, i32 72, i32 73, i32 74, i32 75, i32 76, i32 77, i32 78, i32 79, i32 80, i32 81, i32 82, i32 83, i32 84, i32 85, i32 86, i32 87, i32 88, i32 89, i32 90, i32 91, i32 92, i32 93, i32 94, i32 95, i32 96, i32 97, i32 98, i32 99, i32 100, i32 101, i32 102, i32 103, i32 104, i32 105, i32 106, i32 107, i32 108, i32 109, i32 110, i32 111, i32 112, i32 113, i32 114, i32 115, i32 116, i32 117, i32 118, i32 119, i32 120, i32 121, i32 122, i32 123, i32 124, i32 125, i32 126, i32 127>
; CHECK-NEXT:    [[TMP37:%.*]] = call <128 x bfloat> @llvm.tpc.convert.v128bf16.v128f32.i1(<128 x float> [[IN_SROA_0_256_VECBLEND2]], i8 0, i32 327940, <128 x bfloat> undef, i1 true, i1 false)
; CHECK-NEXT:    [[TMP38:%.*]] = fadd <128 x bfloat> [[TMP30]], [[TMP36]]
; CHECK-NEXT:    [[TMP39:%.*]] = fadd <128 x bfloat> [[TMP38]], [[TMP37]]
; CHECK-NEXT:    [[TMP40:%.*]] = call <128 x float> @llvm.tpc.convert.v128f32.v128bf16.i1(<128 x bfloat> [[TMP39]], i8 1, i32 327680, <128 x float> undef, i1 true, i1 false)
; CHECK-NEXT:    [[TMP_SHUF_1:%.*]] = shufflevector <128 x float> [[TMP40]], <128 x float> undef, <64 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
; CHECK-NEXT:    [[TMP_SHUF_2:%.*]] = shufflevector <128 x float> [[TMP40]], <128 x float> undef, <64 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
; CHECK-NEXT:    tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> [[VECINIT62]], i8 3, <64 x float> [[TMP_SHUF_1]], i32 0, i1 true, i1 false)
; CHECK-NEXT:    tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> [[TMP32]], i8 3, <64 x float> [[TMP_SHUF_2]], i32 0, i1 true, i1 false)
; CHECK-NEXT:    tail call void @llvm.tpc.st.tnsr.v128bf16(<5 x i32> [[VECINIT62]], i8 4, <128 x bfloat> [[TMP39]], i32 4, i1 true, i1 false)
; CHECK-NEXT:    tail call void @llvm.tpc.st.tnsr.v128bf16(<5 x i32> [[VECINIT62]], i8 5, <128 x bfloat> [[TMP37]], i32 4, i1 true, i1 false)
; CHECK-NEXT:    [[ADD116]] = add i32 [[DIM2_0239]], 1
; CHECK-NEXT:    [[EXITCOND:%.*]] = icmp eq i32 [[ADD116]], [[VECEXT53]]
; CHECK-NEXT:    br i1 [[EXITCOND]], label [[FOR_COND_CLEANUP56_LOOPEXIT:%.*]], label [[FOR_BODY57]]
;
entry:
  %0 = tail call <5 x i32> @llvm.tpc.get.index.space.offset()
  %1 = tail call <5 x i32> @llvm.tpc.get.index.space.size()
  %add = add <5 x i32> %1, %0
  %2 = tail call i32 @llvm.tpc.ld.l.i32(i32 1040, i32 1, i32 undef, i1 true, i1 false) #4
  %3 = tail call i32 @llvm.tpc.ld.l.i32(i32 1048, i32 1, i32 undef, i1 true, i1 false) #4
  %mul = mul i32 %3, %2
  %vecext = extractelement <5 x i32> %add, i32 1
  %mul2 = mul nsw i32 %vecext, 126
  %4 = icmp slt i32 %mul, %mul2
  %5 = select i1 %4, i32 %mul, i32 %mul2
  tail call void @llvm.tpc.st.l.i32(i32 1040, i32 %5, i32 1, i1 true, i1 false) #4
  tail call void @llvm.tpc.st.l.i32(i32 1048, i32 1, i32 1, i1 true, i1 false) #4
  tail call void @llvm.tpc.st.l.i32(i32 1052, i32 %mul, i32 1, i1 true, i1 false) #4
  %6 = tail call i32 @llvm.tpc.ld.l.i32(i32 1096, i32 1, i32 undef, i1 true, i1 false) #4
  %7 = tail call i32 @llvm.tpc.ld.l.i32(i32 1104, i32 1, i32 undef, i1 true, i1 false) #4
  %mul6 = mul i32 %7, %6
  %8 = icmp slt i32 %mul6, %mul2
  %9 = select i1 %8, i32 %mul6, i32 %mul2
  tail call void @llvm.tpc.st.l.i32(i32 1096, i32 %9, i32 1, i1 true, i1 false) #4
  tail call void @llvm.tpc.st.l.i32(i32 1104, i32 1, i32 1, i1 true, i1 false) #4
  tail call void @llvm.tpc.st.l.i32(i32 1108, i32 %mul6, i32 1, i1 true, i1 false) #4
  %10 = tail call i32 @llvm.tpc.ld.l.i32(i32 1152, i32 1, i32 undef, i1 true, i1 false) #4
  %11 = tail call i32 @llvm.tpc.ld.l.i32(i32 1160, i32 1, i32 undef, i1 true, i1 false) #4
  %mul12 = mul i32 %11, %10
  %12 = icmp slt i32 %mul12, %mul2
  %13 = select i1 %12, i32 %mul12, i32 %mul2
  tail call void @llvm.tpc.st.l.i32(i32 1152, i32 %13, i32 1, i1 true, i1 false) #4
  tail call void @llvm.tpc.st.l.i32(i32 1160, i32 1, i32 1, i1 true, i1 false) #4
  tail call void @llvm.tpc.st.l.i32(i32 1164, i32 %mul12, i32 1, i1 true, i1 false) #4
  %14 = tail call i32 @llvm.tpc.ld.l.i32(i32 1208, i32 1, i32 undef, i1 true, i1 false) #4
  %15 = tail call i32 @llvm.tpc.ld.l.i32(i32 1216, i32 1, i32 undef, i1 true, i1 false) #4
  %mul18 = mul i32 %15, %14
  %16 = icmp slt i32 %mul18, %mul2
  %17 = select i1 %16, i32 %mul18, i32 %mul2
  tail call void @llvm.tpc.st.l.i32(i32 1208, i32 %17, i32 1, i1 true, i1 false) #4
  tail call void @llvm.tpc.st.l.i32(i32 1216, i32 1, i32 1, i1 true, i1 false) #4
  tail call void @llvm.tpc.st.l.i32(i32 1220, i32 %mul18, i32 1, i1 true, i1 false) #4
  %18 = tail call i32 @llvm.tpc.ld.l.i32(i32 1264, i32 1, i32 undef, i1 true, i1 false) #4
  %19 = tail call i32 @llvm.tpc.ld.l.i32(i32 1272, i32 1, i32 undef, i1 true, i1 false) #4
  %mul24 = mul i32 %19, %18
  %20 = icmp slt i32 %mul24, %mul2
  %21 = select i1 %20, i32 %mul24, i32 %mul2
  tail call void @llvm.tpc.st.l.i32(i32 1264, i32 %21, i32 1, i1 true, i1 false) #4
  tail call void @llvm.tpc.st.l.i32(i32 1272, i32 1, i32 1, i1 true, i1 false) #4
  tail call void @llvm.tpc.st.l.i32(i32 1276, i32 %mul24, i32 1, i1 true, i1 false) #4
  %22 = tail call i32 @llvm.tpc.ld.l.i32(i32 1320, i32 1, i32 undef, i1 true, i1 false) #4
  %23 = tail call i32 @llvm.tpc.ld.l.i32(i32 1328, i32 1, i32 undef, i1 true, i1 false) #4
  %mul30 = mul i32 %23, %22
  %24 = icmp slt i32 %mul30, %mul2
  %25 = select i1 %24, i32 %mul30, i32 %mul2
  tail call void @llvm.tpc.st.l.i32(i32 1320, i32 %25, i32 1, i1 true, i1 false) #4
  tail call void @llvm.tpc.st.l.i32(i32 1328, i32 1, i32 1, i1 true, i1 false) #4
  tail call void @llvm.tpc.st.l.i32(i32 1332, i32 %mul30, i32 1, i1 true, i1 false) #4
  %vecext34 = extractelement <5 x i32> %0, i32 1
  %mul40 = mul nsw i32 %vecext34, 126
  %cmp240 = icmp slt i32 %mul40, %mul2
  br i1 %cmp240, label %for.body.lr.ph, label %for.cond.cleanup

for.body.lr.ph:                                   ; preds = %entry
  %vecext50 = extractelement <5 x i32> %0, i32 2
  %vecext53 = extractelement <5 x i32> %add, i32 2
  %cmp55238 = icmp slt i32 %vecext50, %vecext53
  br label %for.body

for.cond.cleanup.loopexit:                        ; preds = %for.cond.cleanup56
  br label %for.cond.cleanup

for.cond.cleanup:                                 ; preds = %for.cond.cleanup.loopexit, %entry
  tail call void @llvm.tpc.st.l.i32(i32 1040, i32 %2, i32 1, i1 true, i1 false) #4
  tail call void @llvm.tpc.st.l.i32(i32 1048, i32 %3, i32 1, i1 true, i1 false) #4
  tail call void @llvm.tpc.st.l.i32(i32 1052, i32 %3, i32 1, i1 true, i1 false) #4
  tail call void @llvm.tpc.st.l.i32(i32 1096, i32 %6, i32 1, i1 true, i1 false) #4
  tail call void @llvm.tpc.st.l.i32(i32 1104, i32 %7, i32 1, i1 true, i1 false) #4
  tail call void @llvm.tpc.st.l.i32(i32 1108, i32 %7, i32 1, i1 true, i1 false) #4
  tail call void @llvm.tpc.st.l.i32(i32 1152, i32 %10, i32 1, i1 true, i1 false) #4
  tail call void @llvm.tpc.st.l.i32(i32 1160, i32 %11, i32 1, i1 true, i1 false) #4
  tail call void @llvm.tpc.st.l.i32(i32 1164, i32 %11, i32 1, i1 true, i1 false) #4
  tail call void @llvm.tpc.st.l.i32(i32 1208, i32 %14, i32 1, i1 true, i1 false) #4
  tail call void @llvm.tpc.st.l.i32(i32 1216, i32 %15, i32 1, i1 true, i1 false) #4
  tail call void @llvm.tpc.st.l.i32(i32 1220, i32 %15, i32 1, i1 true, i1 false) #4
  tail call void @llvm.tpc.st.l.i32(i32 1264, i32 %18, i32 1, i1 true, i1 false) #4
  tail call void @llvm.tpc.st.l.i32(i32 1272, i32 %19, i32 1, i1 true, i1 false) #4
  tail call void @llvm.tpc.st.l.i32(i32 1276, i32 %19, i32 1, i1 true, i1 false) #4
  tail call void @llvm.tpc.st.l.i32(i32 1320, i32 %22, i32 1, i1 true, i1 false) #4
  tail call void @llvm.tpc.st.l.i32(i32 1328, i32 %23, i32 1, i1 true, i1 false) #4
  tail call void @llvm.tpc.st.l.i32(i32 1332, i32 %23, i32 1, i1 true, i1 false) #4
  ret void

for.body:                                         ; preds = %for.body.lr.ph, %for.cond.cleanup56
  %dim0.0241 = phi i32 [ %mul40, %for.body.lr.ph ], [ %add119, %for.cond.cleanup56 ]
  %vecinit43 = insertelement <5 x i32> <i32 undef, i32 0, i32 undef, i32 undef, i32 undef>, i32 %dim0.0241, i32 0
  %vecinit46 = shufflevector <5 x i32> %vecinit43, <5 x i32> <i32 undef, i32 undef, i32 0, i32 0, i32 0>, <5 x i32> <i32 0, i32 1, i32 7, i32 8, i32 9>
  %26 = tail call <64 x float> @llvm.tpc.ld.tnsr.v64f32.i1(<5 x i32> %vecinit46, i8 0, i32 0, <64 x float> undef, i1 true, i1 false)
  %27 = tail call <5 x i32> @llvm.tpc.add.mask.v5i32.i32(<5 x i32> %vecinit46, i32 64, i32 1, i8 2, i32 0, <5 x i32> %vecinit46, i1 true, i1 false)
  %28 = tail call <64 x float> @llvm.tpc.ld.tnsr.v64f32.i1(<5 x i32> %27, i8 0, i32 0, <64 x float> undef, i1 true, i1 false)
  br i1 %cmp55238, label %for.body57.lr.ph, label %for.cond.cleanup56

for.body57.lr.ph:                                 ; preds = %for.body
  %29 = shufflevector <5 x i32> %vecinit43, <5 x i32> <i32 undef, i32 undef, i32 undef, i32 0, i32 0>, <5 x i32> <i32 0, i32 1, i32 undef, i32 8, i32 9>

  ;; Replacement for 1st fptrunc
  %in.sroa.0.0.vec.expand = shufflevector <64 x float> %26, <64 x float> undef, <128 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>
  ;;
  %in.sroa.0.256.vec.expand = shufflevector <64 x float> %28, <64 x float> undef, <128 x i32> <i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
  ;;
  %in.sroa.0.256.vecblend = shufflevector <128 x float> %in.sroa.0.256.vec.expand, <128 x float> %in.sroa.0.0.vec.expand, <128 x i32> <i32 128, i32 129, i32 130, i32 131, i32 132, i32 133, i32 134, i32 135, i32 136, i32 137, i32 138, i32 139, i32 140, i32 141, i32 142, i32 143, i32 144, i32 145, i32 146, i32 147, i32 148, i32 149, i32 150, i32 151, i32 152, i32 153, i32 154, i32 155, i32 156, i32 157, i32 158, i32 159, i32 160, i32 161, i32 162, i32 163, i32 164, i32 165, i32 166, i32 167, i32 168, i32 169, i32 170, i32 171, i32 172, i32 173, i32 174, i32 175, i32 176, i32 177, i32 178, i32 179, i32 180, i32 181, i32 182, i32 183, i32 184, i32 185, i32 186, i32 187, i32 188, i32 189, i32 190, i32 191, i32 64, i32 65, i32 66, i32 67, i32 68, i32 69, i32 70, i32 71, i32 72, i32 73, i32 74, i32 75, i32 76, i32 77, i32 78, i32 79, i32 80, i32 81, i32 82, i32 83, i32 84, i32 85, i32 86, i32 87, i32 88, i32 89, i32 90, i32 91, i32 92, i32 93, i32 94, i32 95, i32 96, i32 97, i32 98, i32 99, i32 100, i32 101, i32 102, i32 103, i32 104, i32 105, i32 106, i32 107, i32 108, i32 109, i32 110, i32 111, i32 112, i32 113, i32 114, i32 115, i32 116, i32 117, i32 118, i32 119, i32 120, i32 121, i32 122, i32 123, i32 124, i32 125, i32 126, i32 127>
  ;;
  %first.fptrunc = fptrunc <128 x float> %in.sroa.0.256.vecblend to <128 x bfloat16>

  br label %for.body57

for.cond.cleanup56.loopexit:                      ; preds = %for.body57
  br label %for.cond.cleanup56

for.cond.cleanup56:                               ; preds = %for.cond.cleanup56.loopexit, %for.body
  %add119 = add nsw i32 %dim0.0241, 126
  %cmp = icmp slt i32 %add119, %mul2
  br i1 %cmp, label %for.body, label %for.cond.cleanup.loopexit

for.body57:                                       ; preds = %for.body57, %for.body57.lr.ph
  %dim2.0239 = phi i32 [ %vecext50, %for.body57.lr.ph ], [ %add116, %for.body57 ]
  %vecinit62 = insertelement <5 x i32> %29, i32 %dim2.0239, i32 2
  %30 = tail call <64 x float> @llvm.tpc.ld.tnsr.v64f32.i1(<5 x i32> %vecinit62, i8 1, i32 0, <64 x float> undef, i1 true, i1 false)
  %31 = tail call <5 x i32> @llvm.tpc.add.mask.v5i32.i32(<5 x i32> %vecinit62, i32 64, i32 1, i8 2, i32 0, <5 x i32> %vecinit62, i1 true, i1 false)
  %32 = tail call <64 x float> @llvm.tpc.ld.tnsr.v64f32.i1(<5 x i32> %31, i8 1, i32 0, <64 x float> undef, i1 true, i1 false)
  %33 = tail call <64 x float> @llvm.tpc.ld.tnsr.v64f32.i1(<5 x i32> %vecinit62, i8 2, i32 0, <64 x float> undef, i1 true, i1 false)
  %34 = tail call <64 x float> @llvm.tpc.ld.tnsr.v64f32.i1(<5 x i32> %31, i8 2, i32 0, <64 x float> undef, i1 true, i1 false)

  ;; Replacement for 2nd fptrunc
  %in.sroa.0.0.vec.expand1 = shufflevector <64 x float> %30, <64 x float> undef, <128 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>
  ;;
  %in.sroa.0.256.vec.expand1 = shufflevector <64 x float> %32, <64 x float> undef, <128 x i32> <i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
  ;;
  %in.sroa.0.256.vecblend1 = shufflevector <128 x float> %in.sroa.0.256.vec.expand1, <128 x float> %in.sroa.0.0.vec.expand1, <128 x i32> <i32 128, i32 129, i32 130, i32 131, i32 132, i32 133, i32 134, i32 135, i32 136, i32 137, i32 138, i32 139, i32 140, i32 141, i32 142, i32 143, i32 144, i32 145, i32 146, i32 147, i32 148, i32 149, i32 150, i32 151, i32 152, i32 153, i32 154, i32 155, i32 156, i32 157, i32 158, i32 159, i32 160, i32 161, i32 162, i32 163, i32 164, i32 165, i32 166, i32 167, i32 168, i32 169, i32 170, i32 171, i32 172, i32 173, i32 174, i32 175, i32 176, i32 177, i32 178, i32 179, i32 180, i32 181, i32 182, i32 183, i32 184, i32 185, i32 186, i32 187, i32 188, i32 189, i32 190, i32 191, i32 64, i32 65, i32 66, i32 67, i32 68, i32 69, i32 70, i32 71, i32 72, i32 73, i32 74, i32 75, i32 76, i32 77, i32 78, i32 79, i32 80, i32 81, i32 82, i32 83, i32 84, i32 85, i32 86, i32 87, i32 88, i32 89, i32 90, i32 91, i32 92, i32 93, i32 94, i32 95, i32 96, i32 97, i32 98, i32 99, i32 100, i32 101, i32 102, i32 103, i32 104, i32 105, i32 106, i32 107, i32 108, i32 109, i32 110, i32 111, i32 112, i32 113, i32 114, i32 115, i32 116, i32 117, i32 118, i32 119, i32 120, i32 121, i32 122, i32 123, i32 124, i32 125, i32 126, i32 127>
  ;;
  %second.fptrunc = fptrunc <128 x float> %in.sroa.0.256.vecblend1 to <128 x bfloat16>

  ;; Replacement for 2nd fptrunc
  %in.sroa.0.0.vec.expand2 = shufflevector <64 x float> %33, <64 x float> undef, <128 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>
  ;;
  %in.sroa.0.256.vec.expand2 = shufflevector <64 x float> %34, <64 x float> undef, <128 x i32> <i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
  ;;
  %in.sroa.0.256.vecblend2 = shufflevector <128 x float> %in.sroa.0.256.vec.expand2, <128 x float> %in.sroa.0.0.vec.expand2, <128 x i32> <i32 128, i32 129, i32 130, i32 131, i32 132, i32 133, i32 134, i32 135, i32 136, i32 137, i32 138, i32 139, i32 140, i32 141, i32 142, i32 143, i32 144, i32 145, i32 146, i32 147, i32 148, i32 149, i32 150, i32 151, i32 152, i32 153, i32 154, i32 155, i32 156, i32 157, i32 158, i32 159, i32 160, i32 161, i32 162, i32 163, i32 164, i32 165, i32 166, i32 167, i32 168, i32 169, i32 170, i32 171, i32 172, i32 173, i32 174, i32 175, i32 176, i32 177, i32 178, i32 179, i32 180, i32 181, i32 182, i32 183, i32 184, i32 185, i32 186, i32 187, i32 188, i32 189, i32 190, i32 191, i32 64, i32 65, i32 66, i32 67, i32 68, i32 69, i32 70, i32 71, i32 72, i32 73, i32 74, i32 75, i32 76, i32 77, i32 78, i32 79, i32 80, i32 81, i32 82, i32 83, i32 84, i32 85, i32 86, i32 87, i32 88, i32 89, i32 90, i32 91, i32 92, i32 93, i32 94, i32 95, i32 96, i32 97, i32 98, i32 99, i32 100, i32 101, i32 102, i32 103, i32 104, i32 105, i32 106, i32 107, i32 108, i32 109, i32 110, i32 111, i32 112, i32 113, i32 114, i32 115, i32 116, i32 117, i32 118, i32 119, i32 120, i32 121, i32 122, i32 123, i32 124, i32 125, i32 126, i32 127>
  ;;
  %third.fptrunc = fptrunc <128 x float> %in.sroa.0.256.vecblend2 to <128 x bfloat16>


  %35 = fadd <128 x bfloat16> %first.fptrunc, %second.fptrunc
  %36 = fadd <128 x bfloat16> %35, %third.fptrunc

  %tmp.ext = fpext <128 x bfloat16> %36 to <128 x float>
  %tmp.shuf.1 = shufflevector <128 x float> %tmp.ext, <128 x float> undef, <64 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
  %tmp.shuf.2 = shufflevector <128 x float> %tmp.ext, <128 x float> undef, <64 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>


  tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> %vecinit62, i8 3, <64 x float> %tmp.shuf.1, i32 0, i1 true, i1 false)
  tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> %31, i8 3, <64 x float> %tmp.shuf.2, i32 0, i1 true, i1 false)
  tail call void @llvm.tpc.st.tnsr.v128bf16(<5 x i32> %vecinit62, i8 4, <128 x bfloat16> %36, i32 0, i1 true, i1 false)
  tail call void @llvm.tpc.st.tnsr.v128bf16(<5 x i32> %vecinit62, i8 5, <128 x bfloat16> %third.fptrunc, i32 0, i1 true, i1 false)
  %add116 = add i32 %dim2.0239, 1
  %exitcond = icmp eq i32 %add116, %vecext53
  br i1 %exitcond, label %for.cond.cleanup56.loopexit, label %for.body57
}

; Function Attrs: nounwind readnone
declare <5 x i32> @llvm.tpc.get.index.space.offset() #1

; Function Attrs: nounwind readnone
declare <5 x i32> @llvm.tpc.get.index.space.size() #1

; Function Attrs: nounwind readnone
declare <64 x float> @llvm.tpc.ld.tnsr.v64f32.i1(<5 x i32>, i8, i32, <64 x float>, i1, i1) #1

; Function Attrs: nounwind readnone
declare <128 x bfloat16> @llvm.tpc.convert.v128bf16.v64f32.i1(<64 x float>, i8, i32, <128 x bfloat16>, i1, i1) #1

; Function Attrs: nounwind writeonly
declare void @llvm.tpc.st.tnsr.v64f32(<5 x i32>, i8, <64 x float>, i32, i1, i1) #2

; Function Attrs: nounwind writeonly
declare void @llvm.tpc.st.tnsr.v128bf16(<5 x i32>, i8, <128 x bfloat16>, i32, i1, i1) #2

; Function Attrs: nounwind readonly
declare i32 @llvm.tpc.ld.l.i32(i32, i32, i32, i1, i1) #3

; Function Attrs: nounwind writeonly
declare void @llvm.tpc.st.l.i32(i32, i32, i32, i1, i1) #2

; Function Attrs: nounwind readnone
declare <128 x i16> @llvm.tpc.pack.v128i16.i1(<128 x i16>, i8, i32, <128 x i16>, i1, i1) #1

; Function Attrs: nounwind readnone
declare <128 x i16> @llvm.tpc.mov.dual.group.all.v128i16.i1(<128 x i16>, i32, i32, <128 x i16>, i1, i1) #1

; Function Attrs: nounwind readnone
declare <128 x i16> @llvm.tpc.mov.dual.group.v128i16.i1(<128 x i16>, i32, i32, <128 x i16>, i1, i1) #1

; Function Attrs: nounwind readnone
declare <128 x float> @llvm.tpc.convert.v128f32.v128bf16.i1(<128 x bfloat16>, i8, i32, <128 x float>, i1, i1) #1

; Function Attrs: nounwind readnone
declare <128 x i16> @llvm.tpc.mov.group.v128i16.v128i16.i1(<128 x i16>, i32, i32, <128 x i16>, i1, i1) #1

; Function Attrs: nounwind readnone
declare <128 x i16> @llvm.tpc.unpack.v128i16.i1(<128 x i16>, i8, i32, <128 x i16>, i1, i1) #1

; Function Attrs: nounwind readnone
declare <5 x i32> @llvm.tpc.add.mask.v5i32.i32(<5 x i32>, i32, i32, i8, i32, <5 x i32>, i1, i1) #1

attributes #0 = { nounwind "correctly-rounded-divide-sqrt-fp-math"="false" "disable-tail-calls"="false" "frame-pointer"="all" "less-precise-fpmad"="false" "min-legal-vector-width"="2048" "no-infs-fp-math"="false" "no-jump-tables"="false" "no-nans-fp-math"="false" "no-signed-zeros-fp-math"="false" "no-trapping-math"="false" "stack-protector-buffer-size"="8" "target-cpu"="gaudi" "target-features"="+gaudi" "unsafe-fp-math"="false" "use-soft-float"="false" }
attributes #1 = { nounwind readnone }
attributes #2 = { nounwind writeonly }
attributes #3 = { nounwind readonly }
attributes #4 = { nounwind }

!llvm.module.flags = !{!0}
!llvm.ident = !{!1}
!llvm.tpc.scalar_data = !{!2}
!llvm.tpc.vector_data = !{!2}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{!"clang version 10.0.1 (ssh://gerrit:29418/tpc_llvm10 dc18ecd58013a5cbeeb9da4f73dac2351d74c5b3)"}
!2 = !{i32 0}
