; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
;RUN: opt < %s -cast-swizzle-opt -S | FileCheck %s
;XFAIL:*

; ModuleID = 'result.O3.bc'
source_filename = "LLVMDialectModule"

; Function Attrs: nounwind readnone
declare <64 x float> @llvm.tpc.ld.tnsr.v64f32.i1(<5 x i32>, i8, i32, <64 x float>, i1, i1) #0

; Function Attrs: nounwind writeonly
declare void @llvm.tpc.st.tnsr.v64f32(<5 x i32>, i8, <64 x float>, i32, i1, i1) #1

; Function Attrs: nounwind readnone
declare <128 x bfloat> @llvm.tpc.fptrunc.swch.v128bf16.v128f32(<128 x float>, i32) #0

; Function Attrs: nounwind readnone
declare <128 x float> @llvm.tpc.fpext.swch.v128f32.v128bf16(<128 x bfloat>, i32) #0

; Function Attrs: nounwind readnone
declare i8 addrspace(3)* @llvm.tpc.gen.addr(<5 x i32>, i8, i32, i8 addrspace(3)*, i1, i1) #0

; Function Attrs: nounwind readnone
declare <5 x i32> @llvm.tpc.get.index.space.offset() #0

; Function Attrs: nounwind readnone
declare <5 x i32> @llvm.tpc.get.index.space.size() #0

; Function Attrs: nounwind
define void @main() local_unnamed_addr #2 {
; CHECK-LABEL: @main(
; CHECK-NEXT:    [[TMP1:%.*]] = tail call <5 x i32> @llvm.tpc.get.index.space.offset()
; CHECK-NEXT:    [[TMP2:%.*]] = tail call <5 x i32> @llvm.tpc.get.index.space.size()
; CHECK-NEXT:    [[TMP3:%.*]] = add <5 x i32> [[TMP2]], [[TMP1]]
; CHECK-NEXT:    [[TMP4:%.*]] = extractelement <5 x i32> [[TMP1]], i32 1
; CHECK-NEXT:    [[TMP5:%.*]] = extractelement <5 x i32> [[TMP3]], i32 1
; CHECK-NEXT:    [[TMP6:%.*]] = tail call i8 addrspace(3)* @llvm.tpc.gen.addr(<5 x i32> zeroinitializer, i8 1, i32 0, i8 addrspace(3)* undef, i1 true, i1 false)
; CHECK-NEXT:    [[TMP7:%.*]] = tail call <128 x bfloat> @llvm.tpc.ld.g.v128bf16.i1(i8 addrspace(3)* [[TMP6]], i32 0, <128 x bfloat> undef, i1 true, i1 false)
; CHECK-NEXT:    [[TMP8:%.*]] = icmp slt i32 [[TMP4]], [[TMP5]]
; CHECK-NEXT:    br i1 [[TMP8]], label [[DOTLR_PH:%.*]], label [[DOT_CRIT_EDGE:%.*]]
; CHECK:       .lr.ph:
; CHECK-NEXT:    [[TMP9:%.*]] = phi i32 [ [[TMP74:%.*]], [[DOTLR_PH]] ], [ [[TMP4]], [[TMP0:%.*]] ]
; CHECK-NEXT:    [[DOTSROA_013_022:%.*]] = phi <5 x i32> [ [[DOTSROA_013_0_VEC_INSERT_7:%.*]], [[DOTLR_PH]] ], [ zeroinitializer, [[TMP0]] ]
; CHECK-NEXT:    [[DOTSROA_07_021:%.*]] = phi <5 x i32> [ [[DOTSROA_07_0_VEC_INSERT_7:%.*]], [[DOTLR_PH]] ], [ zeroinitializer, [[TMP0]] ]
; CHECK-NEXT:    [[DOTSROA_09_020:%.*]] = phi <5 x i32> [ [[DOTSROA_09_0_VEC_INSERT_7:%.*]], [[DOTLR_PH]] ], [ zeroinitializer, [[TMP0]] ]
; CHECK-NEXT:    [[DOTSROA_011_019:%.*]] = phi <5 x i32> [ [[DOTSROA_011_0_VEC_INSERT_7:%.*]], [[DOTLR_PH]] ], [ zeroinitializer, [[TMP0]] ]
; CHECK-NEXT:    [[DOTSROA_013_4_VEC_INSERT:%.*]] = insertelement <5 x i32> [[DOTSROA_013_022]], i32 [[TMP9]], i32 1
; CHECK-NEXT:    [[DOTSROA_011_4_VEC_INSERT:%.*]] = insertelement <5 x i32> [[DOTSROA_011_019]], i32 [[TMP9]], i32 1
; CHECK-NEXT:    [[DOTSROA_09_4_VEC_INSERT:%.*]] = insertelement <5 x i32> [[DOTSROA_09_020]], i32 [[TMP9]], i32 1
; CHECK-NEXT:    [[DOTSROA_07_4_VEC_INSERT:%.*]] = insertelement <5 x i32> [[DOTSROA_07_021]], i32 [[TMP9]], i32 1
; CHECK-NEXT:    [[DOTSROA_07_0_VEC_INSERT:%.*]] = shufflevector <5 x i32> <i32 0, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> [[DOTSROA_07_4_VEC_INSERT]], <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
; CHECK-NEXT:    [[TMP10:%.*]] = tail call <64 x float> @llvm.tpc.ld.tnsr.v64f32.i1(<5 x i32> [[DOTSROA_07_0_VEC_INSERT]], i8 0, i32 0, <64 x float> undef, i1 true, i1 false)
; CHECK-NEXT:    [[DOTSROA_09_0_VEC_INSERT:%.*]] = shufflevector <5 x i32> <i32 64, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> [[DOTSROA_09_4_VEC_INSERT]], <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
; CHECK-NEXT:    [[TMP11:%.*]] = tail call <64 x float> @llvm.tpc.ld.tnsr.v64f32.i1(<5 x i32> [[DOTSROA_09_0_VEC_INSERT]], i8 0, i32 0, <64 x float> undef, i1 true, i1 false)
; CHECK-NEXT:    [[TMP12:%.*]] = shufflevector <64 x float> [[TMP10]], <64 x float> [[TMP11]], <128 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63, i32 64, i32 65, i32 66, i32 67, i32 68, i32 69, i32 70, i32 71, i32 72, i32 73, i32 74, i32 75, i32 76, i32 77, i32 78, i32 79, i32 80, i32 81, i32 82, i32 83, i32 84, i32 85, i32 86, i32 87, i32 88, i32 89, i32 90, i32 91, i32 92, i32 93, i32 94, i32 95, i32 96, i32 97, i32 98, i32 99, i32 100, i32 101, i32 102, i32 103, i32 104, i32 105, i32 106, i32 107, i32 108, i32 109, i32 110, i32 111, i32 112, i32 113, i32 114, i32 115, i32 116, i32 117, i32 118, i32 119, i32 120, i32 121, i32 122, i32 123, i32 124, i32 125, i32 126, i32 127>
; CHECK-NEXT:    [[TMP13:%.*]] = call <128 x bfloat> @llvm.tpc.convert.v128bf16.v128f32.i1(<128 x float> [[TMP12]], i8 0, i32 327940, <128 x bfloat> undef, i1 true, i1 false)
; CHECK-NEXT:    [[TMP14:%.*]] = fmul <128 x bfloat> [[TMP7]], [[TMP13]]
; CHECK-NEXT:    [[TMP15:%.*]] = call <128 x float> @llvm.tpc.convert.v128f32.v128bf16.i1(<128 x bfloat> [[TMP14]], i8 1, i32 327680, <128 x float> undef, i1 true, i1 false)
; CHECK-NEXT:    [[TMP16:%.*]] = shufflevector <128 x float> [[TMP15]], <128 x float> undef, <64 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
; CHECK-NEXT:    [[TMP17:%.*]] = shufflevector <128 x float> [[TMP15]], <128 x float> undef, <64 x i32> <i32 64, i32 65, i32 66, i32 67, i32 68, i32 69, i32 70, i32 71, i32 72, i32 73, i32 74, i32 75, i32 76, i32 77, i32 78, i32 79, i32 80, i32 81, i32 82, i32 83, i32 84, i32 85, i32 86, i32 87, i32 88, i32 89, i32 90, i32 91, i32 92, i32 93, i32 94, i32 95, i32 96, i32 97, i32 98, i32 99, i32 100, i32 101, i32 102, i32 103, i32 104, i32 105, i32 106, i32 107, i32 108, i32 109, i32 110, i32 111, i32 112, i32 113, i32 114, i32 115, i32 116, i32 117, i32 118, i32 119, i32 120, i32 121, i32 122, i32 123, i32 124, i32 125, i32 126, i32 127>
; CHECK-NEXT:    [[DOTSROA_011_0_VEC_INSERT:%.*]] = shufflevector <5 x i32> <i32 0, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> [[DOTSROA_011_4_VEC_INSERT]], <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
; CHECK-NEXT:    tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> [[DOTSROA_011_0_VEC_INSERT]], i8 2, <64 x float> [[TMP16]], i32 0, i1 true, i1 false)
; CHECK-NEXT:    [[DOTSROA_013_0_VEC_INSERT:%.*]] = shufflevector <5 x i32> <i32 64, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> [[DOTSROA_013_4_VEC_INSERT]], <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
; CHECK-NEXT:    tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> [[DOTSROA_013_0_VEC_INSERT]], i8 2, <64 x float> [[TMP17]], i32 0, i1 true, i1 false)
; CHECK-NEXT:    [[DOTSROA_07_0_VEC_INSERT_1:%.*]] = shufflevector <5 x i32> <i32 128, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> [[DOTSROA_07_0_VEC_INSERT]], <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
; CHECK-NEXT:    [[TMP18:%.*]] = tail call <64 x float> @llvm.tpc.ld.tnsr.v64f32.i1(<5 x i32> [[DOTSROA_07_0_VEC_INSERT_1]], i8 0, i32 0, <64 x float> undef, i1 true, i1 false)
; CHECK-NEXT:    [[DOTSROA_09_0_VEC_INSERT_1:%.*]] = shufflevector <5 x i32> <i32 192, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> [[DOTSROA_09_0_VEC_INSERT]], <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
; CHECK-NEXT:    [[TMP19:%.*]] = tail call <64 x float> @llvm.tpc.ld.tnsr.v64f32.i1(<5 x i32> [[DOTSROA_09_0_VEC_INSERT_1]], i8 0, i32 0, <64 x float> undef, i1 true, i1 false)
; CHECK-NEXT:    [[TMP20:%.*]] = shufflevector <64 x float> [[TMP18]], <64 x float> [[TMP19]], <128 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63, i32 64, i32 65, i32 66, i32 67, i32 68, i32 69, i32 70, i32 71, i32 72, i32 73, i32 74, i32 75, i32 76, i32 77, i32 78, i32 79, i32 80, i32 81, i32 82, i32 83, i32 84, i32 85, i32 86, i32 87, i32 88, i32 89, i32 90, i32 91, i32 92, i32 93, i32 94, i32 95, i32 96, i32 97, i32 98, i32 99, i32 100, i32 101, i32 102, i32 103, i32 104, i32 105, i32 106, i32 107, i32 108, i32 109, i32 110, i32 111, i32 112, i32 113, i32 114, i32 115, i32 116, i32 117, i32 118, i32 119, i32 120, i32 121, i32 122, i32 123, i32 124, i32 125, i32 126, i32 127>
; CHECK-NEXT:    [[TMP21:%.*]] = call <128 x bfloat> @llvm.tpc.convert.v128bf16.v128f32.i1(<128 x float> [[TMP20]], i8 0, i32 327940, <128 x bfloat> undef, i1 true, i1 false)
; CHECK-NEXT:    [[TMP22:%.*]] = fmul <128 x bfloat> [[TMP7]], [[TMP21]]
; CHECK-NEXT:    [[TMP23:%.*]] = call <128 x float> @llvm.tpc.convert.v128f32.v128bf16.i1(<128 x bfloat> [[TMP22]], i8 1, i32 327680, <128 x float> undef, i1 true, i1 false)
; CHECK-NEXT:    [[TMP24:%.*]] = shufflevector <128 x float> [[TMP23]], <128 x float> undef, <64 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
; CHECK-NEXT:    [[TMP25:%.*]] = shufflevector <128 x float> [[TMP23]], <128 x float> undef, <64 x i32> <i32 64, i32 65, i32 66, i32 67, i32 68, i32 69, i32 70, i32 71, i32 72, i32 73, i32 74, i32 75, i32 76, i32 77, i32 78, i32 79, i32 80, i32 81, i32 82, i32 83, i32 84, i32 85, i32 86, i32 87, i32 88, i32 89, i32 90, i32 91, i32 92, i32 93, i32 94, i32 95, i32 96, i32 97, i32 98, i32 99, i32 100, i32 101, i32 102, i32 103, i32 104, i32 105, i32 106, i32 107, i32 108, i32 109, i32 110, i32 111, i32 112, i32 113, i32 114, i32 115, i32 116, i32 117, i32 118, i32 119, i32 120, i32 121, i32 122, i32 123, i32 124, i32 125, i32 126, i32 127>
; CHECK-NEXT:    [[DOTSROA_011_0_VEC_INSERT_1:%.*]] = shufflevector <5 x i32> <i32 128, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> [[DOTSROA_011_0_VEC_INSERT]], <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
; CHECK-NEXT:    tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> [[DOTSROA_011_0_VEC_INSERT_1]], i8 2, <64 x float> [[TMP24]], i32 0, i1 true, i1 false)
; CHECK-NEXT:    [[DOTSROA_013_0_VEC_INSERT_1:%.*]] = shufflevector <5 x i32> <i32 192, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> [[DOTSROA_013_0_VEC_INSERT]], <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
; CHECK-NEXT:    tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> [[DOTSROA_013_0_VEC_INSERT_1]], i8 2, <64 x float> [[TMP25]], i32 0, i1 true, i1 false)
; CHECK-NEXT:    [[DOTSROA_07_0_VEC_INSERT_2:%.*]] = shufflevector <5 x i32> <i32 256, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> [[DOTSROA_07_0_VEC_INSERT_1]], <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
; CHECK-NEXT:    [[TMP26:%.*]] = tail call <64 x float> @llvm.tpc.ld.tnsr.v64f32.i1(<5 x i32> [[DOTSROA_07_0_VEC_INSERT_2]], i8 0, i32 0, <64 x float> undef, i1 true, i1 false)
; CHECK-NEXT:    [[DOTSROA_09_0_VEC_INSERT_2:%.*]] = shufflevector <5 x i32> <i32 320, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> [[DOTSROA_09_0_VEC_INSERT_1]], <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
; CHECK-NEXT:    [[TMP27:%.*]] = tail call <64 x float> @llvm.tpc.ld.tnsr.v64f32.i1(<5 x i32> [[DOTSROA_09_0_VEC_INSERT_2]], i8 0, i32 0, <64 x float> undef, i1 true, i1 false)
; CHECK-NEXT:    [[TMP28:%.*]] = shufflevector <64 x float> [[TMP26]], <64 x float> [[TMP27]], <128 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63, i32 64, i32 65, i32 66, i32 67, i32 68, i32 69, i32 70, i32 71, i32 72, i32 73, i32 74, i32 75, i32 76, i32 77, i32 78, i32 79, i32 80, i32 81, i32 82, i32 83, i32 84, i32 85, i32 86, i32 87, i32 88, i32 89, i32 90, i32 91, i32 92, i32 93, i32 94, i32 95, i32 96, i32 97, i32 98, i32 99, i32 100, i32 101, i32 102, i32 103, i32 104, i32 105, i32 106, i32 107, i32 108, i32 109, i32 110, i32 111, i32 112, i32 113, i32 114, i32 115, i32 116, i32 117, i32 118, i32 119, i32 120, i32 121, i32 122, i32 123, i32 124, i32 125, i32 126, i32 127>
; CHECK-NEXT:    [[TMP29:%.*]] = call <128 x bfloat> @llvm.tpc.convert.v128bf16.v128f32.i1(<128 x float> [[TMP28]], i8 0, i32 327940, <128 x bfloat> undef, i1 true, i1 false)
; CHECK-NEXT:    [[TMP30:%.*]] = fmul <128 x bfloat> [[TMP7]], [[TMP29]]
; CHECK-NEXT:    [[TMP31:%.*]] = call <128 x float> @llvm.tpc.convert.v128f32.v128bf16.i1(<128 x bfloat> [[TMP30]], i8 1, i32 327680, <128 x float> undef, i1 true, i1 false)
; CHECK-NEXT:    [[TMP32:%.*]] = shufflevector <128 x float> [[TMP31]], <128 x float> undef, <64 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
; CHECK-NEXT:    [[TMP33:%.*]] = shufflevector <128 x float> [[TMP31]], <128 x float> undef, <64 x i32> <i32 64, i32 65, i32 66, i32 67, i32 68, i32 69, i32 70, i32 71, i32 72, i32 73, i32 74, i32 75, i32 76, i32 77, i32 78, i32 79, i32 80, i32 81, i32 82, i32 83, i32 84, i32 85, i32 86, i32 87, i32 88, i32 89, i32 90, i32 91, i32 92, i32 93, i32 94, i32 95, i32 96, i32 97, i32 98, i32 99, i32 100, i32 101, i32 102, i32 103, i32 104, i32 105, i32 106, i32 107, i32 108, i32 109, i32 110, i32 111, i32 112, i32 113, i32 114, i32 115, i32 116, i32 117, i32 118, i32 119, i32 120, i32 121, i32 122, i32 123, i32 124, i32 125, i32 126, i32 127>
; CHECK-NEXT:    [[DOTSROA_011_0_VEC_INSERT_2:%.*]] = shufflevector <5 x i32> <i32 256, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> [[DOTSROA_011_0_VEC_INSERT_1]], <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
; CHECK-NEXT:    tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> [[DOTSROA_011_0_VEC_INSERT_2]], i8 2, <64 x float> [[TMP32]], i32 0, i1 true, i1 false)
; CHECK-NEXT:    [[DOTSROA_013_0_VEC_INSERT_2:%.*]] = shufflevector <5 x i32> <i32 320, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> [[DOTSROA_013_0_VEC_INSERT_1]], <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
; CHECK-NEXT:    tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> [[DOTSROA_013_0_VEC_INSERT_2]], i8 2, <64 x float> [[TMP33]], i32 0, i1 true, i1 false)
; CHECK-NEXT:    [[DOTSROA_07_0_VEC_INSERT_3:%.*]] = shufflevector <5 x i32> <i32 384, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> [[DOTSROA_07_0_VEC_INSERT_2]], <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
; CHECK-NEXT:    [[TMP34:%.*]] = tail call <64 x float> @llvm.tpc.ld.tnsr.v64f32.i1(<5 x i32> [[DOTSROA_07_0_VEC_INSERT_3]], i8 0, i32 0, <64 x float> undef, i1 true, i1 false)
; CHECK-NEXT:    [[DOTSROA_09_0_VEC_INSERT_3:%.*]] = shufflevector <5 x i32> <i32 448, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> [[DOTSROA_09_0_VEC_INSERT_2]], <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
; CHECK-NEXT:    [[TMP35:%.*]] = tail call <64 x float> @llvm.tpc.ld.tnsr.v64f32.i1(<5 x i32> [[DOTSROA_09_0_VEC_INSERT_3]], i8 0, i32 0, <64 x float> undef, i1 true, i1 false)
; CHECK-NEXT:    [[TMP36:%.*]] = shufflevector <64 x float> [[TMP34]], <64 x float> [[TMP35]], <128 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63, i32 64, i32 65, i32 66, i32 67, i32 68, i32 69, i32 70, i32 71, i32 72, i32 73, i32 74, i32 75, i32 76, i32 77, i32 78, i32 79, i32 80, i32 81, i32 82, i32 83, i32 84, i32 85, i32 86, i32 87, i32 88, i32 89, i32 90, i32 91, i32 92, i32 93, i32 94, i32 95, i32 96, i32 97, i32 98, i32 99, i32 100, i32 101, i32 102, i32 103, i32 104, i32 105, i32 106, i32 107, i32 108, i32 109, i32 110, i32 111, i32 112, i32 113, i32 114, i32 115, i32 116, i32 117, i32 118, i32 119, i32 120, i32 121, i32 122, i32 123, i32 124, i32 125, i32 126, i32 127>
; CHECK-NEXT:    [[TMP37:%.*]] = call <128 x bfloat> @llvm.tpc.convert.v128bf16.v128f32.i1(<128 x float> [[TMP36]], i8 0, i32 327940, <128 x bfloat> undef, i1 true, i1 false)
; CHECK-NEXT:    [[TMP38:%.*]] = fmul <128 x bfloat> [[TMP7]], [[TMP37]]
; CHECK-NEXT:    [[TMP39:%.*]] = call <128 x float> @llvm.tpc.convert.v128f32.v128bf16.i1(<128 x bfloat> [[TMP38]], i8 1, i32 327680, <128 x float> undef, i1 true, i1 false)
; CHECK-NEXT:    [[TMP40:%.*]] = shufflevector <128 x float> [[TMP39]], <128 x float> undef, <64 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
; CHECK-NEXT:    [[TMP41:%.*]] = shufflevector <128 x float> [[TMP39]], <128 x float> undef, <64 x i32> <i32 64, i32 65, i32 66, i32 67, i32 68, i32 69, i32 70, i32 71, i32 72, i32 73, i32 74, i32 75, i32 76, i32 77, i32 78, i32 79, i32 80, i32 81, i32 82, i32 83, i32 84, i32 85, i32 86, i32 87, i32 88, i32 89, i32 90, i32 91, i32 92, i32 93, i32 94, i32 95, i32 96, i32 97, i32 98, i32 99, i32 100, i32 101, i32 102, i32 103, i32 104, i32 105, i32 106, i32 107, i32 108, i32 109, i32 110, i32 111, i32 112, i32 113, i32 114, i32 115, i32 116, i32 117, i32 118, i32 119, i32 120, i32 121, i32 122, i32 123, i32 124, i32 125, i32 126, i32 127>
; CHECK-NEXT:    [[DOTSROA_011_0_VEC_INSERT_3:%.*]] = shufflevector <5 x i32> <i32 384, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> [[DOTSROA_011_0_VEC_INSERT_2]], <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
; CHECK-NEXT:    tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> [[DOTSROA_011_0_VEC_INSERT_3]], i8 2, <64 x float> [[TMP40]], i32 0, i1 true, i1 false)
; CHECK-NEXT:    [[DOTSROA_013_0_VEC_INSERT_3:%.*]] = shufflevector <5 x i32> <i32 448, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> [[DOTSROA_013_0_VEC_INSERT_2]], <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
; CHECK-NEXT:    tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> [[DOTSROA_013_0_VEC_INSERT_3]], i8 2, <64 x float> [[TMP41]], i32 0, i1 true, i1 false)
; CHECK-NEXT:    [[DOTSROA_07_0_VEC_INSERT_4:%.*]] = shufflevector <5 x i32> <i32 512, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> [[DOTSROA_07_0_VEC_INSERT_3]], <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
; CHECK-NEXT:    [[TMP42:%.*]] = tail call <64 x float> @llvm.tpc.ld.tnsr.v64f32.i1(<5 x i32> [[DOTSROA_07_0_VEC_INSERT_4]], i8 0, i32 0, <64 x float> undef, i1 true, i1 false)
; CHECK-NEXT:    [[DOTSROA_09_0_VEC_INSERT_4:%.*]] = shufflevector <5 x i32> <i32 576, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> [[DOTSROA_09_0_VEC_INSERT_3]], <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
; CHECK-NEXT:    [[TMP43:%.*]] = tail call <64 x float> @llvm.tpc.ld.tnsr.v64f32.i1(<5 x i32> [[DOTSROA_09_0_VEC_INSERT_4]], i8 0, i32 0, <64 x float> undef, i1 true, i1 false)
; CHECK-NEXT:    [[TMP44:%.*]] = shufflevector <64 x float> [[TMP42]], <64 x float> [[TMP43]], <128 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63, i32 64, i32 65, i32 66, i32 67, i32 68, i32 69, i32 70, i32 71, i32 72, i32 73, i32 74, i32 75, i32 76, i32 77, i32 78, i32 79, i32 80, i32 81, i32 82, i32 83, i32 84, i32 85, i32 86, i32 87, i32 88, i32 89, i32 90, i32 91, i32 92, i32 93, i32 94, i32 95, i32 96, i32 97, i32 98, i32 99, i32 100, i32 101, i32 102, i32 103, i32 104, i32 105, i32 106, i32 107, i32 108, i32 109, i32 110, i32 111, i32 112, i32 113, i32 114, i32 115, i32 116, i32 117, i32 118, i32 119, i32 120, i32 121, i32 122, i32 123, i32 124, i32 125, i32 126, i32 127>
; CHECK-NEXT:    [[TMP45:%.*]] = call <128 x bfloat> @llvm.tpc.convert.v128bf16.v128f32.i1(<128 x float> [[TMP44]], i8 0, i32 327940, <128 x bfloat> undef, i1 true, i1 false)
; CHECK-NEXT:    [[TMP46:%.*]] = fmul <128 x bfloat> [[TMP7]], [[TMP45]]
; CHECK-NEXT:    [[TMP47:%.*]] = call <128 x float> @llvm.tpc.convert.v128f32.v128bf16.i1(<128 x bfloat> [[TMP46]], i8 1, i32 327680, <128 x float> undef, i1 true, i1 false)
; CHECK-NEXT:    [[TMP48:%.*]] = shufflevector <128 x float> [[TMP47]], <128 x float> undef, <64 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
; CHECK-NEXT:    [[TMP49:%.*]] = shufflevector <128 x float> [[TMP47]], <128 x float> undef, <64 x i32> <i32 64, i32 65, i32 66, i32 67, i32 68, i32 69, i32 70, i32 71, i32 72, i32 73, i32 74, i32 75, i32 76, i32 77, i32 78, i32 79, i32 80, i32 81, i32 82, i32 83, i32 84, i32 85, i32 86, i32 87, i32 88, i32 89, i32 90, i32 91, i32 92, i32 93, i32 94, i32 95, i32 96, i32 97, i32 98, i32 99, i32 100, i32 101, i32 102, i32 103, i32 104, i32 105, i32 106, i32 107, i32 108, i32 109, i32 110, i32 111, i32 112, i32 113, i32 114, i32 115, i32 116, i32 117, i32 118, i32 119, i32 120, i32 121, i32 122, i32 123, i32 124, i32 125, i32 126, i32 127>
; CHECK-NEXT:    [[DOTSROA_011_0_VEC_INSERT_4:%.*]] = shufflevector <5 x i32> <i32 512, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> [[DOTSROA_011_0_VEC_INSERT_3]], <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
; CHECK-NEXT:    tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> [[DOTSROA_011_0_VEC_INSERT_4]], i8 2, <64 x float> [[TMP48]], i32 0, i1 true, i1 false)
; CHECK-NEXT:    [[DOTSROA_013_0_VEC_INSERT_4:%.*]] = shufflevector <5 x i32> <i32 576, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> [[DOTSROA_013_0_VEC_INSERT_3]], <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
; CHECK-NEXT:    tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> [[DOTSROA_013_0_VEC_INSERT_4]], i8 2, <64 x float> [[TMP49]], i32 0, i1 true, i1 false)
; CHECK-NEXT:    [[DOTSROA_07_0_VEC_INSERT_5:%.*]] = shufflevector <5 x i32> <i32 640, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> [[DOTSROA_07_0_VEC_INSERT_4]], <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
; CHECK-NEXT:    [[TMP50:%.*]] = tail call <64 x float> @llvm.tpc.ld.tnsr.v64f32.i1(<5 x i32> [[DOTSROA_07_0_VEC_INSERT_5]], i8 0, i32 0, <64 x float> undef, i1 true, i1 false)
; CHECK-NEXT:    [[DOTSROA_09_0_VEC_INSERT_5:%.*]] = shufflevector <5 x i32> <i32 704, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> [[DOTSROA_09_0_VEC_INSERT_4]], <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
; CHECK-NEXT:    [[TMP51:%.*]] = tail call <64 x float> @llvm.tpc.ld.tnsr.v64f32.i1(<5 x i32> [[DOTSROA_09_0_VEC_INSERT_5]], i8 0, i32 0, <64 x float> undef, i1 true, i1 false)
; CHECK-NEXT:    [[TMP52:%.*]] = shufflevector <64 x float> [[TMP50]], <64 x float> [[TMP51]], <128 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63, i32 64, i32 65, i32 66, i32 67, i32 68, i32 69, i32 70, i32 71, i32 72, i32 73, i32 74, i32 75, i32 76, i32 77, i32 78, i32 79, i32 80, i32 81, i32 82, i32 83, i32 84, i32 85, i32 86, i32 87, i32 88, i32 89, i32 90, i32 91, i32 92, i32 93, i32 94, i32 95, i32 96, i32 97, i32 98, i32 99, i32 100, i32 101, i32 102, i32 103, i32 104, i32 105, i32 106, i32 107, i32 108, i32 109, i32 110, i32 111, i32 112, i32 113, i32 114, i32 115, i32 116, i32 117, i32 118, i32 119, i32 120, i32 121, i32 122, i32 123, i32 124, i32 125, i32 126, i32 127>
; CHECK-NEXT:    [[TMP53:%.*]] = call <128 x bfloat> @llvm.tpc.convert.v128bf16.v128f32.i1(<128 x float> [[TMP52]], i8 0, i32 327940, <128 x bfloat> undef, i1 true, i1 false)
; CHECK-NEXT:    [[TMP54:%.*]] = fmul <128 x bfloat> [[TMP7]], [[TMP53]]
; CHECK-NEXT:    [[TMP55:%.*]] = call <128 x float> @llvm.tpc.convert.v128f32.v128bf16.i1(<128 x bfloat> [[TMP54]], i8 1, i32 327680, <128 x float> undef, i1 true, i1 false)
; CHECK-NEXT:    [[TMP56:%.*]] = shufflevector <128 x float> [[TMP55]], <128 x float> undef, <64 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
; CHECK-NEXT:    [[TMP57:%.*]] = shufflevector <128 x float> [[TMP55]], <128 x float> undef, <64 x i32> <i32 64, i32 65, i32 66, i32 67, i32 68, i32 69, i32 70, i32 71, i32 72, i32 73, i32 74, i32 75, i32 76, i32 77, i32 78, i32 79, i32 80, i32 81, i32 82, i32 83, i32 84, i32 85, i32 86, i32 87, i32 88, i32 89, i32 90, i32 91, i32 92, i32 93, i32 94, i32 95, i32 96, i32 97, i32 98, i32 99, i32 100, i32 101, i32 102, i32 103, i32 104, i32 105, i32 106, i32 107, i32 108, i32 109, i32 110, i32 111, i32 112, i32 113, i32 114, i32 115, i32 116, i32 117, i32 118, i32 119, i32 120, i32 121, i32 122, i32 123, i32 124, i32 125, i32 126, i32 127>
; CHECK-NEXT:    [[DOTSROA_011_0_VEC_INSERT_5:%.*]] = shufflevector <5 x i32> <i32 640, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> [[DOTSROA_011_0_VEC_INSERT_4]], <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
; CHECK-NEXT:    tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> [[DOTSROA_011_0_VEC_INSERT_5]], i8 2, <64 x float> [[TMP56]], i32 0, i1 true, i1 false)
; CHECK-NEXT:    [[DOTSROA_013_0_VEC_INSERT_5:%.*]] = shufflevector <5 x i32> <i32 704, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> [[DOTSROA_013_0_VEC_INSERT_4]], <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
; CHECK-NEXT:    tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> [[DOTSROA_013_0_VEC_INSERT_5]], i8 2, <64 x float> [[TMP57]], i32 0, i1 true, i1 false)
; CHECK-NEXT:    [[DOTSROA_07_0_VEC_INSERT_6:%.*]] = shufflevector <5 x i32> <i32 768, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> [[DOTSROA_07_0_VEC_INSERT_5]], <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
; CHECK-NEXT:    [[TMP58:%.*]] = tail call <64 x float> @llvm.tpc.ld.tnsr.v64f32.i1(<5 x i32> [[DOTSROA_07_0_VEC_INSERT_6]], i8 0, i32 0, <64 x float> undef, i1 true, i1 false)
; CHECK-NEXT:    [[DOTSROA_09_0_VEC_INSERT_6:%.*]] = shufflevector <5 x i32> <i32 832, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> [[DOTSROA_09_0_VEC_INSERT_5]], <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
; CHECK-NEXT:    [[TMP59:%.*]] = tail call <64 x float> @llvm.tpc.ld.tnsr.v64f32.i1(<5 x i32> [[DOTSROA_09_0_VEC_INSERT_6]], i8 0, i32 0, <64 x float> undef, i1 true, i1 false)
; CHECK-NEXT:    [[TMP60:%.*]] = shufflevector <64 x float> [[TMP58]], <64 x float> [[TMP59]], <128 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63, i32 64, i32 65, i32 66, i32 67, i32 68, i32 69, i32 70, i32 71, i32 72, i32 73, i32 74, i32 75, i32 76, i32 77, i32 78, i32 79, i32 80, i32 81, i32 82, i32 83, i32 84, i32 85, i32 86, i32 87, i32 88, i32 89, i32 90, i32 91, i32 92, i32 93, i32 94, i32 95, i32 96, i32 97, i32 98, i32 99, i32 100, i32 101, i32 102, i32 103, i32 104, i32 105, i32 106, i32 107, i32 108, i32 109, i32 110, i32 111, i32 112, i32 113, i32 114, i32 115, i32 116, i32 117, i32 118, i32 119, i32 120, i32 121, i32 122, i32 123, i32 124, i32 125, i32 126, i32 127>
; CHECK-NEXT:    [[TMP61:%.*]] = call <128 x bfloat> @llvm.tpc.convert.v128bf16.v128f32.i1(<128 x float> [[TMP60]], i8 0, i32 327940, <128 x bfloat> undef, i1 true, i1 false)
; CHECK-NEXT:    [[TMP62:%.*]] = fmul <128 x bfloat> [[TMP7]], [[TMP61]]
; CHECK-NEXT:    [[TMP63:%.*]] = call <128 x float> @llvm.tpc.convert.v128f32.v128bf16.i1(<128 x bfloat> [[TMP62]], i8 1, i32 327680, <128 x float> undef, i1 true, i1 false)
; CHECK-NEXT:    [[TMP64:%.*]] = shufflevector <128 x float> [[TMP63]], <128 x float> undef, <64 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
; CHECK-NEXT:    [[TMP65:%.*]] = shufflevector <128 x float> [[TMP63]], <128 x float> undef, <64 x i32> <i32 64, i32 65, i32 66, i32 67, i32 68, i32 69, i32 70, i32 71, i32 72, i32 73, i32 74, i32 75, i32 76, i32 77, i32 78, i32 79, i32 80, i32 81, i32 82, i32 83, i32 84, i32 85, i32 86, i32 87, i32 88, i32 89, i32 90, i32 91, i32 92, i32 93, i32 94, i32 95, i32 96, i32 97, i32 98, i32 99, i32 100, i32 101, i32 102, i32 103, i32 104, i32 105, i32 106, i32 107, i32 108, i32 109, i32 110, i32 111, i32 112, i32 113, i32 114, i32 115, i32 116, i32 117, i32 118, i32 119, i32 120, i32 121, i32 122, i32 123, i32 124, i32 125, i32 126, i32 127>
; CHECK-NEXT:    [[DOTSROA_011_0_VEC_INSERT_6:%.*]] = shufflevector <5 x i32> <i32 768, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> [[DOTSROA_011_0_VEC_INSERT_5]], <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
; CHECK-NEXT:    tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> [[DOTSROA_011_0_VEC_INSERT_6]], i8 2, <64 x float> [[TMP64]], i32 0, i1 true, i1 false)
; CHECK-NEXT:    [[DOTSROA_013_0_VEC_INSERT_6:%.*]] = shufflevector <5 x i32> <i32 832, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> [[DOTSROA_013_0_VEC_INSERT_5]], <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
; CHECK-NEXT:    tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> [[DOTSROA_013_0_VEC_INSERT_6]], i8 2, <64 x float> [[TMP65]], i32 0, i1 true, i1 false)
; CHECK-NEXT:    [[DOTSROA_07_0_VEC_INSERT_7]] = shufflevector <5 x i32> <i32 896, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> [[DOTSROA_07_0_VEC_INSERT_6]], <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
; CHECK-NEXT:    [[TMP66:%.*]] = tail call <64 x float> @llvm.tpc.ld.tnsr.v64f32.i1(<5 x i32> [[DOTSROA_07_0_VEC_INSERT_7]], i8 0, i32 0, <64 x float> undef, i1 true, i1 false)
; CHECK-NEXT:    [[DOTSROA_09_0_VEC_INSERT_7]] = shufflevector <5 x i32> <i32 960, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> [[DOTSROA_09_0_VEC_INSERT_6]], <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
; CHECK-NEXT:    [[TMP67:%.*]] = tail call <64 x float> @llvm.tpc.ld.tnsr.v64f32.i1(<5 x i32> [[DOTSROA_09_0_VEC_INSERT_7]], i8 0, i32 0, <64 x float> undef, i1 true, i1 false)
; CHECK-NEXT:    [[TMP68:%.*]] = shufflevector <64 x float> [[TMP66]], <64 x float> [[TMP67]], <128 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63, i32 64, i32 65, i32 66, i32 67, i32 68, i32 69, i32 70, i32 71, i32 72, i32 73, i32 74, i32 75, i32 76, i32 77, i32 78, i32 79, i32 80, i32 81, i32 82, i32 83, i32 84, i32 85, i32 86, i32 87, i32 88, i32 89, i32 90, i32 91, i32 92, i32 93, i32 94, i32 95, i32 96, i32 97, i32 98, i32 99, i32 100, i32 101, i32 102, i32 103, i32 104, i32 105, i32 106, i32 107, i32 108, i32 109, i32 110, i32 111, i32 112, i32 113, i32 114, i32 115, i32 116, i32 117, i32 118, i32 119, i32 120, i32 121, i32 122, i32 123, i32 124, i32 125, i32 126, i32 127>
; CHECK-NEXT:    [[TMP69:%.*]] = call <128 x bfloat> @llvm.tpc.convert.v128bf16.v128f32.i1(<128 x float> [[TMP68]], i8 0, i32 327940, <128 x bfloat> undef, i1 true, i1 false)
; CHECK-NEXT:    [[TMP70:%.*]] = fmul <128 x bfloat> [[TMP7]], [[TMP69]]
; CHECK-NEXT:    [[TMP71:%.*]] = call <128 x float> @llvm.tpc.convert.v128f32.v128bf16.i1(<128 x bfloat> [[TMP70]], i8 1, i32 327680, <128 x float> undef, i1 true, i1 false)
; CHECK-NEXT:    [[TMP72:%.*]] = shufflevector <128 x float> [[TMP71]], <128 x float> undef, <64 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
; CHECK-NEXT:    [[TMP73:%.*]] = shufflevector <128 x float> [[TMP71]], <128 x float> undef, <64 x i32> <i32 64, i32 65, i32 66, i32 67, i32 68, i32 69, i32 70, i32 71, i32 72, i32 73, i32 74, i32 75, i32 76, i32 77, i32 78, i32 79, i32 80, i32 81, i32 82, i32 83, i32 84, i32 85, i32 86, i32 87, i32 88, i32 89, i32 90, i32 91, i32 92, i32 93, i32 94, i32 95, i32 96, i32 97, i32 98, i32 99, i32 100, i32 101, i32 102, i32 103, i32 104, i32 105, i32 106, i32 107, i32 108, i32 109, i32 110, i32 111, i32 112, i32 113, i32 114, i32 115, i32 116, i32 117, i32 118, i32 119, i32 120, i32 121, i32 122, i32 123, i32 124, i32 125, i32 126, i32 127>
; CHECK-NEXT:    [[DOTSROA_011_0_VEC_INSERT_7]] = shufflevector <5 x i32> <i32 896, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> [[DOTSROA_011_0_VEC_INSERT_6]], <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
; CHECK-NEXT:    tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> [[DOTSROA_011_0_VEC_INSERT_7]], i8 2, <64 x float> [[TMP72]], i32 0, i1 true, i1 false)
; CHECK-NEXT:    [[DOTSROA_013_0_VEC_INSERT_7]] = shufflevector <5 x i32> <i32 960, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> [[DOTSROA_013_0_VEC_INSERT_6]], <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
; CHECK-NEXT:    tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> [[DOTSROA_013_0_VEC_INSERT_7]], i8 2, <64 x float> [[TMP73]], i32 0, i1 true, i1 false)
; CHECK-NEXT:    [[TMP74]] = add nsw i32 [[TMP9]], 1
; CHECK-NEXT:    [[TMP75:%.*]] = icmp slt i32 [[TMP74]], [[TMP5]]
; CHECK-NEXT:    br i1 [[TMP75]], label [[DOTLR_PH]], label [[DOT_CRIT_EDGE]]
; CHECK:       ._crit_edge:
; CHECK-NEXT:    ret void
;
  %1 = tail call <5 x i32> @llvm.tpc.get.index.space.offset()
  %2 = tail call <5 x i32> @llvm.tpc.get.index.space.size()
  %3 = add <5 x i32> %2, %1
  %4 = extractelement <5 x i32> %1, i32 1
  %5 = extractelement <5 x i32> %3, i32 1
  %6 = tail call i8 addrspace(3)* @llvm.tpc.gen.addr(<5 x i32> zeroinitializer, i8 1, i32 0, i8 addrspace(3)* undef, i1 true, i1 false)
  %7 = tail call <128 x bfloat> @llvm.tpc.ld.g.v128bf16.i1(i8 addrspace(3)* %6, i32 0, <128 x bfloat> undef, i1 true, i1 false)
  %8 = icmp slt i32 %4, %5
  br i1 %8, label %.lr.ph, label %._crit_edge

.lr.ph:                                           ; preds = %0, %.lr.ph
  %9 = phi i32 [ %74, %.lr.ph ], [ %4, %0 ]
  %.sroa.013.022 = phi <5 x i32> [ %.sroa.013.0.vec.insert.7, %.lr.ph ], [ zeroinitializer, %0 ]
  %.sroa.07.021 = phi <5 x i32> [ %.sroa.07.0.vec.insert.7, %.lr.ph ], [ zeroinitializer, %0 ]
  %.sroa.09.020 = phi <5 x i32> [ %.sroa.09.0.vec.insert.7, %.lr.ph ], [ zeroinitializer, %0 ]
  %.sroa.011.019 = phi <5 x i32> [ %.sroa.011.0.vec.insert.7, %.lr.ph ], [ zeroinitializer, %0 ]
  %.sroa.013.4.vec.insert = insertelement <5 x i32> %.sroa.013.022, i32 %9, i32 1
  %.sroa.011.4.vec.insert = insertelement <5 x i32> %.sroa.011.019, i32 %9, i32 1
  %.sroa.09.4.vec.insert = insertelement <5 x i32> %.sroa.09.020, i32 %9, i32 1
  %.sroa.07.4.vec.insert = insertelement <5 x i32> %.sroa.07.021, i32 %9, i32 1
  %.sroa.07.0.vec.insert = shufflevector <5 x i32> <i32 0, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> %.sroa.07.4.vec.insert, <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
  %10 = tail call <64 x float> @llvm.tpc.ld.tnsr.v64f32.i1(<5 x i32> %.sroa.07.0.vec.insert, i8 0, i32 0, <64 x float> undef, i1 true, i1 false)
  %.sroa.09.0.vec.insert = shufflevector <5 x i32> <i32 64, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> %.sroa.09.4.vec.insert, <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
  %11 = tail call <64 x float> @llvm.tpc.ld.tnsr.v64f32.i1(<5 x i32> %.sroa.09.0.vec.insert, i8 0, i32 0, <64 x float> undef, i1 true, i1 false)
  %12 = shufflevector <64 x float> %10, <64 x float> %11, <128 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63, i32 64, i32 65, i32 66, i32 67, i32 68, i32 69, i32 70, i32 71, i32 72, i32 73, i32 74, i32 75, i32 76, i32 77, i32 78, i32 79, i32 80, i32 81, i32 82, i32 83, i32 84, i32 85, i32 86, i32 87, i32 88, i32 89, i32 90, i32 91, i32 92, i32 93, i32 94, i32 95, i32 96, i32 97, i32 98, i32 99, i32 100, i32 101, i32 102, i32 103, i32 104, i32 105, i32 106, i32 107, i32 108, i32 109, i32 110, i32 111, i32 112, i32 113, i32 114, i32 115, i32 116, i32 117, i32 118, i32 119, i32 120, i32 121, i32 122, i32 123, i32 124, i32 125, i32 126, i32 127>
  %13 = tail call <128 x bfloat> @llvm.tpc.fptrunc.swch.v128bf16.v128f32(<128 x float> %12, i32 327680)
  %14 = fmul <128 x bfloat> %7, %13
  %15 = tail call <128 x float> @llvm.tpc.fpext.swch.v128f32.v128bf16(<128 x bfloat> %14, i32 327680)
  %16 = shufflevector <128 x float> %15, <128 x float> undef, <64 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
  %17 = shufflevector <128 x float> %15, <128 x float> undef, <64 x i32> <i32 64, i32 65, i32 66, i32 67, i32 68, i32 69, i32 70, i32 71, i32 72, i32 73, i32 74, i32 75, i32 76, i32 77, i32 78, i32 79, i32 80, i32 81, i32 82, i32 83, i32 84, i32 85, i32 86, i32 87, i32 88, i32 89, i32 90, i32 91, i32 92, i32 93, i32 94, i32 95, i32 96, i32 97, i32 98, i32 99, i32 100, i32 101, i32 102, i32 103, i32 104, i32 105, i32 106, i32 107, i32 108, i32 109, i32 110, i32 111, i32 112, i32 113, i32 114, i32 115, i32 116, i32 117, i32 118, i32 119, i32 120, i32 121, i32 122, i32 123, i32 124, i32 125, i32 126, i32 127>
  %.sroa.011.0.vec.insert = shufflevector <5 x i32> <i32 0, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> %.sroa.011.4.vec.insert, <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
  tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> %.sroa.011.0.vec.insert, i8 2, <64 x float> %16, i32 0, i1 true, i1 false)
  %.sroa.013.0.vec.insert = shufflevector <5 x i32> <i32 64, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> %.sroa.013.4.vec.insert, <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
  tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> %.sroa.013.0.vec.insert, i8 2, <64 x float> %17, i32 0, i1 true, i1 false)
  %.sroa.07.0.vec.insert.1 = shufflevector <5 x i32> <i32 128, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> %.sroa.07.0.vec.insert, <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
  %18 = tail call <64 x float> @llvm.tpc.ld.tnsr.v64f32.i1(<5 x i32> %.sroa.07.0.vec.insert.1, i8 0, i32 0, <64 x float> undef, i1 true, i1 false)
  %.sroa.09.0.vec.insert.1 = shufflevector <5 x i32> <i32 192, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> %.sroa.09.0.vec.insert, <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
  %19 = tail call <64 x float> @llvm.tpc.ld.tnsr.v64f32.i1(<5 x i32> %.sroa.09.0.vec.insert.1, i8 0, i32 0, <64 x float> undef, i1 true, i1 false)
  %20 = shufflevector <64 x float> %18, <64 x float> %19, <128 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63, i32 64, i32 65, i32 66, i32 67, i32 68, i32 69, i32 70, i32 71, i32 72, i32 73, i32 74, i32 75, i32 76, i32 77, i32 78, i32 79, i32 80, i32 81, i32 82, i32 83, i32 84, i32 85, i32 86, i32 87, i32 88, i32 89, i32 90, i32 91, i32 92, i32 93, i32 94, i32 95, i32 96, i32 97, i32 98, i32 99, i32 100, i32 101, i32 102, i32 103, i32 104, i32 105, i32 106, i32 107, i32 108, i32 109, i32 110, i32 111, i32 112, i32 113, i32 114, i32 115, i32 116, i32 117, i32 118, i32 119, i32 120, i32 121, i32 122, i32 123, i32 124, i32 125, i32 126, i32 127>
  %21 = tail call <128 x bfloat> @llvm.tpc.fptrunc.swch.v128bf16.v128f32(<128 x float> %20, i32 327680)
  %22 = fmul <128 x bfloat> %7, %21
  %23 = tail call <128 x float> @llvm.tpc.fpext.swch.v128f32.v128bf16(<128 x bfloat> %22, i32 327680)
  %24 = shufflevector <128 x float> %23, <128 x float> undef, <64 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
  %25 = shufflevector <128 x float> %23, <128 x float> undef, <64 x i32> <i32 64, i32 65, i32 66, i32 67, i32 68, i32 69, i32 70, i32 71, i32 72, i32 73, i32 74, i32 75, i32 76, i32 77, i32 78, i32 79, i32 80, i32 81, i32 82, i32 83, i32 84, i32 85, i32 86, i32 87, i32 88, i32 89, i32 90, i32 91, i32 92, i32 93, i32 94, i32 95, i32 96, i32 97, i32 98, i32 99, i32 100, i32 101, i32 102, i32 103, i32 104, i32 105, i32 106, i32 107, i32 108, i32 109, i32 110, i32 111, i32 112, i32 113, i32 114, i32 115, i32 116, i32 117, i32 118, i32 119, i32 120, i32 121, i32 122, i32 123, i32 124, i32 125, i32 126, i32 127>
  %.sroa.011.0.vec.insert.1 = shufflevector <5 x i32> <i32 128, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> %.sroa.011.0.vec.insert, <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
  tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> %.sroa.011.0.vec.insert.1, i8 2, <64 x float> %24, i32 0, i1 true, i1 false)
  %.sroa.013.0.vec.insert.1 = shufflevector <5 x i32> <i32 192, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> %.sroa.013.0.vec.insert, <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
  tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> %.sroa.013.0.vec.insert.1, i8 2, <64 x float> %25, i32 0, i1 true, i1 false)
  %.sroa.07.0.vec.insert.2 = shufflevector <5 x i32> <i32 256, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> %.sroa.07.0.vec.insert.1, <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
  %26 = tail call <64 x float> @llvm.tpc.ld.tnsr.v64f32.i1(<5 x i32> %.sroa.07.0.vec.insert.2, i8 0, i32 0, <64 x float> undef, i1 true, i1 false)
  %.sroa.09.0.vec.insert.2 = shufflevector <5 x i32> <i32 320, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> %.sroa.09.0.vec.insert.1, <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
  %27 = tail call <64 x float> @llvm.tpc.ld.tnsr.v64f32.i1(<5 x i32> %.sroa.09.0.vec.insert.2, i8 0, i32 0, <64 x float> undef, i1 true, i1 false)
  %28 = shufflevector <64 x float> %26, <64 x float> %27, <128 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63, i32 64, i32 65, i32 66, i32 67, i32 68, i32 69, i32 70, i32 71, i32 72, i32 73, i32 74, i32 75, i32 76, i32 77, i32 78, i32 79, i32 80, i32 81, i32 82, i32 83, i32 84, i32 85, i32 86, i32 87, i32 88, i32 89, i32 90, i32 91, i32 92, i32 93, i32 94, i32 95, i32 96, i32 97, i32 98, i32 99, i32 100, i32 101, i32 102, i32 103, i32 104, i32 105, i32 106, i32 107, i32 108, i32 109, i32 110, i32 111, i32 112, i32 113, i32 114, i32 115, i32 116, i32 117, i32 118, i32 119, i32 120, i32 121, i32 122, i32 123, i32 124, i32 125, i32 126, i32 127>
  %29 = tail call <128 x bfloat> @llvm.tpc.fptrunc.swch.v128bf16.v128f32(<128 x float> %28, i32 327680)
  %30 = fmul <128 x bfloat> %7, %29
  %31 = tail call <128 x float> @llvm.tpc.fpext.swch.v128f32.v128bf16(<128 x bfloat> %30, i32 327680)
  %32 = shufflevector <128 x float> %31, <128 x float> undef, <64 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
  %33 = shufflevector <128 x float> %31, <128 x float> undef, <64 x i32> <i32 64, i32 65, i32 66, i32 67, i32 68, i32 69, i32 70, i32 71, i32 72, i32 73, i32 74, i32 75, i32 76, i32 77, i32 78, i32 79, i32 80, i32 81, i32 82, i32 83, i32 84, i32 85, i32 86, i32 87, i32 88, i32 89, i32 90, i32 91, i32 92, i32 93, i32 94, i32 95, i32 96, i32 97, i32 98, i32 99, i32 100, i32 101, i32 102, i32 103, i32 104, i32 105, i32 106, i32 107, i32 108, i32 109, i32 110, i32 111, i32 112, i32 113, i32 114, i32 115, i32 116, i32 117, i32 118, i32 119, i32 120, i32 121, i32 122, i32 123, i32 124, i32 125, i32 126, i32 127>
  %.sroa.011.0.vec.insert.2 = shufflevector <5 x i32> <i32 256, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> %.sroa.011.0.vec.insert.1, <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
  tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> %.sroa.011.0.vec.insert.2, i8 2, <64 x float> %32, i32 0, i1 true, i1 false)
  %.sroa.013.0.vec.insert.2 = shufflevector <5 x i32> <i32 320, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> %.sroa.013.0.vec.insert.1, <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
  tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> %.sroa.013.0.vec.insert.2, i8 2, <64 x float> %33, i32 0, i1 true, i1 false)
  %.sroa.07.0.vec.insert.3 = shufflevector <5 x i32> <i32 384, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> %.sroa.07.0.vec.insert.2, <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
  %34 = tail call <64 x float> @llvm.tpc.ld.tnsr.v64f32.i1(<5 x i32> %.sroa.07.0.vec.insert.3, i8 0, i32 0, <64 x float> undef, i1 true, i1 false)
  %.sroa.09.0.vec.insert.3 = shufflevector <5 x i32> <i32 448, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> %.sroa.09.0.vec.insert.2, <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
  %35 = tail call <64 x float> @llvm.tpc.ld.tnsr.v64f32.i1(<5 x i32> %.sroa.09.0.vec.insert.3, i8 0, i32 0, <64 x float> undef, i1 true, i1 false)
  %36 = shufflevector <64 x float> %34, <64 x float> %35, <128 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63, i32 64, i32 65, i32 66, i32 67, i32 68, i32 69, i32 70, i32 71, i32 72, i32 73, i32 74, i32 75, i32 76, i32 77, i32 78, i32 79, i32 80, i32 81, i32 82, i32 83, i32 84, i32 85, i32 86, i32 87, i32 88, i32 89, i32 90, i32 91, i32 92, i32 93, i32 94, i32 95, i32 96, i32 97, i32 98, i32 99, i32 100, i32 101, i32 102, i32 103, i32 104, i32 105, i32 106, i32 107, i32 108, i32 109, i32 110, i32 111, i32 112, i32 113, i32 114, i32 115, i32 116, i32 117, i32 118, i32 119, i32 120, i32 121, i32 122, i32 123, i32 124, i32 125, i32 126, i32 127>
  %37 = tail call <128 x bfloat> @llvm.tpc.fptrunc.swch.v128bf16.v128f32(<128 x float> %36, i32 327680)
  %38 = fmul <128 x bfloat> %7, %37
  %39 = tail call <128 x float> @llvm.tpc.fpext.swch.v128f32.v128bf16(<128 x bfloat> %38, i32 327680)
  %40 = shufflevector <128 x float> %39, <128 x float> undef, <64 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
  %41 = shufflevector <128 x float> %39, <128 x float> undef, <64 x i32> <i32 64, i32 65, i32 66, i32 67, i32 68, i32 69, i32 70, i32 71, i32 72, i32 73, i32 74, i32 75, i32 76, i32 77, i32 78, i32 79, i32 80, i32 81, i32 82, i32 83, i32 84, i32 85, i32 86, i32 87, i32 88, i32 89, i32 90, i32 91, i32 92, i32 93, i32 94, i32 95, i32 96, i32 97, i32 98, i32 99, i32 100, i32 101, i32 102, i32 103, i32 104, i32 105, i32 106, i32 107, i32 108, i32 109, i32 110, i32 111, i32 112, i32 113, i32 114, i32 115, i32 116, i32 117, i32 118, i32 119, i32 120, i32 121, i32 122, i32 123, i32 124, i32 125, i32 126, i32 127>
  %.sroa.011.0.vec.insert.3 = shufflevector <5 x i32> <i32 384, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> %.sroa.011.0.vec.insert.2, <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
  tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> %.sroa.011.0.vec.insert.3, i8 2, <64 x float> %40, i32 0, i1 true, i1 false)
  %.sroa.013.0.vec.insert.3 = shufflevector <5 x i32> <i32 448, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> %.sroa.013.0.vec.insert.2, <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
  tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> %.sroa.013.0.vec.insert.3, i8 2, <64 x float> %41, i32 0, i1 true, i1 false)
  %.sroa.07.0.vec.insert.4 = shufflevector <5 x i32> <i32 512, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> %.sroa.07.0.vec.insert.3, <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
  %42 = tail call <64 x float> @llvm.tpc.ld.tnsr.v64f32.i1(<5 x i32> %.sroa.07.0.vec.insert.4, i8 0, i32 0, <64 x float> undef, i1 true, i1 false)
  %.sroa.09.0.vec.insert.4 = shufflevector <5 x i32> <i32 576, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> %.sroa.09.0.vec.insert.3, <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
  %43 = tail call <64 x float> @llvm.tpc.ld.tnsr.v64f32.i1(<5 x i32> %.sroa.09.0.vec.insert.4, i8 0, i32 0, <64 x float> undef, i1 true, i1 false)
  %44 = shufflevector <64 x float> %42, <64 x float> %43, <128 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63, i32 64, i32 65, i32 66, i32 67, i32 68, i32 69, i32 70, i32 71, i32 72, i32 73, i32 74, i32 75, i32 76, i32 77, i32 78, i32 79, i32 80, i32 81, i32 82, i32 83, i32 84, i32 85, i32 86, i32 87, i32 88, i32 89, i32 90, i32 91, i32 92, i32 93, i32 94, i32 95, i32 96, i32 97, i32 98, i32 99, i32 100, i32 101, i32 102, i32 103, i32 104, i32 105, i32 106, i32 107, i32 108, i32 109, i32 110, i32 111, i32 112, i32 113, i32 114, i32 115, i32 116, i32 117, i32 118, i32 119, i32 120, i32 121, i32 122, i32 123, i32 124, i32 125, i32 126, i32 127>
  %45 = tail call <128 x bfloat> @llvm.tpc.fptrunc.swch.v128bf16.v128f32(<128 x float> %44, i32 327680)
  %46 = fmul <128 x bfloat> %7, %45
  %47 = tail call <128 x float> @llvm.tpc.fpext.swch.v128f32.v128bf16(<128 x bfloat> %46, i32 327680)
  %48 = shufflevector <128 x float> %47, <128 x float> undef, <64 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
  %49 = shufflevector <128 x float> %47, <128 x float> undef, <64 x i32> <i32 64, i32 65, i32 66, i32 67, i32 68, i32 69, i32 70, i32 71, i32 72, i32 73, i32 74, i32 75, i32 76, i32 77, i32 78, i32 79, i32 80, i32 81, i32 82, i32 83, i32 84, i32 85, i32 86, i32 87, i32 88, i32 89, i32 90, i32 91, i32 92, i32 93, i32 94, i32 95, i32 96, i32 97, i32 98, i32 99, i32 100, i32 101, i32 102, i32 103, i32 104, i32 105, i32 106, i32 107, i32 108, i32 109, i32 110, i32 111, i32 112, i32 113, i32 114, i32 115, i32 116, i32 117, i32 118, i32 119, i32 120, i32 121, i32 122, i32 123, i32 124, i32 125, i32 126, i32 127>
  %.sroa.011.0.vec.insert.4 = shufflevector <5 x i32> <i32 512, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> %.sroa.011.0.vec.insert.3, <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
  tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> %.sroa.011.0.vec.insert.4, i8 2, <64 x float> %48, i32 0, i1 true, i1 false)
  %.sroa.013.0.vec.insert.4 = shufflevector <5 x i32> <i32 576, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> %.sroa.013.0.vec.insert.3, <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
  tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> %.sroa.013.0.vec.insert.4, i8 2, <64 x float> %49, i32 0, i1 true, i1 false)
  %.sroa.07.0.vec.insert.5 = shufflevector <5 x i32> <i32 640, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> %.sroa.07.0.vec.insert.4, <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
  %50 = tail call <64 x float> @llvm.tpc.ld.tnsr.v64f32.i1(<5 x i32> %.sroa.07.0.vec.insert.5, i8 0, i32 0, <64 x float> undef, i1 true, i1 false)
  %.sroa.09.0.vec.insert.5 = shufflevector <5 x i32> <i32 704, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> %.sroa.09.0.vec.insert.4, <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
  %51 = tail call <64 x float> @llvm.tpc.ld.tnsr.v64f32.i1(<5 x i32> %.sroa.09.0.vec.insert.5, i8 0, i32 0, <64 x float> undef, i1 true, i1 false)
  %52 = shufflevector <64 x float> %50, <64 x float> %51, <128 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63, i32 64, i32 65, i32 66, i32 67, i32 68, i32 69, i32 70, i32 71, i32 72, i32 73, i32 74, i32 75, i32 76, i32 77, i32 78, i32 79, i32 80, i32 81, i32 82, i32 83, i32 84, i32 85, i32 86, i32 87, i32 88, i32 89, i32 90, i32 91, i32 92, i32 93, i32 94, i32 95, i32 96, i32 97, i32 98, i32 99, i32 100, i32 101, i32 102, i32 103, i32 104, i32 105, i32 106, i32 107, i32 108, i32 109, i32 110, i32 111, i32 112, i32 113, i32 114, i32 115, i32 116, i32 117, i32 118, i32 119, i32 120, i32 121, i32 122, i32 123, i32 124, i32 125, i32 126, i32 127>
  %53 = tail call <128 x bfloat> @llvm.tpc.fptrunc.swch.v128bf16.v128f32(<128 x float> %52, i32 327680)
  %54 = fmul <128 x bfloat> %7, %53
  %55 = tail call <128 x float> @llvm.tpc.fpext.swch.v128f32.v128bf16(<128 x bfloat> %54, i32 327680)
  %56 = shufflevector <128 x float> %55, <128 x float> undef, <64 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
  %57 = shufflevector <128 x float> %55, <128 x float> undef, <64 x i32> <i32 64, i32 65, i32 66, i32 67, i32 68, i32 69, i32 70, i32 71, i32 72, i32 73, i32 74, i32 75, i32 76, i32 77, i32 78, i32 79, i32 80, i32 81, i32 82, i32 83, i32 84, i32 85, i32 86, i32 87, i32 88, i32 89, i32 90, i32 91, i32 92, i32 93, i32 94, i32 95, i32 96, i32 97, i32 98, i32 99, i32 100, i32 101, i32 102, i32 103, i32 104, i32 105, i32 106, i32 107, i32 108, i32 109, i32 110, i32 111, i32 112, i32 113, i32 114, i32 115, i32 116, i32 117, i32 118, i32 119, i32 120, i32 121, i32 122, i32 123, i32 124, i32 125, i32 126, i32 127>
  %.sroa.011.0.vec.insert.5 = shufflevector <5 x i32> <i32 640, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> %.sroa.011.0.vec.insert.4, <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
  tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> %.sroa.011.0.vec.insert.5, i8 2, <64 x float> %56, i32 0, i1 true, i1 false)
  %.sroa.013.0.vec.insert.5 = shufflevector <5 x i32> <i32 704, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> %.sroa.013.0.vec.insert.4, <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
  tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> %.sroa.013.0.vec.insert.5, i8 2, <64 x float> %57, i32 0, i1 true, i1 false)
  %.sroa.07.0.vec.insert.6 = shufflevector <5 x i32> <i32 768, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> %.sroa.07.0.vec.insert.5, <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
  %58 = tail call <64 x float> @llvm.tpc.ld.tnsr.v64f32.i1(<5 x i32> %.sroa.07.0.vec.insert.6, i8 0, i32 0, <64 x float> undef, i1 true, i1 false)
  %.sroa.09.0.vec.insert.6 = shufflevector <5 x i32> <i32 832, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> %.sroa.09.0.vec.insert.5, <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
  %59 = tail call <64 x float> @llvm.tpc.ld.tnsr.v64f32.i1(<5 x i32> %.sroa.09.0.vec.insert.6, i8 0, i32 0, <64 x float> undef, i1 true, i1 false)
  %60 = shufflevector <64 x float> %58, <64 x float> %59, <128 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63, i32 64, i32 65, i32 66, i32 67, i32 68, i32 69, i32 70, i32 71, i32 72, i32 73, i32 74, i32 75, i32 76, i32 77, i32 78, i32 79, i32 80, i32 81, i32 82, i32 83, i32 84, i32 85, i32 86, i32 87, i32 88, i32 89, i32 90, i32 91, i32 92, i32 93, i32 94, i32 95, i32 96, i32 97, i32 98, i32 99, i32 100, i32 101, i32 102, i32 103, i32 104, i32 105, i32 106, i32 107, i32 108, i32 109, i32 110, i32 111, i32 112, i32 113, i32 114, i32 115, i32 116, i32 117, i32 118, i32 119, i32 120, i32 121, i32 122, i32 123, i32 124, i32 125, i32 126, i32 127>
  %61 = tail call <128 x bfloat> @llvm.tpc.fptrunc.swch.v128bf16.v128f32(<128 x float> %60, i32 327680)
  %62 = fmul <128 x bfloat> %7, %61
  %63 = tail call <128 x float> @llvm.tpc.fpext.swch.v128f32.v128bf16(<128 x bfloat> %62, i32 327680)
  %64 = shufflevector <128 x float> %63, <128 x float> undef, <64 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
  %65 = shufflevector <128 x float> %63, <128 x float> undef, <64 x i32> <i32 64, i32 65, i32 66, i32 67, i32 68, i32 69, i32 70, i32 71, i32 72, i32 73, i32 74, i32 75, i32 76, i32 77, i32 78, i32 79, i32 80, i32 81, i32 82, i32 83, i32 84, i32 85, i32 86, i32 87, i32 88, i32 89, i32 90, i32 91, i32 92, i32 93, i32 94, i32 95, i32 96, i32 97, i32 98, i32 99, i32 100, i32 101, i32 102, i32 103, i32 104, i32 105, i32 106, i32 107, i32 108, i32 109, i32 110, i32 111, i32 112, i32 113, i32 114, i32 115, i32 116, i32 117, i32 118, i32 119, i32 120, i32 121, i32 122, i32 123, i32 124, i32 125, i32 126, i32 127>
  %.sroa.011.0.vec.insert.6 = shufflevector <5 x i32> <i32 768, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> %.sroa.011.0.vec.insert.5, <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
  tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> %.sroa.011.0.vec.insert.6, i8 2, <64 x float> %64, i32 0, i1 true, i1 false)
  %.sroa.013.0.vec.insert.6 = shufflevector <5 x i32> <i32 832, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> %.sroa.013.0.vec.insert.5, <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
  tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> %.sroa.013.0.vec.insert.6, i8 2, <64 x float> %65, i32 0, i1 true, i1 false)
  %.sroa.07.0.vec.insert.7 = shufflevector <5 x i32> <i32 896, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> %.sroa.07.0.vec.insert.6, <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
  %66 = tail call <64 x float> @llvm.tpc.ld.tnsr.v64f32.i1(<5 x i32> %.sroa.07.0.vec.insert.7, i8 0, i32 0, <64 x float> undef, i1 true, i1 false)
  %.sroa.09.0.vec.insert.7 = shufflevector <5 x i32> <i32 960, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> %.sroa.09.0.vec.insert.6, <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
  %67 = tail call <64 x float> @llvm.tpc.ld.tnsr.v64f32.i1(<5 x i32> %.sroa.09.0.vec.insert.7, i8 0, i32 0, <64 x float> undef, i1 true, i1 false)
  %68 = shufflevector <64 x float> %66, <64 x float> %67, <128 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63, i32 64, i32 65, i32 66, i32 67, i32 68, i32 69, i32 70, i32 71, i32 72, i32 73, i32 74, i32 75, i32 76, i32 77, i32 78, i32 79, i32 80, i32 81, i32 82, i32 83, i32 84, i32 85, i32 86, i32 87, i32 88, i32 89, i32 90, i32 91, i32 92, i32 93, i32 94, i32 95, i32 96, i32 97, i32 98, i32 99, i32 100, i32 101, i32 102, i32 103, i32 104, i32 105, i32 106, i32 107, i32 108, i32 109, i32 110, i32 111, i32 112, i32 113, i32 114, i32 115, i32 116, i32 117, i32 118, i32 119, i32 120, i32 121, i32 122, i32 123, i32 124, i32 125, i32 126, i32 127>
  %69 = tail call <128 x bfloat> @llvm.tpc.fptrunc.swch.v128bf16.v128f32(<128 x float> %68, i32 327680)
  %70 = fmul <128 x bfloat> %7, %69
  %71 = tail call <128 x float> @llvm.tpc.fpext.swch.v128f32.v128bf16(<128 x bfloat> %70, i32 327680)
  %72 = shufflevector <128 x float> %71, <128 x float> undef, <64 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
  %73 = shufflevector <128 x float> %71, <128 x float> undef, <64 x i32> <i32 64, i32 65, i32 66, i32 67, i32 68, i32 69, i32 70, i32 71, i32 72, i32 73, i32 74, i32 75, i32 76, i32 77, i32 78, i32 79, i32 80, i32 81, i32 82, i32 83, i32 84, i32 85, i32 86, i32 87, i32 88, i32 89, i32 90, i32 91, i32 92, i32 93, i32 94, i32 95, i32 96, i32 97, i32 98, i32 99, i32 100, i32 101, i32 102, i32 103, i32 104, i32 105, i32 106, i32 107, i32 108, i32 109, i32 110, i32 111, i32 112, i32 113, i32 114, i32 115, i32 116, i32 117, i32 118, i32 119, i32 120, i32 121, i32 122, i32 123, i32 124, i32 125, i32 126, i32 127>
  %.sroa.011.0.vec.insert.7 = shufflevector <5 x i32> <i32 896, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> %.sroa.011.0.vec.insert.6, <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
  tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> %.sroa.011.0.vec.insert.7, i8 2, <64 x float> %72, i32 0, i1 true, i1 false)
  %.sroa.013.0.vec.insert.7 = shufflevector <5 x i32> <i32 960, i32 undef, i32 0, i32 0, i32 undef>, <5 x i32> %.sroa.013.0.vec.insert.6, <5 x i32> <i32 0, i32 6, i32 2, i32 3, i32 9>
  tail call void @llvm.tpc.st.tnsr.v64f32(<5 x i32> %.sroa.013.0.vec.insert.7, i8 2, <64 x float> %73, i32 0, i1 true, i1 false)
  %74 = add nsw i32 %9, 1
  %75 = icmp slt i32 %74, %5
  br i1 %75, label %.lr.ph, label %._crit_edge

._crit_edge:                                      ; preds = %.lr.ph, %0
  ret void
}

; Function Attrs: nounwind readonly
declare <128 x bfloat> @llvm.tpc.ld.g.v128bf16.i1(i8 addrspace(3)*, i32, <128 x bfloat>, i1, i1) #3

attributes #0 = { nounwind readnone }
attributes #1 = { nounwind writeonly }
attributes #2 = { nounwind }
attributes #3 = { nounwind readonly }

!llvm.module.flags = !{!0}

!0 = !{i32 2, !"Debug Info Version", i32 3}
