# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=tpc -mcpu=doron1 -run-pass=tpc-pred %s -o - | FileCheck %s

--- |
  ; Function Attrs: nofree nounwind willreturn
  define dso_local void @main(i32 %mem_src, i32 %mem_dst) local_unnamed_addr {
  entry:
    %0 = inttoptr i32 %mem_dst to <128 x bfloat> addrspace(2)*
    %1 = inttoptr i32 %mem_src to <128 x float> addrspace(2)*
    %2 = load <128 x float>, <128 x float> addrspace(2)* %1, align 256
    %3 = tail call <128 x bfloat> @llvm.tpc.convert.v128bf16.v128f32.i1(<128 x float> %2, i8 0, i32 256, <128 x bfloat> zeroinitializer, i1 true, i1 false)
    store <128 x bfloat> %3, <128 x bfloat> addrspace(2)* %0, align 256
    ret void
  }

  ; Function Attrs: nounwind readnone
  declare <128 x bfloat> @llvm.tpc.convert.v128bf16.v128f32.i1(<128 x float>, i8, i32, <128 x bfloat>, i1, i1)

...
---
name:            main
tracksRegLiveness: true
liveins:
  - { reg: '$s0', virtual-reg: '%0' }
  - { reg: '$s1', virtual-reg: '%1' }
body:             |
  bb.0.entry:
    liveins: $s0, $s1

    ; CHECK-LABEL: name: main
    ; CHECK: liveins: $s0, $s1
    ; CHECK: [[COPY:%[0-9]+]]:srf = COPY $s1
    ; CHECK: [[COPY1:%[0-9]+]]:srf = COPY $s0
    ; CHECK: [[DEF:%[0-9]+]]:vrf = IMPLICIT_DEF
    ; CHECK: [[LD_L_Vvsp:%[0-9]+]]:vrf = LD_L_Vvsp [[COPY1]], 0, [[DEF]], $sprf_true, 0 :: (load 256 from %ir.1, addrspace 2)
    ; CHECK: [[DEF1:%[0-9]+]]:srf = IMPLICIT_DEF
    ; CHECK: [[ADDsip:%[0-9]+]]:srf = ADDsip [[COPY1]], 256, 2, 0, [[DEF1]], $sprf_true, 0
    ; CHECK: [[DEF2:%[0-9]+]]:vrf = IMPLICIT_DEF
    ; CHECK: [[LD_L_Vvsp1:%[0-9]+]]:vrf = LD_L_Vvsp killed [[ADDsip]], 0, [[DEF2]], $sprf_true, 0 :: (load 256 from %ir.1 + 256, addrspace 2)
    ; CHECK: [[REG_SEQUENCE:%[0-9]+]]:drf = REG_SEQUENCE killed [[LD_L_Vvsp]], %subreg.sub_0, killed [[LD_L_Vvsp1]], %subreg.sub_1
    ; CHECK: [[DEF3:%[0-9]+]]:vrf = IMPLICIT_DEF
    ; CHECK: [[MOV_ld_vip:%[0-9]+]]:vrf = MOV_ld_vip 0, 1, 0, [[DEF3]], $sprf_true, 0
    ; CHECK: [[COPY2:%[0-9]+]]:sprf = COPY $sprf_true
    ; CHECK: [[DEF4:%[0-9]+]]:vrf = IMPLICIT_DEF
    ; CHECK: [[CONVERTg3vdp:%[0-9]+]]:vrf = CONVERTg3vdp killed [[REG_SEQUENCE]], 0, 256, [[DEF4]], $sprf_true, 0
    ; CHECK: ST_L_Vsvp [[COPY]], killed [[CONVERTg3vdp]], 0, $sprf_true, 0 :: (store 256 into %ir.0, addrspace 2)
    ; CHECK: HALTs
    %1:srf = COPY $s1
    %0:srf = COPY $s0
    %3:vrf = IMPLICIT_DEF
    %2:vrf = LD_L_Vvsp %0, 0, %3, $sprf_true, 0 :: (load 256 from %ir.1, addrspace 2)
    %5:srf = IMPLICIT_DEF
    %4:srf = ADDsip %0, 256, 2, 0, %5, $sprf_true, 0
    %7:vrf = IMPLICIT_DEF
    %6:vrf = LD_L_Vvsp killed %4, 0, %7, $sprf_true, 0 :: (load 256 from %ir.1 + 256, addrspace 2)
    %8:drf = REG_SEQUENCE killed %2, %subreg.sub_0, killed %6, %subreg.sub_1
    %10:vrf = IMPLICIT_DEF
    %9:vrf = MOV_ld_vip 0, 1, 0, %10, $sprf_true, 0
    %11:sprf = COPY $sprf_true
    %12:vrf = CONVERTg3vdp killed %8, 0, 256, %9, killed %11, 0
    ST_L_Vsvp %1, killed %12, 0, $sprf_true, 0 :: (store 256 into %ir.0, addrspace 2)
    HALTs

...
